# Summary

How the summary ranking is computed:

1. **Evidence.** Every axis (replicate agreement, functional sensitivity and precision, state recovery, ...)
   gives one value of its metric per method and dataset cell (`encode:pooled`,
   `encode:replicates`, `sagaconf`, `epi1000`), averaged over the datasets or
   sample pairs every method of the cell reached.
2. **Rank score** (`rank_scores`). Methods are compared only within their family
   (individual or joint) and only on the same comparison unit. A method scores
   `1 - (methods of its family that beat it) / (n - 1)` in the axis' direction:
   1 = nobody did better (ties for best all get 1), 0 = every other method did
   better. A unit with a single method or where all methods tie separates
   nothing and is left unscored.
3. **Cell scores** (`score_evidence`). For most axes the unit is the cell
   itself, so the cell score is the rank score of the cell's value. The
   cross-assay axes and the ENCODE joint cross-sample axis are ranked inside
   every sample pair instead, because their methods reached different pairs;
   their cell score is the mean of those per-pair rank scores, and is not
   ranked again.
4. **Axis scores** (`axis_scores`). The mean of the cell scores; the
   per-metric variants are averaged into their main axis. The
   individual / joint axes are scored for the joint model of each pair, so
   they rank the joint models and the individual ones have none; the joint
   models have no cross-assay axes.
5. **Summary score** (`summary_ranking`). The weighted mean of a method's axis
   scores, weighted by `AXIS_WEIGHTS` (1 for an axis not listed), sorted within
   each family. The two families are scored over different axes, so a joint and
   an individual score are not comparable and there is no combined ranking.

The ENCODE reference markup is scored as one more individual model, on the
ENCODE axes it has: it has no replicates or joint counterpart, so it is ranked
on the functional, segmentation, cross-sample and cross-assay axes only.

The grouped rankings take the same weighted mean over the axes of each
`RANKING_GROUPS` group only; an axis in no group counts in the summary
score alone.

# 1. Performing computations

In [1]:
import glob
import importlib
import os
import re
import sys

import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import numpy as np
import pandas as pd
import seaborn as sns
import yaml

# Load configuration and find project root
if "PROJECT_ROOT" not in globals():
    PROJECT_ROOT = None
    for _p in [os.getcwd()] + sys.path:
        _curr = os.path.abspath(_p) if _p else ""
        while _curr and _curr != os.path.dirname(_curr):
            if os.path.exists(os.path.join(_curr, "scripts/analysis/analyze.py")):
                PROJECT_ROOT = _curr
                break
            _curr = os.path.dirname(_curr)
        if PROJECT_ROOT: break
    if not PROJECT_ROOT:
        PROJECT_ROOT = os.getcwd()

scripts_dir = os.path.abspath(os.path.join(PROJECT_ROOT, "scripts", "analysis"))
if scripts_dir not in sys.path:
    sys.path.insert(0, scripts_dir)

import display as _display_helpers
import utils

for _m in (utils, _display_helpers):
    importlib.reload(_m)

# The project's plot style (fonts, PDF output) from utils, set once for every
# plot below; after the reload, so a re-run picks up edits to utils.py.
utils.set_style()

from utils import (
    AMI, AMI_DISPLAY, CALLER_KEYS, CHROMHMM_DEFAULT, COMPOSITION_DISPLAY, COSINE,
    JACCARD,
    JACCARD_DISPLAY, JOINT_CHROMHMM, JOINT_HATCH, JOINT_KMEANS_HOMER,
    JOINT_KMEANS_MACS2, JOINT_KMEANS_OMNI, 
    BMM3_HOMER, BMM3_MACS2, BMM3_OMNI, JOINT_BMM3_HOMER, JOINT_BMM3_MACS2, JOINT_BMM3_OMNI,
    KAPPA, KAPPA_DISPLAY, KMEANS_HOMER,
    KMEANS_MACS2, KMEANS_OMNI, POINT_SIZE,
    PRECISION_DISPLAY, SENSITIVITY_DISPLAY,
    ACTIVE_OPEN_STATES, PROMOTER_CORE_STATES,
)
from display import header

FUNCTIONAL_TARGETS = (
    ("functional_atac", "Active chromatin vs ATAC-seq",
     ACTIVE_OPEN_STATES, "atac_"),
    ("functional_tss", "Tss states vs expressed TSS",
     PROMOTER_CORE_STATES, "ExpressedTSS2kb"),
    ("functional_refseq_tss", "Tss states vs RefSeq TSS",
     PROMOTER_CORE_STATES, "RefSeqTSS2kb"),
    ("functional_tx", "Tx state vs expressed genes",
     "Tx", "ExpressedGeneBodies"),
)

In [2]:
COMPARISON_METRICS = [KAPPA, AMI]

# The cosine is collected next to them but ranked as axes of its own: the
# composition similarity, over every state except the biggest one of either
# side, so the quiescent majority both segmentations share does not decide it.
COLLECTED_METRICS = COMPARISON_METRICS + [COSINE]

COSINE_LABEL = ("the Cosine similarity of the state compositions, the biggest "
                "state of either side left out")

AXIS_WEIGHTS = {
    # Requested number of states
    "state_recovery": 5,
    # Replicates
    "replicates": 3,
    "replicates_cosine": 3,
    "replicates_emissions": 3,
    # Biological assay
    "functional_atac_sensitivity": 2,
    "functional_atac_precision": 2,
    "functional_tss_sensitivity": 2,
    "functional_tss_precision": 2,
    "functional_refseq_tss_sensitivity": 2,
    "functional_refseq_tss_precision": 2,
    "functional_tx_sensitivity": 2,
    "functional_tx_precision": 2,
}


METRICS_SLASH_LABEL = " / ".join(utils.metric_display(m) for m in COMPARISON_METRICS)
METRICS_LABEL = " and ".join(utils.metric_display(m) for m in COMPARISON_METRICS)
print(f"  metrics {COMPARISON_METRICS}, composition [{COSINE!r}]")

OUT = "out/summary"
os.makedirs(OUT, exist_ok=True)

  metrics ['kappa', 'ami'], composition ['cosine']

In [3]:
# The published ENCODE reference markup, one per ENCODE dataset: an
# individual model, scored and drawn with them on ENCODE alone.
REFERENCE = "reference"

METHODS = [
    # ENCODE reference
    REFERENCE,
    # ChromHMM
    CHROMHMM_DEFAULT,
    JOINT_CHROMHMM,
    # HOMER
    KMEANS_HOMER,
    BMM3_HOMER,
    JOINT_KMEANS_HOMER,
    JOINT_BMM3_HOMER,
    # MACS2
    KMEANS_MACS2,
    BMM3_MACS2,
    JOINT_KMEANS_MACS2,
    JOINT_BMM3_MACS2,
    # OmniPeak
    KMEANS_OMNI,
    BMM3_OMNI,
    JOINT_KMEANS_OMNI,
    JOINT_BMM3_OMNI,
]

def is_joint(method):
    """True for a joint model: the family a method is scored and ranked in."""
    return str(method).startswith("joint")


INDIVIDUAL_METHODS = [m for m in METHODS if not is_joint(m)]
JOINT_METHODS = [m for m in METHODS if is_joint(m)]

# The joint model of every individual one: its caller's joint model of the
# same kind.
JOINT_OF = {keys[indiv]: keys[joint] for keys in CALLER_KEYS.values()
            for indiv, joint in [(0, 1), (2, 3)]}


DATASETS = ["encode", "sagaconf", "epi1000"]

DATASET_NAMES = {"encode": "ENCODE", "sagaconf": "SAGAconf", "epi1000": "1000 epigenomes"}

AXES = {
    "replicates": (
        "Replicate\nagreement", "high", METRICS_SLASH_LABEL,
        f"Agreement between segmentations of biological replicates of the same "
        f"condition, averaged over {METRICS_LABEL}."),
    "replicates_cosine": (
        "Replicate\ncomposition", "high", "Cosine",
        f"Agreement of state composition between biological replicates, "
        f"measured by {COSINE_LABEL}."),
    "replicates_emissions": (
        "Replicate emission\nsimilarity", "high", "cosine of the state emissions",
        "Similarity of the state signatures a method learns from the two "
        "replicates of a sample: the mean cosine of the emission vectors of "
        "the matched states, over the one-to-one matching of the two state "
        "spaces. Higher means the same biology is described by the same state "
        "definitions."),
    "cross_sample": (
        "Cross-sample\nagreement", "high", METRICS_SLASH_LABEL,
        f"Agreement between segmentations of different samples, averaged over "
        f"{METRICS_LABEL}. The two families are compared "
        f"over different sample sets, which costs nothing because they are "
        f"ranked apart: on ENCODE the individual models are read over every "
        f"pair of the 15 datasets, the joint ones - which exist per dataset "
        f"rather than per sample - over the pairs of the three datasets that "
        f"have replicates."),
    "cross_sample_cosine": (
        "Cross-sample\ncomposition", "high", "Cosine",
        f"Agreement of state composition between different samples, "
        f"measured by {COSINE_LABEL}."),
    "joint_indiv": (
        "Individual /\njoint agreement", "high", METRICS_SLASH_LABEL,
        f"Agreement of a sample segmented on its own with the same sample "
        f"segmented inside a joint model, averaged over {METRICS_LABEL}. "
        f"Scored for the joint model: how much of each sample's own "
        f"segmentation it keeps."),
    "joint_indiv_cosine": (
        "Individual / joint\ncomposition agreement", "high", "Cosine",
        f"Agreement of state composition between individual and joint "
        f"segmentations, measured by {COSINE_LABEL}."),
    "entropy": (
        "Transition Matrix\nEntropy stability", "low", "CV of entropy",
        "Coefficient of variation of the state transition matrix entropy "
        "across the samples of a dataset. Lower means the fragmentation "
        "is more consistent across samples."),
    "functional_atac_sensitivity": (
        "Active chromatin\nvs ATAC-seq (Sensitivity)", "high", SENSITIVITY_DISPLAY,
        f"Overlap of the active states (the promoter and enhancer families) "
        f"with the ATAC-seq peaks of the same sample, measured by {SENSITIVITY_DISPLAY}: "
        f"the share of the annotation the family covers."),
    "functional_atac_precision": (
        "Active chromatin\nvs ATAC-seq (Precision)", "high", PRECISION_DISPLAY,
        f"Overlap of the active states (the promoter and enhancer families) "
        f"with the ATAC-seq peaks of the same sample, measured by {PRECISION_DISPLAY}: "
        f"the annotated share of the state family."),
    "functional_tss_sensitivity": (
        "Tss states vs\nexpressed TSS (Sensitivity)", "high", SENSITIVITY_DISPLAY,
        f"Overlap of the Tss state family (Tss and its flanking states) with "
        f"the RNA-seq-expressed transcription start sites of the same sample, "
        f"+-2 kb, measured by {SENSITIVITY_DISPLAY}: "
        f"the share of the annotation the family covers."),
    "functional_tss_precision": (
        "Tss states vs\nexpressed TSS (Precision)", "high", PRECISION_DISPLAY,
        f"Overlap of the Tss state family (Tss and its flanking states) with "
        f"the RNA-seq-expressed transcription start sites of the same sample, "
        f"+-2 kb, measured by {PRECISION_DISPLAY}: "
        f"the annotated share of the state family."),
    "functional_refseq_tss_sensitivity": (
        "Tss states vs\nRefSeq TSS (Sensitivity)", "high", SENSITIVITY_DISPLAY,
        f"Overlap of the Tss state family (Tss and its flanking states) with "
        f"the RefSeq transcription start sites, +-2 kb, measured by {SENSITIVITY_DISPLAY}: "
        f"the share of the annotation the family covers."),
    "functional_refseq_tss_precision": (
        "Tss states vs\nRefSeq TSS (Precision)", "high", PRECISION_DISPLAY,
        f"Overlap of the Tss state family (Tss and its flanking states) with "
        f"the RefSeq transcription start sites, +-2 kb, measured by {PRECISION_DISPLAY}: "
        f"the annotated share of the state family."),
    "functional_tx_sensitivity": (
        "Tx state vs\nexpressed genes (Sensitivity)", "high", SENSITIVITY_DISPLAY,
        f"Overlap of the Tx state alone (without TxWk) with the "
        f"RNA-seq-expressed gene bodies of the same sample, measured by {SENSITIVITY_DISPLAY}: "
        f"the share of the annotation the state covers."),
    "functional_tx_precision": (
        "Tx state vs\nexpressed genes (Precision)", "high", PRECISION_DISPLAY,
        f"Overlap of the Tx state alone (without TxWk) with the "
        f"RNA-seq-expressed gene bodies of the same sample, measured by {PRECISION_DISPLAY}: "
        f"the annotated share of the state."),
    "state_recovery": (
        "Recovery of requested\nstate count", "high", "fraction reaching k=15",
        "Fraction of segmentations that actually realize the 15 requested "
        "states instead of collapsing some of them."),
    "segments_stability": (
        "Segment-count\nstability", "low", "CV of segment number",
        "Coefficient of variation of the number of segments across the "
        "samples of a dataset — how much the granularity drifts with input."),
    "cross_assay_agreement": (
        "Cross-assay\nagreement", "high", METRICS_SLASH_LABEL,
        f"Agreement between the ChIP-seq and the Mint-ChIP segmentations of a "
        f"caller, over every ChIP x Mint pair of samples, so it asks how much "
        f"agreement survives a change of assay and of cell type together. "
        f"Read on raw states using remapping to align the two vocabularies, "
        f"over {METRICS_LABEL}. The callers are ranked inside each pair "
        f"and those ranks averaged, since a caller whose Mint-ChIP model "
        f"collapsed has fewer usable pairs than the others."),
    "cross_assay_agreement_cosine": (
        "Cross-assay\ncomposition agreement", "high", "Cosine",
        f"Agreement of state composition between the ChIP-seq and the "
        f"Mint-ChIP segmentations of a caller, on the same rematched raw state "
        f"labels and pairs as the axis above and ranked inside each pair the "
        f"same way, measured by {COSINE_LABEL}."),
    "cross_assay_segments_stability": (
        "Cross-assay\ncounts stability", "low", "CV of segment number",
        "Coefficient of variation of the number of segments between the "
        "ChIP-seq and the Mint-ChIP segmentation of a caller, over every "
        "ChIP x Mint pair of datasets - the pairs the two cross-assay "
        "agreement axes are read over. The callers are ranked inside each "
        "pair and those ranks averaged, since a caller whose Mint-ChIP model "
        "collapsed has fewer usable pairs than the others."),
}

AXIS_ORDER = [
    "replicates", "replicates_cosine",
    "replicates_emissions",
    "functional_atac_sensitivity", "functional_atac_precision",
    "functional_tss_sensitivity", "functional_tss_precision",
    "functional_refseq_tss_sensitivity", "functional_refseq_tss_precision",
    "functional_tx_sensitivity", "functional_tx_precision",
    "state_recovery", "segments_stability",
    "entropy",
    "cross_sample", "cross_sample_cosine",
    "cross_assay_segments_stability", "cross_assay_agreement", "cross_assay_agreement_cosine",
    "joint_indiv", "joint_indiv_cosine",
]

UNBOUNDED_AXES = {"entropy", "segments_stability",
                  "cross_assay_segments_stability"}

RANKING_GROUPS = {
    "Replicates": ["replicates", "replicates_cosine", "replicates_emissions"],
    "Biological assay": [
        "functional_atac_sensitivity", "functional_atac_precision",
        "functional_tss_sensitivity", "functional_tss_precision",
        "functional_refseq_tss_sensitivity", "functional_refseq_tss_precision",
        "functional_tx_sensitivity", "functional_tx_precision",
    ],
    "Segmentation": ["state_recovery", "segments_stability", "entropy"],
    "Cross-sample": ["cross_sample", "cross_sample_cosine"],
    "Assay": ["cross_assay_segments_stability", "cross_assay_agreement", "cross_assay_agreement_cosine"],
    "Individual / Join": ["joint_indiv", "joint_indiv_cosine"]
}

# The agreement axes are averaged over their `{axis}_{metric}` variants; the
# `{axis}_cosine` axes and the entropy are collected under their own name.
VARIANT_MAIN_AXES = ["replicates", "cross_sample", "joint_indiv",
                     "cross_assay_agreement"]


def axis_variants(main):
    """The per-metric variants an axis is built from."""
    return [f"{main}_{m}" for m in COMPARISON_METRICS]


VARIANT_AXES = []
for main in VARIANT_MAIN_AXES:
    for v in axis_variants(main):
        if v in AXES:
            continue
        AXES[v] = (v, AXES[main][1], AXES[main][2], "Variant for ranking")
        VARIANT_AXES.append(v)

ALL_AXIS_CATEGORIES = AXIS_ORDER + VARIANT_AXES

EVIDENCE_COLUMNS = ["Axis", "Dataset", "Cell", "Method", "Value", "score",
                    "N", "Note"]


def canonical(name):
    """The method key of `name`; the ENCODE reference under any of its names,
    its segmentation (ENCFF..._chromhmm) or its display name."""
    key = str(name).strip().lower().replace(" ", "_")
    if key in ("ref", REFERENCE, "encode_ref", "encode_reference") \
            or re.fullmatch(r"encff\w+_chromhmm", key):
        return REFERENCE
    return utils.normalize_method(name)


def axis_label(axis, oneline=False):
    label = AXES[str(axis)][0]
    return label.replace("\n", " ") if oneline else label


WORKDIRS, DATASET_KEYS, DATASET_CELLS = {}, {}, {}
for dataset, config_file in [("encode", "config_encode.yaml"),
                             ("sagaconf", "config_sagaconf.yaml")]:
    with open(os.path.join(PROJECT_ROOT, config_file)) as f:
        dataset_config = yaml.safe_load(f)
    WORKDIRS[dataset] = dataset_config["workdir"]
    # The config's outliers are left out of every collected axis.
    outliers = set(dataset_config.get("outliers") or ())
    DATASET_KEYS[dataset] = [ds for ds in dataset_config["datasets"]
                             if ds not in outliers]
    DATASET_CELLS[dataset] = {ds: cfg["cell"] for ds, cfg
                              in dataset_config["datasets"].items()}
WORKDIRS["epi1000"] = os.path.join(os.path.dirname(WORKDIRS["encode"]), "epi1000")

for dataset, workdir in WORKDIRS.items():
    present = os.path.isdir(os.path.join(os.path.expanduser(workdir), "out"))
    known = DATASET_KEYS.get(dataset)
    print(f"  {DATASET_NAMES[dataset]:16s} {workdir}"
          f"{f'   ({len(known)} datasets)' if known else ''}"
          f"{'' if present else '   (no out/ — run its notebook first)'}")

  ENCODE           ~/data/2026_segmentations/encode   (12 datasets)
  SAGAconf         ~/data/2026_segmentations/sagaconf   (5 datasets)
  1000 epigenomes  ~/data/2026_segmentations/epi1000

In [4]:
pd.DataFrame([{"Axis": axis_label(a, oneline=True), "Metric": AXES[a][2],
               "Better": AXES[a][1], "What it measures": AXES[a][3]}
              for a in AXIS_ORDER])

,Axis,Metric,Better,What it measures
0,Replicate agreement,Kappa / AMI,high,Agreement between segmentations of biological ...
1,Replicate composition,Cosine,high,Agreement of state composition between biologi...
2,Replicate emission similarity,cosine of the state emissions,high,Similarity of the state signatures a method le...
3,Active chromatin vs ATAC-seq (Sensitivity),Sensitivity,high,Overlap of the active states (the promoter and...
4,Active chromatin vs ATAC-seq (Precision),Precision,high,Overlap of the active states (the promoter and...
5,Tss states vs expressed TSS (Sensitivity),Sensitivity,high,Overlap of the Tss state family (Tss and its f...
6,Tss states vs expressed TSS (Precision),Precision,high,Overlap of the Tss state family (Tss and its f...
7,Tss states vs RefSeq TSS (Sensitivity),Sensitivity,high,Overlap of the Tss state family (Tss and its f...
8,Tss states vs RefSeq TSS (Precision),Precision,high,Overlap of the Tss state family (Tss and its f...
9,Tx state vs expressed genes (Sensitivity),Sensitivity,high,Overlap of the Tx state alone (without TxWk) w...
10,Tx state vs expressed genes (Precision),Precision,high,Overlap of the Tx state alone (without TxWk) w...
11,Recovery of requested state count,fraction reaching k=15,high,Fraction of segmentations that actually realiz...
12,Segment-count stability,CV of segment number,low,Coefficient of variation of the number of segm...
13,Transition Matrix Entropy stability,CV of entropy,low,Coefficient of variation of the state transiti...
14,Cross-sample agreement,Kappa / AMI,high,Agreement between segmentations of different s...
15,Cross-sample composition,Cosine,high,Agreement of state composition between differe...
16,Cross-assay counts stability,CV of segment number,low,Coefficient of variation of the number of segm...
17,Cross-assay agreement,Kappa / AMI,high,Agreement between the ChIP-seq and the Mint-Ch...
18,Cross-assay composition agreement,Cosine,high,Agreement of state composition between the ChI...
19,Individual / joint agreement,Kappa / AMI,high,Agreement of a sample segmented on its own wit...
20,Individual / joint composition agreement,Cosine,high,Agreement of state composition between individ...

## Reading the caches into one evidence table

In [5]:
def _rows(axis, dataset, values, note, cell=None, n=None, scores=None):
    """Evidence rows for one axis, `values` keyed by method. `scores` are
    the cell scores of an axis ranked inside its sample pairs; every other
    axis is scored later, by `score_evidence`."""
    return [{"Axis": axis, "Dataset": dataset, "Cell": cell or dataset,
             "Method": method, "Value": float(value),
             "score": (scores or {}).get(method, np.nan), "Note": note,
             "N": (n or {}).get(method, np.nan)}
            for method, value in values.items()
            if method in METHODS and value is not None and not pd.isna(value)]


def rank_scores(values, high=True):
    """`1 - (methods that beat it) / (n - 1)` per method of one comparison
    unit: 1 for the best and every method tied with it, 0 when all the others
    do better. None for a unit that separates nothing - a single method, or
    all of them tied."""
    values = pd.Series(values, dtype=float)
    if values.nunique() < 2:
        return None
    beaten_by = values.rank(ascending=not high, method="min") - 1
    return 1 - beaten_by / (len(values) - 1)


_SAID = set()


def _say_once(message):
    """Print `message` unless this run has already printed it."""
    if message not in _SAID:
        _SAID.add(message)
        print(message)


def _common_units(df, keys, unit_col, where):
    """`df` cut down to the comparison units every method in it has a value
    for."""
    units = df[unit_col].astype(str)
    per_method = {method: set(group) for method, group in units.groupby(keys)}
    if not per_method:
        return df, keys
    common = set.intersection(*per_method.values())
    dropped = sorted(set.union(*per_method.values()) - common)
    if dropped:
        _say_once(f"  {where}: {len(dropped)} of {len(dropped) + len(common)} "
                  f"comparison units are missing for at least one method and "
                  f"go for all of them, so the averages cover the same units "
                  f"({', '.join(dropped)})")
    keep = units.isin(common)
    return df[keep], keys[keep]


def _unit_ranks(df, keys, value_col, unit_col, where, high=True):
    """Mean within-unit rank score per method, and the unit count behind it."""
    frame = pd.DataFrame({"method": list(keys),
                          "unit": list(df[unit_col].astype(str)),
                          "value": list(df[value_col].astype(float))})
    units = frame["unit"].nunique()
    scores, alone = {}, 0
    for _, side in frame.groupby(["unit", frame["method"].map(is_joint)]):
        unit_scores = rank_scores(side["value"].values, high=high)
        if unit_scores is None:
            alone += 1
            continue
        for method, score in zip(side["method"], unit_scores):
            scores.setdefault(method, []).append(score)
    reached = frame.groupby("method")["unit"].nunique()
    partial = reached[reached < units]
    if len(partial):
        _say_once(f"  {where}: "
                  + ", ".join(f"{m} reached {n} of {units} comparison units"
                              for m, n in partial.items())
                  + " - the methods are ranked inside each unit and those "
                    "ranks averaged, so a unit one method missed costs "
                    "neither that method the axis nor the others the unit")
    if alone:
        _say_once(f"  {where}: {alone} comparison unit(s) carry a single model "
                  f"of its family or a tie of all of them, so they hold no "
                  f"ranking and are left out")
    return ({m: float(np.mean(v)) for m, v in scores.items()},
            {m: len(v) for m, v in scores.items()})


def _aggregate(df, method_col, value_col, mapper=canonical, unit_col=None,
               where=None, balance="units", high=True):
    """Mean and count of `value_col` per method."""
    keys = df[method_col].map(mapper)
    keep = keys.notna() & df[value_col].notna()
    df, keys = df.loc[keep], keys[keep]
    if unit_col is None:
        grouped = df.groupby(keys)[value_col]
        return grouped.mean().to_dict(), grouped.size().to_dict()
    if balance == "ranks":
        return _unit_ranks(df, keys, value_col, unit_col, where, high=high)
    df, keys = _common_units(df, keys, unit_col, where)
    grouped = df.groupby(keys)[value_col]
    return grouped.mean().to_dict(), grouped.size().to_dict()


def _no_cache(where, what):
    print(f"  {where}: no {what}, that variant is omitted")


def _find_column(df, *candidates):
    """The first of `candidates` among the columns of `df`,
    case-insensitively."""
    lookup = {str(c).lower(): c for c in df.columns}
    for candidate in candidates:
        if candidate is not None and str(candidate).lower() in lookup:
            return lookup[str(candidate).lower()]
    return None


def _metric_column(df, metric, where):
    """The column holding `metric`, under any of its spellings."""
    candidates = list(utils.metric_aliases(metric))
    col = _find_column(df, *candidates)
    if col is None:
        _no_cache(where, f"a {metric} column (looked for {candidates})")
    return col


def _metric_rows(rows, axis, dataset, where, note, method_col="Method",
                 unit_col="Dataset", balance="units"):
    """One `{axis}_{metric}` variant per collected metric of a cache."""
    evidence = []
    for metric in COLLECTED_METRICS:
        col = _metric_column(rows, metric, where)
        if col is None:
            continue
        values, counts = _aggregate(rows, method_col, col, unit_col=unit_col,
                                    where=where, balance="units")
        scores = None
        if balance == "ranks":
            scores, counts = _aggregate(rows, method_col, col,
                                        unit_col=unit_col, where=where,
                                        balance="ranks",
                                        high=AXES[axis][1] == "high")
        evidence += _rows(f"{axis}_{metric}", dataset, values,
                          f"{note} ({utils.metric_display(metric)})",
                          n=counts, scores=scores)
    return evidence


def _cv(values):
    values = np.asarray([v for v in values if v is not None and not pd.isna(v)],
                        dtype=float)
    if len(values) < 2 or values.mean() == 0:
        return np.nan
    return float(values.std(ddof=1) / values.mean())


def _segments_stability(dataset, df, method_col, segments_col, cell=None,
                        unit_col=None, where=None):
    keys = df[method_col].map(canonical)
    keep = keys.notna()
    df, keys = df.loc[keep], keys[keep]
    if unit_col is not None:
        df, keys = _common_units(df, keys, unit_col, where)
    grouped = df.groupby(keys)[segments_col]
    values = {method: _cv(group.values) for method, group in grouped}
    return _rows("segments_stability", dataset, values, cell=cell,
                 note=f"CV of the segment number over {len(df)} "
                      f"segmentations", n=grouped.size().to_dict())


def _entropy_stability(dataset, axis, df, method_col, value_col, unit_col=None,
                       cell=None, where=None, note=None):
    keys = df[method_col].map(canonical)
    keep = keys.notna()
    df, keys = df.loc[keep], keys[keep]
    if unit_col is not None:
        df, keys = _common_units(df, keys, unit_col, where)
    grouped = df.groupby(keys)[value_col]
    values = {method: _cv(group.values) for method, group in grouped}
    return _rows(axis, dataset, values, cell=cell,
                 note=f"{note} over {len(df)} segmentations",
                 n=grouped.size().to_dict())


def _replicate_emissions(out, datasets):
    """rep1-vs-rep2 emission similarity of every method, one row per
    dataset."""
    frames = []
    for ds in datasets:
        for rel in ("matched/comparison_all_pairs.tsv",
                    "matched/joint/comparison_all_pairs.tsv"):
            path = f"{out}/{ds}/{rel}"
            if not os.path.exists(path):
                continue
            df = _read(path)
            if df is None or utils.EMISSION not in df.columns:
                continue
            seg1, seg2 = df["seg1"].astype(str), df["seg2"].astype(str)
            pairs = [utils.is_replicate(a) and utils.should_compare(a, b)
                     for a, b in zip(seg1, seg2)]
            rows = df[pairs].dropna(subset=[utils.EMISSION])
            if rows.empty:
                continue
            frames.append(pd.DataFrame({
                "Dataset": ds,
                "Method": rows["seg1"].astype(str).str[:-len("_rep1")],
                utils.EMISSION: rows[utils.EMISSION].astype(float),
            }))
    if not frames:
        return None
    return (pd.concat(frames, ignore_index=True)
            .drop_duplicates(subset=["Dataset", "Method"]))


def _emission_rows(dataset, out, datasets, excluded, where):
    """The emission similarity evidence of one dataset, empty when uncached."""
    emissions = _drop_excluded(_replicate_emissions(out, datasets), excluded)
    if emissions is None or emissions.empty:
        _no_cache(where, f"{utils.EMISSION} in the all-pairs comparison "
                         f"tables")
        return []
    values, counts = _aggregate(emissions, "Method", utils.EMISSION,
                                unit_col="Dataset",
                                where=f"{where} all-pairs comparison tables")
    return _rows("replicates_emissions", dataset, values,
                 f"rep1 vs rep2 cosine of the matched state emission vectors, "
                 f"over {len(emissions)} segmentation pairs", n=counts)


def _read(path, **kwargs):
    if not os.path.exists(path):
        print(f"  missing {path}")
        return None
    if path.endswith(".pkl"):
        df = pd.read_pickle(path)
    else:
        sep = "\t" if path.endswith(".tsv") else ","
        df = pd.read_csv(path, sep=sep, **kwargs)
    # A Mode column marks a cache of the old two-domain layout, written with
    # the old cosine; it is left out until its notebook rewrites it.
    if isinstance(df, pd.DataFrame) and "Mode" in df.columns:
        print(f"  stale {path} (has a Mode column) - re-run its notebook")
        return None
    return df

In [6]:
ENCODE_DATASETS = DATASET_KEYS["encode"]
SAGACONF_DATASETS = DATASET_KEYS["sagaconf"]

def _scope(segmentation):
    return "replicates" if str(segmentation).endswith(("_rep1", "_rep2")) else "pooled"


def _encode_frames(out, filename, columns, datasets=ENCODE_DATASETS, label="encode"):
    frames = []
    for ds in datasets:
        for rel in (f"matched/{filename}", f"matched/joint/{filename}"):
            path = f"{out}/{ds}/{rel}"
            if not os.path.isdir(os.path.dirname(path)):
                continue
            df = _read(path)
            if df is None:
                continue
            df = df.copy()
            df["Method"] = (df["segmentation"].astype(str)
                            .str.replace(r"_rep\d$", "", regex=True))
            df["Dataset"] = ds
            df["Cell"] = f"{label}:" + df["segmentation"].map(_scope)
            df["Segmentation"] = ds + ":" + df["segmentation"].astype(str)
            frames.append(df[["Dataset", "Segmentation", "Method", "Cell"] + columns])
    if not frames:
        return None
    return (pd.concat(frames, ignore_index=True)
            .drop_duplicates(subset=["Segmentation"]))


N_STATES = 15

INCOMPLETE_COLUMNS = ["Dataset", "Segmentation", "Method", "n_states",
                      "Covered_bp", "Share", "Reason"]


def no_incomplete():
    """The empty unusable-segmentations frame, for a dataset with no gate."""
    return pd.DataFrame(columns=INCOMPLETE_COLUMNS)


def incomplete_segmentations(workdir, datasets=ENCODE_DATASETS, label="encode",
                             min_share=0.5, min_states=N_STATES):
    """The segmentations of `datasets` no comparison should be read off."""
    out = os.path.join(os.path.expanduser(workdir), "out")
    stats = _encode_frames(out, "segment_stats.tsv",
                          ["n_states", "n_segments", "mean_length"],
                          datasets=datasets, label=label)
    if stats is None:
        return no_incomplete()
    stats = stats.assign(Covered_bp=stats["n_segments"] * stats["mean_length"])
    median = stats.groupby("Dataset")["Covered_bp"].transform("median")
    stats["Share"] = stats["Covered_bp"] / median
    truncated = stats["Share"] < min_share
    collapsed = stats["n_states"] < min_states
    bad = stats[truncated | collapsed].copy()
    reasons = []
    for share, n_states in zip(bad["Share"], bad["n_states"]):
        why = []
        if share < min_share:
            why.append(f"covers {share:.2%} of the dataset median")
        if n_states < min_states:
            why.append(f"{int(n_states)} of {min_states} states")
        reasons.append(", ".join(why))
    bad["Reason"] = reasons
    bad["Method"] = bad["Method"].map(canonical)
    return bad[INCOMPLETE_COLUMNS]


def _excluded_pairs(incomplete, announce=True):
    reasons = dict(zip(zip(incomplete["Dataset"], incomplete["Method"]),
                       incomplete["Reason"]))
    pairs = {(ds, method)
             for ds, method in zip(incomplete["Dataset"], incomplete["Method"])
             if method is not None}
    if pairs and announce:
        print("  excluding unusable segmentations: "
              + ", ".join(f"{ds}/{m} ({reasons[(ds, m)]})"
                          for ds, m in sorted(pairs)))
    return pairs


def _excluded_comparisons(pairs):
    # The reference has no caller: utils.caller_key() reads it as ChromHMM.
    return {(ds, key) for ds, method in pairs
            for key in ((method,) if method == REFERENCE else
                        CALLER_KEYS.get(utils.caller_key(method), (method,)))}


def _drop_excluded(df, excluded, method_col="Method", dataset_cols=("Dataset",)):
    """`df` without the rows that name an excluded (dataset, method) pair."""
    if not excluded or df is None or df.empty:
        return df
    methods = df[method_col].map(canonical)
    keep = np.ones(len(df), dtype=bool)
    for col in dataset_cols:
        sides = df[col].astype(str).str.split("/")
        keep &= np.array([not any((side, m) in excluded for side in row)
                          for row, m in zip(sides, methods)])
    return df[keep]


FUNCTIONAL_METRICS = {
    f"{axis}_sensitivity": SENSITIVITY_DISPLAY for axis, _, _, _ in FUNCTIONAL_TARGETS
}
FUNCTIONAL_METRICS.update({
    f"{axis}_precision": PRECISION_DISPLAY for axis, _, _, _ in FUNCTIONAL_TARGETS
})

FUNCTIONAL_LABELS = {
    f"{axis}_sensitivity": f"{label} ({SENSITIVITY_DISPLAY})" for axis, label, _, _ in FUNCTIONAL_TARGETS
}
FUNCTIONAL_LABELS.update({
    f"{axis}_precision": f"{label} ({PRECISION_DISPLAY})" for axis, label, _, _ in FUNCTIONAL_TARGETS
})


def _encode_functional(out, label="encode"):
    """Every segmentation on every functional target, one row per
    annotation."""
    rows = []
    for pattern, scope in ((f"{out}/*/ref/report.tsv", "pooled"),
                           (f"{out}/*/matched/*/report.tsv", "pooled"),
                           (f"{out}/*/rep*/matched/*/report.tsv", "replicates")):
        for path in sorted(glob.glob(pattern)):
            dirpath = os.path.dirname(path)
            ds = os.path.relpath(dirpath, out).split(os.sep)[0]
            leaf = os.path.basename(dirpath)
            method = REFERENCE if leaf == "ref" else canonical(leaf)
            if method is None:
                continue
            found = [(axis, utils.annotation_sensitivity_precision(dirpath, states, prefix))
                     for axis, _, states, prefix in FUNCTIONAL_TARGETS]
            for base_axis, found_rows in found:
                for row in found_rows:
                    rows.append({"Dataset": ds, "Method": method,
                                 "Axis": f"{base_axis}_sensitivity",
                                 "Cell": f"{label}:{scope}",
                                 "Label": row["Label"],
                                 "Value": float(row[SENSITIVITY_DISPLAY])})
                    rows.append({"Dataset": ds, "Method": method,
                                 "Axis": f"{base_axis}_precision",
                                 "Cell": f"{label}:{scope}",
                                 "Label": row["Label"],
                                 "Value": float(row[PRECISION_DISPLAY])})
    return pd.DataFrame(rows) if rows else None


def _with_reference(out, cache):
    """An ENCODE sample-pair cache and the reference's pairs, which
    analysis_encode.ipynb runs through the same sweep into the `_ref` cache
    next to it."""
    models = _read(f"{out}/{cache}")
    refs = _read(f"{out}/{cache.replace('.pkl', '_ref.pkl')}")
    if models is None or refs is None:
        return models
    return pd.concat([models, refs], ignore_index=True)


def collect_encode(workdir):
    out = os.path.join(os.path.expanduser(workdir), "out")
    print(f"ENCODE caches in {out}")
    evidence = []
    incomplete = incomplete_segmentations(workdir)
    excluded = _excluded_pairs(incomplete)

    rep = _read(f"{out}/df_joint_rep.pkl")
    if rep is not None:
        evidence += _metric_rows(
            _drop_excluded(rep, excluded), "replicates", "encode",
            "ENCODE df_joint_rep.pkl", "rep1 vs rep2")

    evidence += _emission_rows("encode", out, ENCODE_DATASETS, excluded,
                               "ENCODE")

    # The individual models off the same cache as the joint ones, not off the
    # pipeline's comparison_table.tsv: the two agree on every metric they
    # share, and only the cache carries the AMI.
    cross_sample = _drop_excluded(_with_reference(out, "df_cross_sample.pkl"), excluded)
    if cross_sample is None:
        _no_cache("ENCODE", "df_cross_sample.pkl (run the cross-sample section "
                            "of analysis_encode.ipynb)")
    else:
        same_assay = cross_sample[
            cross_sample["SameAssay"].fillna(True).astype(bool)]
        joint = same_assay["Method"].map(canonical).map(is_joint)
        indiv_rows = same_assay[~joint]
        if indiv_rows.empty:
            _no_cache("ENCODE", "individual models in df_cross_sample.pkl")
        else:
            evidence += _metric_rows(
                indiv_rows, "cross_sample", "encode",
                "ENCODE df_cross_sample.pkl", "all same-assay pairs")
        joint_rows = same_assay[joint]
        if joint_rows.empty:
            _no_cache("ENCODE", "joint models in df_cross_sample.pkl")
        else:
            evidence += _metric_rows(
                joint_rows, "cross_sample", "encode",
                "ENCODE df_cross_sample.pkl",
                "the metric over the pairs every joint model reached, on rep1 "
                "with the state spaces realigned; scored by the mean rank "
                "among the joint models of each same-assay sample pair",
                balance="ranks")

    cross_assay = _drop_excluded(_with_reference(out, "df_cross_assay.pkl"),
                                 excluded)
    if cross_assay is None:
        _no_cache("ENCODE", "df_cross_assay.pkl (run the cross-assay section "
                            "of analysis_encode.ipynb)")
    else:
        evidence += _metric_rows(
            cross_assay, "cross_assay_agreement", "encode",
            "ENCODE df_cross_assay.pkl",
            "the metric over the pairs every caller reached, on rematched "
            "raw states; scored by the mean rank among the callers of each "
            "ChIP vs Mint-ChIP pair", balance="ranks")

    joint = _read(f"{out}/df_joint_indiv.pkl")
    if joint is not None:
        evidence += _metric_rows(
            _drop_excluded(joint, _excluded_comparisons(excluded)),
            "joint_indiv", "encode", "ENCODE df_joint_indiv.pkl",
            "individual vs joint")

    entropy = _drop_excluded(
        _encode_frames(out, "entropy_summary.tsv", ["total_entropy"]), excluded)
    if entropy is None:
        _no_cache("ENCODE", "entropy_summary.tsv (transition matrix entropy)")
    else:
        for cell, group in entropy.groupby("Cell"):
            evidence += _entropy_stability(
                "encode", "entropy", group, "Method", "total_entropy",
                unit_col="Dataset", cell=cell,
                where=f"ENCODE entropy_summary.tsv ({cell})",
                note=f"CV of the transition matrix entropy of the {cell} "
                     f"segmentations")

    functional = _drop_excluded(_encode_functional(out), excluded)
    if functional is not None:
        for (axis, cell), group in functional.groupby(["Axis", "Cell"]):
            where = f"ENCODE enrichment ({axis}, {cell})"
            values, counts = _aggregate(group, "Method", "Value",
                                        mapper=lambda m: m,
                                        unit_col="Dataset", where=where)
            datasets = ", ".join(sorted(set.intersection(*(
                set(rows["Dataset"]) for _, rows in group.groupby("Method")))))
            evidence += _rows(axis, "encode", values,
                              f"{FUNCTIONAL_METRICS[axis]}, "
                              f"{FUNCTIONAL_LABELS[axis]}, over the {cell} "
                              f"segmentations of {datasets}",
                              cell=cell, n=counts)

    all_segments = _encode_frames(out, "segment_stats.tsv",
                                  ["n_states", "n_segments"])
    if all_segments is not None:
        # Before the gate: this axis measures the collapse the gate excludes for.
        fidelity = all_segments.assign(
            ok=all_segments["n_states"].eq(N_STATES).astype(float))
        for cell, group in fidelity.groupby("Cell"):
            values, counts = _aggregate(
                group, "Method", "ok", unit_col="Dataset",
                where=f"ENCODE segment_stats.tsv fidelity ({cell})")
            evidence += _rows("state_recovery", "encode", values,
                              f"fraction of the {cell} segmentations realizing "
                              f"{N_STATES} states", cell=cell, n=counts)

    segments = _drop_excluded(all_segments, excluded)
    if segments is not None:
        for cell, group in segments.groupby("Cell"):
            evidence += _segments_stability(
                "encode", group, "Method", "n_segments", cell=cell,
                unit_col="Dataset",
                where=f"ENCODE segment_stats.tsv stability ({cell})")
            chip_dss = [ds for ds in ENCODE_DATASETS if not ds.endswith("_mint")]
            mint_dss = [ds for ds in ENCODE_DATASETS if ds.endswith("_mint")]
            keyed = group.assign(Method=group["Method"].map(canonical))
            counts_by = (keyed[keyed["Method"].isin(METHODS)]
                         .groupby(["Method", "Dataset"])["n_segments"].mean())
            callers = [m for m in counts_by.index.get_level_values(0).unique()
                       if not is_joint(m)]
            cross = pd.DataFrame(
                [{"Method": m, "Pair": f"{chip}/{mint}",
                  "CV": _cv([counts_by[(m, chip)], counts_by[(m, mint)]])}
                 for m in callers for chip in chip_dss for mint in mint_dss
                 if (m, chip) in counts_by.index
                 and (m, mint) in counts_by.index],
                columns=["Method", "Pair", "CV"]).dropna(subset=["CV"])
            where = f"ENCODE cross-assay counts stability ({cell})"
            if cross.empty:
                _say_once(f"  {where}: no ChIP x Mint-ChIP dataset pair has a "
                          f"segmentation on both sides in this scope, so the "
                          f"axis is left to the other scope")
            else:
                values, _ = _aggregate(cross, "Method", "CV", unit_col="Pair",
                                       where=where, balance="units")
                scores, counts = _aggregate(
                    cross, "Method", "CV", unit_col="Pair", where=where,
                    balance="ranks", high=False)
                evidence += _rows(
                    "cross_assay_segments_stability", "encode", values,
                    f"CV of the segment number between the two assays, over "
                    f"the ChIP vs Mint-ChIP dataset pairs every caller "
                    f"reached; scored by the mean rank among the callers of "
                    f"each of the {cross['Pair'].nunique()} pairs",
                    cell=cell, n=counts, scores=scores)
    return evidence, incomplete

In [7]:
def collect_sagaconf(workdir):
    out = os.path.join(os.path.expanduser(workdir), "out")
    print(f"SAGAconf caches in {out}")
    evidence = []
    incomplete = incomplete_segmentations(workdir, datasets=SAGACONF_DATASETS,
                                          label="sagaconf")
    excluded = _excluded_pairs(incomplete)

    def rows_of(axis, cache, label, note, drop):
        """The evidence of one SAGAconf cache."""
        df = _read(f"{out}/{cache}")
        if df is None:
            _no_cache("SAGAconf", f"{label} ({cache})")
            return []
        return _metric_rows(_drop_excluded(df, drop), axis, "sagaconf",
                            f"SAGAconf {cache}", note)

    evidence += rows_of("replicates", "df_rep.pkl", "replicate agreement",
                        "rep1 vs rep2", excluded)

    evidence += _emission_rows("sagaconf", out, SAGACONF_DATASETS, excluded,
                               "SAGAconf")

    evidence += rows_of("cross_sample", "df_cross_sample.pkl",
                        "cross-sample agreement", "all cell-line pairs",
                        excluded)

    evidence += rows_of("joint_indiv", "df_ji.pkl",
                        "individual vs joint agreement", "individual vs joint",
                        _excluded_comparisons(excluded))

    entropy = _read(f"{out}/df_entropy.pkl")
    if entropy is None:
        _no_cache("SAGAconf", "df_entropy.pkl (transition matrix entropy)")
    else:
        evidence += _entropy_stability(
            "sagaconf", "entropy", _drop_excluded(entropy, excluded), "Method",
            "total_entropy", unit_col="Dataset", where="SAGAconf df_entropy.pkl",
            note="CV of the transition matrix entropy")

    segments = _read(f"{out}/df_segs.pkl")
    if segments is not None:
        fidelity = segments.assign(
            ok=segments["n_states"].eq(N_STATES).astype(float))
        values, counts = _aggregate(fidelity, "Method", "ok",
                                    unit_col="Dataset",
                                    where="SAGAconf df_segs.pkl fidelity")
        evidence += _rows("state_recovery", "sagaconf", values,
                          f"fraction of the 5 cell lines x 2 replicates realizing "
                          f"{N_STATES} states", n=counts)
        evidence += _segments_stability("sagaconf",
                                        _drop_excluded(segments, excluded),
                                        "Method", "n_segments",
                                        unit_col="Dataset",
                                        where="SAGAconf df_segs.pkl stability")
    return evidence, incomplete


EPI1000_REF_INDIV_LABELS = ("ref 15", "individual", "ref_15")


def _drop_reference_indiv(df, where, col="Method"):
    """`df` without the rows of the published individual 15-state model."""
    if df is None:
        return None
    is_ref = df[col].astype(str).str.strip().str.lower().isin(EPI1000_REF_INDIV_LABELS)
    if is_ref.any():
        _say_once(f"  {where}: {int(is_ref.sum())} published individual "
                  f"15-state rows dropped, they are not the de-novo "
                  f"{CHROMHMM_DEFAULT}")
    return df[~is_ref]


def _reference_joint_only(df, where, col="Method"):
    """The `joint_chromhmm` rows of a cache holding only the reference
    models."""
    if df is None:
        return None
    keep = df[col].map(canonical) == JOINT_CHROMHMM
    if not keep.all():
        _say_once(f"  {where}: {int((~keep).sum())} published individual "
                  f"15-state rows dropped, {int(keep.sum())} joint ones kept "
                  f"as {JOINT_CHROMHMM}")
    return df[keep]


def _cross_sample_epi1000(out):
    by_method = {}
    for path in sorted(glob.glob(f"{out}/pw_cache_*.pkl")):
        cache = pd.read_pickle(path)
        df = cache.get("df") if isinstance(cache, dict) else None
        if df is None or df.empty:
            continue
        if "Mode" in df.columns:
            print(f"  stale {path} (has a Mode column) - re-run its notebook")
            continue
        key = canonical(df["Method"].iloc[0])
        if key is None:
            continue
        previous = by_method.get(key)
        if previous is None or os.path.getmtime(path) > os.path.getmtime(previous[0]):
            by_method[key] = (path, df)
        if previous is not None:
            ignored = min([previous[0], path], key=os.path.getmtime)
            print(f"  1000 epigenomes: {os.path.basename(ignored)} is an older "
                  f"copy of the {key} pairs, ignored")
    frames = [df for _, df in by_method.values()]

    df_15 = _reference_joint_only(_read(f"{out}/df_pw_15.csv"),
                                  "1000 epigenomes df_pw_15.csv")
    if df_15 is not None and not df_15.empty:
        frames.append(df_15)

    if not frames:
        print(f"  missing {out}/pw_cache_*.pkl")
        return None
    return pd.concat(frames, ignore_index=True)


def collect_epi1000(workdir):
    out = os.path.join(os.path.expanduser(workdir), "out")
    print(f"1000-epigenomes caches in {out}")
    evidence = []

    rep = _drop_reference_indiv(_read(f"{out}/df_replicates.csv"),
                                "1000 epigenomes df_replicates.csv")
    if rep is not None:
        rep = rep.assign(Pair=rep["EID1"].astype(str) + "/"
                              + rep["EID2"].astype(str))
        evidence += _metric_rows(rep, "replicates", "epi1000",
                                 "1000 epigenomes df_replicates.csv",
                                 "rep1 vs rep2", unit_col="Pair")

    pairs = _cross_sample_epi1000(out)
    if pairs is not None:
        print("  1000 epigenomes: the cross-sample caches carry no pair "
              "identity, so the sampled pairs behind each method's mean are "
              "not checked to be the same ones")
        evidence += _metric_rows(pairs, "cross_sample", "epi1000",
                                 "1000 epigenomes pw_cache_*.pkl",
                                 "sampled pairs", unit_col=None)

    joint = _read(f"{out}/df_joint_indiv_comparison.csv")
    if joint is not None:
        evidence += _metric_rows(
            joint, "joint_indiv", "epi1000",
            "1000 epigenomes df_joint_indiv_comparison.csv",
            "individual vs joint")

    emissions = _drop_reference_indiv(
        _read(f"{out}/df_replicates_emissions.csv"),
        "1000 epigenomes df_replicates_emissions.csv")
    if emissions is None:
        _no_cache("1000 epigenomes", "df_replicates_emissions.csv (run the "
                                     "replicate emission similarity cell)")
    else:
        col = _find_column(emissions, utils.EMISSION, utils.EMISSION_DISPLAY)
        if col is None:
            _no_cache("1000 epigenomes", f"a {utils.EMISSION} column")
        else:
            emissions = emissions.assign(
                Pair=emissions["EID1"].astype(str) + "/"
                     + emissions["EID2"].astype(str))
            values, counts = _aggregate(
                emissions, "Method", col, unit_col="Pair",
                where="1000 epigenomes df_replicates_emissions.csv")
            evidence += _rows("replicates_emissions", "epi1000", values,
                              f"rep1 vs rep2 cosine of the matched state "
                              f"emission vectors, over {len(emissions)} "
                              f"replicate pairs", n=counts)

    results = _read(f"{out}/df_results.csv")
    entropy_15 = _reference_joint_only(_read(f"{out}/df_entropy_15.csv"),
                                       "1000 epigenomes df_entropy_15.csv")
    segments_15 = _reference_joint_only(_read(f"{out}/df_segments_15.csv"),
                                        "1000 epigenomes df_segments_15.csv")
    if entropy_15 is not None and segments_15 is not None:
        mean_15 = (entropy_15.groupby(["Dataset", "Method"], as_index=False)
                   ["Entropy"].mean())
        res_15 = pd.merge(mean_15, segments_15, on=["Dataset", "Method"])
        res_15["N_States"] = 15
        if results is not None:
            results = pd.concat([results, res_15], ignore_index=True)
        else:
            results = res_15

    if results is not None:
        col = _metric_column(results, "Entropy",
                             "1000 epigenomes df_results.csv")
        if col is not None:
            evidence += _entropy_stability(
                "epi1000", "entropy", results, "Method", col,
                unit_col="Dataset", where="1000 epigenomes df_results.csv entropy",
                note="CV of the transition matrix entropy")

        fidelity = results.assign(
            ok=results["N_States"].eq(N_STATES).astype(float))
        values, counts = _aggregate(
            fidelity, "Method", "ok", unit_col="Dataset",
            where="1000 epigenomes df_results.csv fidelity")
        evidence += _rows("state_recovery", "epi1000", values,
                          f"fraction of the 98 epigenomes realizing "
                          f"{N_STATES} states", n=counts)
        evidence += _segments_stability(
            "epi1000", results, "Method", "N_Segments", unit_col="Dataset",
            where="1000 epigenomes df_results.csv stability")

        short = results[results["N_States"] < N_STATES]
        if not short.empty:
            per_method = (short.groupby(short["Method"].map(canonical))
                          .size().sort_values(ascending=False))
            print(f"  1000 epigenomes: {len(short)} of {len(results)} "
                  f"segmentations realize fewer than {N_STATES} states "
                  f"({', '.join(f'{m} {n}' for m, n in per_method.items())}); "
                  f"they stay in the agreement axes, which have no gate for "
                  f"this dataset - see state_recovery for the size of it")
    return evidence, no_incomplete()


COLLECTORS = {"encode": collect_encode, "sagaconf": collect_sagaconf,
              "epi1000": collect_epi1000}


def build_evidence(workdirs):
    _SAID.clear()
    evidence = []
    incomplete = []
    for dataset, collect in COLLECTORS.items():
        if dataset in workdirs:
            rows, bad = collect(workdirs[dataset])
            evidence += rows
            incomplete.append(bad)

    df = pd.DataFrame(evidence, columns=EVIDENCE_COLUMNS)
    # The individual / joint caches key a pair by its individual model; the
    # axes are scored for the joint one.
    pairs = df["Axis"].astype(str).str.startswith("joint_indiv")
    df.loc[pairs, "Method"] = df.loc[pairs, "Method"].map(JOINT_OF)

    unknown = sorted(set(df["Axis"].astype(str)) - set(ALL_AXIS_CATEGORIES))
    if unknown:
        raise ValueError(
            f"collected evidence for axes no main axis is built from: "
            f"{unknown}. axis_variants() takes the agreement metrics from "
            f"COMPARISON_METRICS, the composition axes are named in AXES - "
            f"register the axis there or stop collecting it.")

    df["Axis"] = pd.Categorical(df["Axis"], categories=ALL_AXIS_CATEGORIES,
                                ordered=True)
    df["Method"] = pd.Categorical(df["Method"], categories=METHODS, ordered=True)

    incomplete = [frame for frame in incomplete
                  if frame is not None and not frame.empty]
    df_incomplete = pd.concat(incomplete, ignore_index=True) if incomplete \
        else no_incomplete()

    return (df.sort_values(["Axis", "Dataset", "Cell", "Method"])
            .reset_index(drop=True), df_incomplete)


SEGMENT_COUNT_MODELS = METHODS

SEGMENT_COUNT_COLUMNS = ["Dataset", "Cell", "Scope", "Segmentation", "Model",
                         "N_Segments", "N_States"]


def _encode_reference_ids():
    """The ref_chromhmm accession of every ENCODE dataset that names one."""
    with open(os.path.join(PROJECT_ROOT, "config_encode.yaml")) as f:
        datasets = yaml.safe_load(f)["datasets"]
    return {ds: info["ref_chromhmm"] for ds, info in datasets.items()
            if info.get("ref_chromhmm")}


def _encode_segment_counts(workdir, excluded):
    """Segment and state counts of every ENCODE segmentation, reference
    included; both scopes, kept apart in Scope."""
    out = os.path.join(os.path.expanduser(workdir), "out")
    stats = _encode_frames(out, "segment_stats.tsv", ["n_states", "n_segments"])
    if stats is None:
        _no_cache("ENCODE", "segment_stats.tsv (segment counts)")
        return None
    stats = _drop_excluded(stats, excluded)
    stats = stats.assign(Model=stats["Method"].map(canonical))
    return (stats.rename(columns={"n_segments": "N_Segments",
                                  "n_states": "N_States"})
            .assign(Scope=stats["Cell"].astype(str).str.rsplit(":", n=1).str[-1]))


def _sagaconf_segment_counts(workdir, excluded):
    """Segment and state counts of the SAGAconf segmentations; it has no
    reference."""
    out = os.path.join(os.path.expanduser(workdir), "out")
    segments = _drop_excluded(_read(f"{out}/df_segs.pkl"), excluded)
    if segments is None:
        return None
    return (segments.assign(Model=segments["Method"].map(canonical),
                            Scope="",
                            Segmentation=segments["Dataset"].astype(str) + ":"
                                         + segments["segmentation"].astype(str))
            .rename(columns={"n_segments": "N_Segments",
                             "n_states": "N_States"}))


def _epi1000_segment_counts(workdir, excluded):
    """Segment and state counts of the 1000-epigenomes models, one row per
    epigenome."""
    out = os.path.join(os.path.expanduser(workdir), "out")
    frames = []
    results = _read(f"{out}/df_results.csv")
    if results is not None:
        frames.append(results.assign(Model=results["Method"].map(canonical)))
    # The published 15-state joint model is the joint ChromHMM of this
    # dataset, not a reference bar of its own.
    published = _read(f"{out}/df_segments_15.csv")
    if published is not None:
        published = published[published["Method"].map(canonical)
                              == JOINT_CHROMHMM]
        frames.append(published.assign(Model=JOINT_CHROMHMM))
    if not frames:
        return None
    counts = pd.concat(frames, ignore_index=True)
    return counts.assign(Scope="",
                         Segmentation=counts["Dataset"].astype(str) + ":"
                                      + counts["Model"].astype(str))


SEGMENT_COUNT_COLLECTORS = {"encode": _encode_segment_counts,
                            "sagaconf": _sagaconf_segment_counts,
                            "epi1000": _epi1000_segment_counts}


def collect_segment_counts(workdirs, incomplete):
    """One row per segmentation of every dataset: its model and its count."""
    excluded = _excluded_pairs(incomplete, announce=False)
    frames = []
    for dataset, collect in SEGMENT_COUNT_COLLECTORS.items():
        if dataset not in workdirs:
            continue
        counts = collect(workdirs[dataset], excluded)
        if counts is None or counts.empty:
            continue
        counts = counts[counts["Model"].isin(SEGMENT_COUNT_MODELS)]
        frames.append(counts.assign(Cell=counts["Dataset"].astype(str), Dataset=dataset)
                      .reindex(columns=SEGMENT_COUNT_COLUMNS))
    if not frames:
        print("  no segment counts collected")
        return pd.DataFrame(columns=SEGMENT_COUNT_COLUMNS)
    counts = pd.concat(frames, ignore_index=True)
    counts["N_Segments"] = counts["N_Segments"].astype(float)
    counts["N_States"] = pd.to_numeric(counts["N_States"], errors="coerce")
    unknown = counts["N_States"].isna()
    if unknown.any():
        models = sorted(set(counts.loc[unknown, "Model"].astype(str)))
        print(f"  no state count for {int(unknown.sum())} segmentations "
              f"({', '.join(models)}) - re-run their notebook to cache it")
    counts["Dataset"] = pd.Categorical(counts["Dataset"], categories=DATASETS,
                                       ordered=True)
    counts["Model"] = pd.Categorical(counts["Model"],
                                     categories=SEGMENT_COUNT_MODELS,
                                     ordered=True)
    return (counts.dropna(subset=["N_Segments"])
            .sort_values(["Dataset", "Model", "Cell"]).reset_index(drop=True))


# The AMI compares the segmentations as partitions, whatever the states are
# called, so it is the one agreement here that does not rest on the state
# matching; it is ranked next to the Kappa through COMPARISON_METRICS.
SUMMARY_METRICS = [COSINE, KAPPA, JACCARD, AMI]

SUMMARY_METRIC_LABELS = {COSINE: COMPOSITION_DISPLAY, KAPPA: KAPPA_DISPLAY,
                         JACCARD: JACCARD_DISPLAY, AMI: AMI_DISPLAY}
SUMMARY_METRIC_ORDER = [SUMMARY_METRIC_LABELS[m] for m in SUMMARY_METRICS]

SUMMARY_COMPARISONS = ["cross_sample", "replicates", "joint_indiv"]

COMPARISON_ROW_COLUMNS = ["Dataset", "Cell", "Comparison", "Metric", "Method",
                          "Value"]


def _summary_categoricals(rows):
    """The dataset, method, metric and comparison columns as ordered
    categoricals."""
    rows = rows.copy()
    rows["Dataset"] = pd.Categorical(rows["Dataset"], categories=DATASETS,
                                     ordered=True)
    rows["Method"] = pd.Categorical(rows["Method"], categories=METHODS,
                                    ordered=True)
    if "Metric" in rows:
        rows["Metric"] = pd.Categorical(rows["Metric"],
                                        categories=SUMMARY_METRIC_ORDER,
                                        ordered=True)
    if "Comparison" in rows:
        rows["Comparison"] = pd.Categorical(rows["Comparison"],
                                            categories=SUMMARY_COMPARISONS,
                                            ordered=True)
    return rows.dropna(subset=["Dataset", "Method"])


def _metric_value_rows(rows, comparison, dataset, where, method_col="Method",
                       unit_col=None):
    """Every metric of `rows` in long form, one row per comparison and
    metric."""
    frames = []
    for metric in SUMMARY_METRICS:
        col = _metric_column(rows, metric, where)
        if col is None:
            continue
        keys = rows[method_col].map(canonical)
        keep = keys.notna() & rows[col].notna()
        if not keep.any():
            continue
        frames.append(pd.DataFrame({
            "Dataset": dataset,
            "Cell": (rows.loc[keep, unit_col].astype(str) if unit_col
                     else str(dataset)),
            "Comparison": comparison,
            "Metric": SUMMARY_METRIC_LABELS[metric],
            "Method": keys[keep].values,
            "Value": rows.loc[keep, col].astype(float).values}))
    return frames


def _encode_comparison_rows(workdir, excluded):
    """The three comparisons of ENCODE, gated as collect_encode() gates
    them."""
    out = os.path.join(os.path.expanduser(workdir), "out")
    frames = []

    rep = _drop_excluded(_read(f"{out}/df_joint_rep.pkl"), excluded)
    if rep is not None:
        frames += _metric_value_rows(rep, "replicates", "encode",
                                     "ENCODE df_joint_rep.pkl",
                                     unit_col="Dataset")

    # Individual and joint models alike off df_cross_sample.pkl, which -
    # unlike the pipeline's comparison_table.tsv - carries the AMI, and the
    # reference off df_cross_sample_ref.pkl.
    cross_sample = _drop_excluded(_with_reference(out, "df_cross_sample.pkl"), excluded)
    if cross_sample is not None:
        same_assay = cross_sample[
            cross_sample["SameAssay"].fillna(True).astype(bool)]
        frames += _metric_value_rows(same_assay, "cross_sample", "encode",
                                     "ENCODE df_cross_sample.pkl",
                                     unit_col="Dataset")

    joint = _drop_excluded(_read(f"{out}/df_joint_indiv.pkl"),
                           _excluded_comparisons(excluded))
    if joint is not None:
        frames += _metric_value_rows(joint, "joint_indiv", "encode",
                                     "ENCODE df_joint_indiv.pkl",
                                     unit_col="Dataset")
    return frames


SAGACONF_COMPARISON_CACHES = {"replicates": "df_rep.pkl",
                              "cross_sample": "df_cross_sample.pkl",
                              "joint_indiv": "df_ji.pkl"}


def _sagaconf_comparison_rows(workdir, excluded):
    out = os.path.join(os.path.expanduser(workdir), "out")
    frames = []
    for comparison, cache in SAGACONF_COMPARISON_CACHES.items():
        drop = (_excluded_comparisons(excluded) if comparison == "joint_indiv"
                else excluded)
        rows = _drop_excluded(_read(f"{out}/{cache}"), drop)
        if rows is None:
            continue
        frames += _metric_value_rows(rows, comparison, "sagaconf",
                                     f"SAGAconf {cache}", unit_col="Dataset")
    return frames


def _epi1000_comparison_rows(workdir, excluded):
    """The three comparisons of the 1000 epigenomes; no gate, as in
    collect_epi1000()."""
    out = os.path.join(os.path.expanduser(workdir), "out")
    frames = []

    rep = _drop_reference_indiv(_read(f"{out}/df_replicates.csv"),
                                "1000 epigenomes df_replicates.csv")
    if rep is not None:
        rep = rep.assign(Pair=rep["EID1"].astype(str) + "/"
                              + rep["EID2"].astype(str))
        frames += _metric_value_rows(rep, "replicates", "epi1000",
                                     "1000 epigenomes df_replicates.csv",
                                     unit_col="Pair")

    pairs = _cross_sample_epi1000(out)
    if pairs is not None:
        frames += _metric_value_rows(pairs, "cross_sample", "epi1000",
                                     "1000 epigenomes pw_cache_*.pkl")

    joint = _read(f"{out}/df_joint_indiv_comparison.csv")
    if joint is not None:
        frames += _metric_value_rows(
            joint, "joint_indiv", "epi1000",
            "1000 epigenomes df_joint_indiv_comparison.csv",
            unit_col="Dataset")
    return frames


COMPARISON_COLLECTORS = {"encode": _encode_comparison_rows,
                         "sagaconf": _sagaconf_comparison_rows,
                         "epi1000": _epi1000_comparison_rows}


def collect_comparisons(workdirs, incomplete):
    """Every comparison and metric, one row per measured comparison."""
    excluded = _excluded_pairs(incomplete, announce=False)
    frames = []
    for dataset, collect in COMPARISON_COLLECTORS.items():
        if dataset in workdirs:
            frames += collect(workdirs[dataset], excluded)
    if not frames:
        print("  no comparison metrics collected")
        return pd.DataFrame(columns=COMPARISON_ROW_COLUMNS)
    rows = pd.concat(frames, ignore_index=True)[COMPARISON_ROW_COLUMNS]
    return _summary_categoricals(rows).sort_values(
        ["Comparison", "Metric", "Dataset", "Method"]
    ).reset_index(drop=True)


ENTROPY_ROW_COLUMNS = ["Dataset", "Cell", "Method", "Value"]


def _entropy_rows(rows, dataset, method_col, value_col, unit_col):
    keys = rows[method_col].map(canonical)
    keep = keys.notna() & rows[value_col].notna()
    if not keep.any():
        return []
    return [pd.DataFrame({"Dataset": dataset,
                          "Cell": rows.loc[keep, unit_col].astype(str),
                          "Method": keys[keep].values,
                          "Value": rows.loc[keep, value_col].astype(float).values})]


def collect_entropy(workdirs, incomplete):
    """The transition matrix entropy of every segmentation."""
    excluded = _excluded_pairs(incomplete, announce=False)
    frames = []

    if "encode" in workdirs:
        out = os.path.join(os.path.expanduser(workdirs["encode"]), "out")
        entropy = _drop_excluded(
            _encode_frames(out, "entropy_summary.tsv", ["total_entropy"]),
            excluded)
        if entropy is None:
            _no_cache("ENCODE", "entropy_summary.tsv")
        else:
            frames += _entropy_rows(entropy, "encode", "Method",
                                    "total_entropy", "Segmentation")

    if "sagaconf" in workdirs:
        out = os.path.join(os.path.expanduser(workdirs["sagaconf"]), "out")
        entropy = _drop_excluded(_read(f"{out}/df_entropy.pkl"), excluded)
        if entropy is not None:
            frames += _entropy_rows(entropy, "sagaconf", "Method",
                                    "total_entropy", "Dataset")

    if "epi1000" in workdirs:
        out = os.path.join(os.path.expanduser(workdirs["epi1000"]), "out")
        results = _read(f"{out}/df_results.csv")
        if results is not None:
            col = _metric_column(results, "Entropy",
                                 "1000 epigenomes df_results.csv")
            if col is not None:
                frames += _entropy_rows(results, "epi1000", "Method", col,
                                        "Dataset")
        entropy_15 = _reference_joint_only(_read(f"{out}/df_entropy_15.csv"),
                                           "1000 epigenomes df_entropy_15.csv")
        if entropy_15 is not None:
            frames += _entropy_rows(entropy_15, "epi1000", "Method", "Entropy",
                                    "Dataset")

    if not frames:
        print("  no entropy collected")
        return pd.DataFrame(columns=ENTROPY_ROW_COLUMNS)
    rows = pd.concat(frames, ignore_index=True)[ENTROPY_ROW_COLUMNS]
    return _summary_categoricals(rows).sort_values(
        ["Dataset", "Method"]).reset_index(drop=True)


PEAK_MODELS = [CHROMHMM_DEFAULT, KMEANS_HOMER, BMM3_HOMER, KMEANS_MACS2, BMM3_MACS2,
               KMEANS_OMNI, BMM3_OMNI]

PEAK_MARKS = ["H3K4me3", "H3K4me1", "H3K27ac", "H3K27me3", "H3K36me3",
              "H3K9me3"]

PEAK_ROW_COLUMNS = ["Dataset", "Cell", "Mark", "Method", "N_Peaks",
                    "Mean_Length"]


def _peak_method(name):
    """Canonical model key of a peak-table method; 'Default' is the ChromHMM
    binarization."""
    if str(name).strip().lower() == "default":
        return CHROMHMM_DEFAULT
    return canonical(name)


def _peak_frame(df, dataset, dataset_col):
    return pd.DataFrame({"Dataset": dataset,
                         "Cell": df[dataset_col].astype(str),
                         "Mark": df["mark"].astype(str),
                         "Method": df["method"].map(_peak_method),
                         "N_Peaks": df["n_peaks"].astype(float),
                         "Mean_Length": df["mean_length"].astype(float)})


def _encode_peak_stats(workdir):
    """The peak table of every ENCODE dataset, which sits next to the
    segmentations."""
    root = os.path.expanduser(workdir)
    frames = []
    for ds in ENCODE_DATASETS:
        path = os.path.join(root, ds, "peaks", "peak_stats.tsv")
        if not os.path.exists(path):
            continue
        frames.append(_peak_frame(_read(path).assign(Dataset=ds), "encode",
                                  "Dataset"))
    if not frames:
        _no_cache("ENCODE", "peaks/peak_stats.tsv")
        return []
    return frames


def _drop_unanalyzed_samples(rows):
    """`rows` without the samples whose peak table is zero everywhere - a run
    that never happened, unlike a single empty call, which stays."""
    totals = rows.groupby(["Dataset", "Cell"])["N_Peaks"].sum()
    empty = set(totals[totals <= 0].index)
    if empty:
        print("  no peaks at all for "
              + ", ".join(f"{DATASET_NAMES[ds]}/{cell}"
                          for ds, cell in sorted(empty))
              + " - the peak analysis of those samples did not run, so they "
                "are left out of the peak figures")
        rows = rows[[(ds, cell) not in empty
                     for ds, cell in zip(rows["Dataset"], rows["Cell"])]]
    return rows


def collect_peak_stats(workdirs):
    """Peak count and mean peak length of every (sample, mark), over
    PEAK_MARKS."""
    frames = []
    if "encode" in workdirs:
        frames += _encode_peak_stats(workdirs["encode"])
    if "sagaconf" in workdirs:
        out = os.path.join(os.path.expanduser(workdirs["sagaconf"]), "out")
        peaks = _read(f"{out}/df_peaks.pkl")
        if peaks is not None:
            frames.append(_peak_frame(peaks, "sagaconf", "Dataset"))
    if "epi1000" in workdirs:
        out = os.path.join(os.path.expanduser(workdirs["epi1000"]), "out")
        peaks = _read(f"{out}/df_peaks.csv")
        if peaks is not None:
            frames.append(_peak_frame(peaks, "epi1000", "dataset"))
    if not frames:
        print("  no peak statistics collected")
        return pd.DataFrame(columns=PEAK_ROW_COLUMNS)
    rows = pd.concat(frames, ignore_index=True)
    rows = rows[rows["Mark"].isin(PEAK_MARKS) & rows["Method"].isin(PEAK_MODELS)]
    rows = _drop_unanalyzed_samples(rows)
    rows["Mark"] = pd.Categorical(rows["Mark"], categories=PEAK_MARKS,
                                  ordered=True)
    return _summary_categoricals(rows[PEAK_ROW_COLUMNS]).sort_values(
        ["Dataset", "Method", "Cell", "Mark"]).reset_index(drop=True)


# The quiescent state is the "nothing here" label - no mark reaches it, and in
# most samples it is the majority of the genome. What is left of the genome
# once it is taken out is what a segmentation actually annotates, so its share
# is read here for every segmentation of every dataset, next to the segment
# counts above.
#
# The share is of the genome the segmentation covers, which is what the cached
# compositions are normalized by; ENCODE also carries the covered length, and
# there every complete segmentation covers the same 3.09 Gb, so the two
# denominators are one. A state matching left unlabelled ("Unknown", under 2%
# of the ENCODE Mint-ChIP segmentations and absent everywhere else) is counted
# as annotated - it is not the quiescent state, only an unmatched one.
ANNOTATED_COLUMNS = ["Dataset", "Cell", "Scope", "Segmentation", "Model",
                     "Covered_bp", "Quiescent", "Annotated"]


def _annotated_row(dataset, scope, segmentation, model, states, weights,
                   covered=np.nan):
    """One row off the per-state weights of a segmentation, bp or fractions."""
    weights = np.asarray(weights, dtype=float)
    total = weights.sum()
    if not np.isfinite(total) or total <= 0:
        return None
    quiescent = weights[[utils.is_quiescent(s) for s in states]].sum() / total
    return {"Dataset": dataset, "Scope": scope, "Segmentation": segmentation,
            "Model": model, "Covered_bp": covered,
            "Quiescent": quiescent, "Annotated": 1.0 - quiescent}


def _encode_annotated_share(workdir, excluded):
    """Quiescent and annotated share of every ENCODE segmentation, reference
    included, off the per-state bp of its report.tsv; both scopes, kept apart
    in Scope."""
    out = os.path.join(os.path.expanduser(workdir), "out")
    references = _encode_reference_ids()
    rows = []
    for pattern, scope in ((f"{out}/*/ref/report.tsv", "pooled"),
                           (f"{out}/*/matched/*/report.tsv", "pooled"),
                           (f"{out}/*/rep*/matched/*/report.tsv", "replicates")):
        for path in sorted(glob.glob(pattern)):
            dirpath = os.path.dirname(path)
            parts = os.path.relpath(dirpath, out).split(os.sep)
            ds, leaf = parts[0], parts[-1]
            if ds not in ENCODE_DATASETS:
                continue
            if leaf == "ref":
                model, name = REFERENCE, f"{references.get(ds)}_chromhmm"
            else:
                model = canonical(leaf)
                name = leaf + (f"_{parts[1]}" if scope == "replicates" else "")
            if model is None:
                continue
            report = _read(path)
            if report is None:
                continue
            row = _annotated_row(ds, scope, f"{ds}:{name}", model,
                                 report["state"], report["total_bp"],
                                 covered=float(report["total_bp"].sum()))
            if row is not None:
                rows.append(row)
    if not rows:
        _no_cache("ENCODE", "report.tsv per-state coverage")
        return None
    return _drop_excluded(pd.DataFrame(rows), excluded, method_col="Model")


def _sagaconf_annotated_share(workdir, excluded):
    """The same for SAGAconf, off the interpreted state types: its states are
    matched per dataset and numbered, so which of them is the quiescent one is
    a question about the emissions, not about the name."""
    out = os.path.join(os.path.expanduser(workdir), "out")
    interp = _read(f"{out}/df_interp_matched.pkl")
    if interp is None:
        _no_cache("SAGAconf", "df_interp_matched.pkl (interpreted state types)")
        return None
    rows = []
    for (ds, method, rep), group in interp.groupby(["Dataset", "Method", "Rep"]):
        model = canonical(method)
        if model is None:
            continue
        row = _annotated_row(ds, "", f"{ds}:{model}_{rep}", model,
                             group["Type"], group["Fraction"])
        if row is not None:
            rows.append(row)
    if not rows:
        return None
    return _drop_excluded(pd.DataFrame(rows), excluded, method_col="Model")


def _epi1000_annotated_share(workdir, excluded):
    """The same for the 1000 epigenomes, one row per epigenome and model. The
    published 15-state joint model is the joint ChromHMM of this dataset and
    is cached apart from the de-novo compositions."""
    out = os.path.join(os.path.expanduser(workdir), "out")
    rows = []
    comp = _read(f"{out}/df_comp.csv")
    if comp is not None:
        for (ds, method), group in comp.groupby(["Dataset", "Method"]):
            model = canonical(method)
            if model is None:
                continue
            row = _annotated_row(ds, "", f"{ds}:{model}", model,
                                 group["State"], group["Fraction"])
            if row is not None:
                rows.append(row)
    published = _read(f"{out}/stats_15_cache.pkl")
    if published is not None:
        for (ds, method), stats in published.items():
            if canonical(method) != JOINT_CHROMHMM:
                continue
            states = pd.DataFrame(stats["composition"])
            row = _annotated_row(ds, "", f"{ds}:{JOINT_CHROMHMM}",
                                 JOINT_CHROMHMM, states["State"],
                                 states["Fraction"])
            if row is not None:
                rows.append(row)
    if not rows:
        _no_cache("1000 epigenomes", "df_comp.csv (state composition)")
        return None
    return _drop_excluded(pd.DataFrame(rows), excluded, method_col="Model")


ANNOTATED_COLLECTORS = {"encode": _encode_annotated_share,
                        "sagaconf": _sagaconf_annotated_share,
                        "epi1000": _epi1000_annotated_share}


def collect_annotated_share(workdirs, incomplete):
    """One row per segmentation of every dataset: how much of the genome it
    puts on a state other than the quiescent one."""
    excluded = _excluded_pairs(incomplete, announce=False)
    frames = []
    for dataset, collect in ANNOTATED_COLLECTORS.items():
        if dataset not in workdirs:
            continue
        shares = collect(workdirs[dataset], excluded)
        if shares is None or shares.empty:
            continue
        shares = shares[shares["Model"].isin(SEGMENT_COUNT_MODELS)]
        frames.append(shares.assign(Cell=shares["Dataset"].astype(str),
                                    Dataset=dataset)
                      .reindex(columns=ANNOTATED_COLUMNS))
    if not frames:
        print("  no state coverage collected")
        return pd.DataFrame(columns=ANNOTATED_COLUMNS)
    shares = pd.concat(frames, ignore_index=True)
    shares["Dataset"] = pd.Categorical(shares["Dataset"], categories=DATASETS,
                                       ordered=True)
    shares["Model"] = pd.Categorical(shares["Model"],
                                     categories=SEGMENT_COUNT_MODELS,
                                     ordered=True)
    return (shares.dropna(subset=["Annotated"])
            .sort_values(["Dataset", "Model", "Cell"]).reset_index(drop=True))

In [8]:
# Per-state replicate agreement: rep1 vs rep2 of every model, one value per
# state of the pair. No cache upstream holds it for all three datasets -
# ENCODE has per_state_metrics.tsv, SAGAconf df_rep_per_type.pkl, the 1000
# epigenomes keep none - so it is measured here off the replicate
# segmentations and cached.
from collections import defaultdict

for _p in (os.path.join(PROJECT_ROOT, "scripts", "rules"),
           os.path.join(PROJECT_ROOT, "scripts")):
    if _p not in sys.path:
        sys.path.append(_p)
import interpretation
import match
import summary_plots

REP_STATE_METRICS = [JACCARD, KAPPA]

REP_STATE_COLUMNS = ["Dataset", "Cell", "Method", "Metric", "State", "Value"]


def _rep_bed(root, ds, cell, method, rep, joint_suffix):
    """The replicate segmentation of one ENCODE / SAGAconf model, the layout
    of inter_ds_bed() in analysis_encode.ipynb and get_method_path() in
    analysis_sagaconf.ipynb; SAGAconf leaves its joint models unmatched."""
    if method == CHROMHMM_DEFAULT:
        return f"{root}/{ds}/{rep}/{CHROMHMM_DEFAULT}_result/{cell}_{N_STATES}_dense_matched.bed"
    if method == JOINT_CHROMHMM:
        return f"{root}/{ds}/{JOINT_CHROMHMM}/{rep}_{N_STATES}_dense{joint_suffix}.bed"
    model = "kmeans" if "kmeans" in method else "bmm3"
    caller = method.replace("joint_", "").replace(f"{model}_", "")
    if is_joint(method):
        return f"{root}/{ds}/joint_{model}/{caller}/{rep}_{model}_joint_states{joint_suffix}.bed"
    return f"{root}/{ds}/{rep}/{caller}/{caller}_{model}_states_matched.bed"


def _rep_datasets(config_file, dataset):
    """(dataset, cell) of every non-outlier dataset of a config with
    replicates."""
    with open(os.path.join(PROJECT_ROOT, config_file)) as f:
        datasets = yaml.safe_load(f)["datasets"]
    return [(ds, datasets[ds]["cell"]) for ds in DATASET_KEYS[dataset]
            if datasets[ds].get("replicates", True)]


def _sagaconf_types(root):
    """(dataset, method, rep) -> {state: interpreted type} of every
    interpreted SAGAconf segmentation."""
    interp = _read(f"{root}/out/df_interp_matched.pkl")
    if interp is None:
        return {}
    types = defaultdict(dict)
    for ds, method, rep, state, kind in interp[
            ["Dataset", "Method", "Rep", "State", "Type"]].itertuples(index=False):
        types[(ds, canonical(method), rep)][str(state)] = kind
    return types


# The 1000-epigenome segmentation of every model, relative to the epigenome
# folder: METHOD_PATTERNS of analysis_epi1000.ipynb. Its joint ChromHMM is the
# published joint 15-state model, as everywhere else in this notebook.
EPI1000_REP_BEDS = {
    CHROMHMM_DEFAULT:   "{f}/{f}_chromhmm/{f}_15_dense_matched.bed",
    KMEANS_HOMER:       "{f}/homer/{f}_homer_kmeans_states_matched.bed",
    KMEANS_MACS2:       "{f}/macs2/{f}_macs2_kmeans_states_matched.bed",
    KMEANS_OMNI:        "{f}/omni/{f}_omni_kmeans_states_matched.bed",
    BMM3_HOMER:         "{f}/homer/{f}_homer_bmm3_states_matched.bed",
    BMM3_MACS2:         "{f}/macs2/{f}_macs2_bmm3_states_matched.bed",
    BMM3_OMNI:          "{f}/omni/{f}_omni_bmm3_states_matched.bed",
    JOINT_KMEANS_HOMER: "joint_kmeans/homer/{f}_kmeans_joint_states_matched.bed",
    JOINT_KMEANS_MACS2: "joint_kmeans/macs2/{f}_kmeans_joint_states_matched.bed",
    JOINT_KMEANS_OMNI:  "joint_kmeans/omni/{f}_kmeans_joint_states_matched.bed",
    JOINT_BMM3_HOMER:   "joint_bmm3/homer/{f}_bmm3_joint_states_matched.bed",
    JOINT_BMM3_MACS2:   "joint_bmm3/macs2/{f}_bmm3_joint_states_matched.bed",
    JOINT_BMM3_OMNI:    "joint_bmm3/omni/{f}_bmm3_joint_states_matched.bed",
    JOINT_CHROMHMM:     "{f}_15_coreMarks_dense_joint_re*dered.bed.gz",
}


def _epi1000_bed(root, eid, method):
    found = sorted(glob.glob(f"{root}/{EPI1000_REP_BEDS[method].format(f=eid)}"))
    return found[0] if found else None


def replicate_state_tasks(workdirs):
    """(dataset, cell, method, path1, path2, types1, types2) of every
    replicate pair on disk; the types map SAGAconf states onto their
    interpreted type and are None elsewhere."""
    tasks = []
    for dataset, config_file, joint_suffix in [
            ("encode", "config_encode.yaml", "_matched"),
            ("sagaconf", "config_sagaconf.yaml", "")]:
        if dataset not in workdirs:
            continue
        root = os.path.expanduser(workdirs[dataset])
        types = _sagaconf_types(root) if dataset == "sagaconf" else None
        for ds, cell in _rep_datasets(config_file, dataset):
            for method in METHODS:
                paths = [_rep_bed(root, ds, cell, method, rep, joint_suffix)
                         for rep in ("rep1", "rep2")]
                if not all(os.path.exists(p) for p in paths):
                    continue
                if types is None:
                    tasks.append((dataset, ds, method, *paths, None, None))
                    continue
                # SAGAconf states are matched per dataset, so state "13" means
                # something else in every cell line: they are compared as the
                # interpreted types every segmentation shares.
                sides = [types.get((ds, method, rep)) for rep in ("rep1", "rep2")]
                if all(sides):
                    tasks.append((dataset, ds, method, *paths, *sides))
                else:
                    _say_once(f"  SAGAconf {ds} {method}: no interpreted types, "
                              f"left out of the per-state agreement")

    if "epi1000" in workdirs:
        root = os.path.expanduser(workdirs["epi1000"])
        pairs = _drop_reference_indiv(_read(f"{root}/out/df_replicates.csv"),
                                      "1000 epigenomes df_replicates.csv")
        if pairs is not None:
            pairs = pairs.assign(Method=pairs["Method"].map(canonical))
            for method, eid1, eid2 in (pairs[["Method", "EID1", "EID2"]]
                                       .drop_duplicates()
                                       .itertuples(index=False)):
                if method not in EPI1000_REP_BEDS:
                    continue
                paths = [_epi1000_bed(root, eid, method) for eid in (eid1, eid2)]
                if all(paths):
                    tasks.append(("epi1000", f"{eid1}/{eid2}", method, *paths,
                                  None, None))
    return tasks


def _replicate_states(task):
    """The per-state rows of one replicate pair, every metric."""
    dataset, cell, method, path1, path2, types1, types2 = task
    names = [(lambda s, t=types: t.get(str(s), utils.QUIESCENT)) if types
             else utils.normalize_state_name for types in (types1, types2)]
    segs1, segs2 = match.load_bed(path1), match.load_bed(path2)
    # pair_overlap() puts its work state first: keys come out (state1, state2).
    overlap = defaultdict(int)
    for (s1, s2), bp in match.pair_overlap(segs2, segs1).items():
        overlap[(names[0](s1), names[1](s2))] += bp
    states = sorted({s for pair in overlap for s in pair})
    rows = []
    for metric in REP_STATE_METRICS:
        for state, value in match.per_state_diagonal(overlap, states,
                                                     metric).items():
            rows.append((dataset, cell, method, SUMMARY_METRIC_LABELS[metric],
                         state, float(value)))
    return rows


def compute_replicate_states(tasks):
    import multiprocessing as mp
    from concurrent.futures import ProcessPoolExecutor
    # Half the cores: a worker holds two whole segmentations.
    with ProcessPoolExecutor(max_workers=max(1, os.cpu_count() // 2),
                             mp_context=mp.get_context("fork")) as executor:
        rows = [row for pair in executor.map(_replicate_states, tasks)
                for row in pair]
    return pd.DataFrame(rows, columns=REP_STATE_COLUMNS)


def collect_replicate_states(workdirs, incomplete):
    """Per-state rep1-vs-rep2 Jaccard and Kappa of every model, gated as the
    replicate axes are."""
    tasks = replicate_state_tasks(workdirs)
    pairs = {(t[0], t[1], t[2]) for t in tasks}
    print(f"  per-state replicate agreement: {len(tasks)} replicate pairs - "
          + ", ".join(f"{DATASET_NAMES[d]} {sum(t[0] == d for t in tasks)}"
                      for d in DATASETS))
    states = utils.cached_pickle(
        f"{OUT}/rep_per_state.pkl", lambda: compute_replicate_states(tasks),
        label="per-state replicate agreement",
        valid=lambda df: (list(df.columns) == REP_STATE_COLUMNS
                          and set(zip(df["Dataset"], df["Cell"], df["Method"]))
                          == pairs))
    gated = _drop_excluded(states.rename(columns={"Dataset": "Collection",
                                                  "Cell": "Dataset"}),
                           _excluded_pairs(incomplete, announce=False))
    gated = gated.rename(columns={"Dataset": "Cell", "Collection": "Dataset"})
    return _summary_categoricals(gated).sort_values(
        ["Metric", "Dataset", "Method"]).reset_index(drop=True)


# The functional family of every state name and interpreted type, the one
# vocabulary the three datasets share: ENCODE, the 1000 epigenomes and SAGAconf
# name their states three different ways.
STATE_FAMILIES = {
    "Promoter": ("Tss", "TssA", "TssAFlnk", "TssFlnk", "TssFlnkU", "TssFlnkD",
                 "Promoter", "PromoterFlanking"),
    "Enhancer": ("Enh", "Enh1", "Enh2", "EnhG", "EnhG1", "EnhG2", "EnhLo",
                 "Enhancer", "EnhancerLow"),
    "Transcribed": ("Tx", "TxWk", "TxFlnk", "Transcribed"),
    "Bivalent": ("Biv", "TssBiv", "BivFlnk", "EnhBiv", "Bivalent"),
    "Polycomb": ("ReprPC", "ReprPCWk", utils.FACULTATIVE_HET),
    "Heterochromatin": ("Het", "ZNF/Rpts", utils.CONSTITUTIVE_HET, "K9K36"),
    "Quiescent": ("Quies", utils.QUIESCENT),
}
FAMILY_OF = {state: family for family, states in STATE_FAMILIES.items()
             for state in states}

FAMILY_COLUMNS = ["Dataset", "Method", "Metric", "Family", "Value", "N"]


def replicate_state_families(states):
    """Per-state replicate agreement folded into state families: the mean over
    the states of a family within a replicate pair, then over the pairs of a
    dataset. One row per dataset, model, metric and family."""
    if states.empty:
        return pd.DataFrame(columns=FAMILY_COLUMNS)
    rows = states.assign(Family=states["State"].map(FAMILY_OF))
    unknown = sorted(set(rows.loc[rows["Family"].isna(), "State"]))
    if unknown:
        print(f"  per-state families: no family for {unknown}, left out")
    rows = rows.dropna(subset=["Family"])
    keys = ["Dataset", "Method", "Metric", "Family"]
    pairs = (rows.groupby(keys + ["Cell"], observed=True)["Value"].mean()
             .reset_index())
    return (pairs.groupby(keys, observed=True)["Value"]
            .agg(Value="mean", N="size").reset_index()[FAMILY_COLUMNS])


def family_table(families, metric):
    """Model x family table of one metric, every dataset weighted equally: the
    mean of the dataset means a model reached. The individual models come
    first, the joint ones after them."""
    rows = families[families["Metric"] == metric]
    table = rows.pivot_table(index="Method", columns="Family", values="Value",
                             aggfunc="mean", observed=True)
    return table.reindex(index=[m for m in INDIVIDUAL_METHODS + JOINT_METHODS
                                if m in table.index],
                         columns=[f for f in STATE_FAMILIES
                                  if f in table.columns])

In [9]:
# Binarization mark combinations: how many of the C(M, N) combinations of N of
# a sample's M marks occur in at least one bin of a caller's binarization. It
# is a property of the binarization, not of a model, so it is read per caller.
# ENCODE and SAGAconf draw it in their notebooks without caching it, so it is
# measured here off the binary files and cached; the 1000 epigenomes cache
# theirs in out/df_mark_comb.csv. SAGAconf has 11 marks (13 for MCF-7) against
# the 6 of the other two, so counts are compared as the share of the possible
# combinations.
from math import comb

import analyze_peaks

MARK_COMBINATION_COLUMNS = ["Dataset", "Cell", "Caller", "N", "Marks",
                            "Combinations", "Share"]

RAW_COMBINATION_COLUMNS = ["collection", "dataset", "method", "N",
                           "combinations"]


def _mark_combinations(task):
    collection, ds, cell, root = task
    return analyze_peaks.binarization_mark_combinations(
        ds, cell, workdir=root).assign(collection=collection)


def compute_mark_combinations(tasks):
    import multiprocessing as mp
    from concurrent.futures import ProcessPoolExecutor
    with ProcessPoolExecutor(max_workers=max(1, os.cpu_count() // 2),
                             mp_context=mp.get_context("fork")) as executor:
        frames = [f for f in executor.map(_mark_combinations, tasks)
                  if not f.empty]
    if not frames:
        return pd.DataFrame(columns=RAW_COMBINATION_COLUMNS)
    return pd.concat(frames, ignore_index=True)[RAW_COMBINATION_COLUMNS]


def collect_mark_combinations(workdirs):
    """Unique mark combinations per number of marks N of every (sample,
    caller) binarization, with the share of the C(M, N) possible ones."""
    tasks = [(dataset, ds, DATASET_CELLS[dataset][ds],
              os.path.expanduser(workdirs[dataset]))
             for dataset in ("encode", "sagaconf") if dataset in workdirs
             for ds in DATASET_KEYS[dataset]]
    wanted = {(t[0], t[1]) for t in tasks}
    frames = [utils.cached_pickle(
        f"{OUT}/mark_combinations.pkl",
        lambda: compute_mark_combinations(tasks),
        label="binarization mark combinations",
        valid=lambda df: set(zip(df["collection"], df["dataset"])) == wanted)]
    if "epi1000" in workdirs:
        out = os.path.join(os.path.expanduser(workdirs["epi1000"]), "out")
        epi = _read(f"{out}/df_mark_comb.csv")
        if epi is None:
            _no_cache("1000 epigenomes", "out/df_mark_comb.csv")
        else:
            frames.append(epi.assign(collection="epi1000"))
    rows = pd.concat(frames, ignore_index=True).rename(columns={
        "collection": "Dataset", "dataset": "Cell", "method": "Caller",
        "combinations": "Combinations"})
    if rows.empty:
        print("  no binarization mark combinations collected")
        return pd.DataFrame(columns=MARK_COMBINATION_COLUMNS)
    rows["Cell"] = rows["Cell"].astype(str)
    # A binarization lists N = 1..M, so its largest N is its mark count.
    binarization = rows.groupby(["Dataset", "Cell", "Caller"])
    rows["Marks"] = binarization["N"].transform("max")
    rows["Share"] = rows["Combinations"] / [comb(m, n) for m, n
                                            in zip(rows["Marks"], rows["N"])]
    empty = binarization["Combinations"].transform("sum") <= 0
    if empty.any():
        print("  no mark in any bin for "
              + ", ".join(f"{DATASET_NAMES[ds]}/{cell} {caller}"
                          for ds, cell, caller in sorted(set(zip(
                              rows.loc[empty, "Dataset"],
                              rows.loc[empty, "Cell"],
                              rows.loc[empty, "Caller"]))))
              + " - a binarization that never ran, left out")
        rows = rows[~empty]
    rows["Dataset"] = pd.Categorical(rows["Dataset"], categories=DATASETS,
                                     ordered=True)
    rows["Caller"] = pd.Categorical(rows["Caller"],
                                    categories=analyze_peaks.METHOD_ORDER,
                                    ordered=True)
    return (rows[MARK_COMBINATION_COLUMNS]
            .sort_values(["Dataset", "Caller", "Cell", "N"])
            .reset_index(drop=True))


def combination_usage(combinations):
    """The share of all 2^M - 1 non-empty mark combinations every (sample,
    caller) binarization reaches."""
    used = (combinations.groupby(["Dataset", "Cell", "Caller", "Marks"],
                                 observed=True)["Combinations"].sum()
            .reset_index())
    used["Share"] = used["Combinations"] / (2.0 ** used["Marks"] - 1)
    return used

## Scoring

In [10]:
def score_evidence(df):
    """The rank score of every evidence row within its family and (axis,
    cell) group. Rows scored inside their sample pairs already carry their
    score and keep it."""
    out = df.copy()
    families = out["Method"].astype(str).map(is_joint)
    for (axis, cell, _), group in out.groupby(["Axis", "Cell", families],
                                              observed=True):
        if group["score"].notna().any():
            continue
        scores = rank_scores(group["Value"].values,
                             high=AXES[str(axis)][1] == "high")
        if scores is not None:
            out.loc[group.index, "score"] = scores.values
    return out


def _axis_table(scored, aggfunc, fold, blank, column="score"):
    """The Method x AXIS_ORDER table of `aggfunc` over `column`."""
    table = scored.pivot_table(index="Method", columns="Axis", values=column,
                               aggfunc=aggfunc, observed=True)
    for main in VARIANT_MAIN_AXES:
        avail = [v for v in axis_variants(main) if v in table.columns]
        if avail:
            table[main] = fold(table[avail])
    table = table.reindex(index=METHODS, columns=AXIS_ORDER)
    joint = np.array([is_joint(m) for m in table.index])
    excluded = [a for a in table.columns if str(a).startswith("cross_assay")]
    table.loc[joint, excluded] = blank
    return table


def axis_scores(scored):
    return _axis_table(scored, "mean", lambda t: t.mean(axis=1), np.nan)


def axis_values(scored):
    """The Method x AXIS_ORDER table of the evidence values."""
    return _axis_table(scored, "mean", lambda t: t.mean(axis=1), np.nan,
                       column="Value")


def count_cells(scored):
    """The dataset cells behind each score, the largest of a main axis'
    variants."""
    return _axis_table(scored, "count", lambda t: t.max(axis=1),
                       0).fillna(0).astype(int)


COVERED, MISSING = "yes", "no"


def feature_coverage(evidence):
    """Which features each dataset contributes evidence for, per main axis."""
    present = set(zip(evidence["Axis"].astype(str), evidence["Dataset"]))
    rows = []
    for axis in AXIS_ORDER:
        variants = axis_variants(axis) if axis in VARIANT_MAIN_AXES else [axis]
        row = {"Feature": axis_label(axis, oneline=True),
               "Metric": AXES[axis][2]}
        for dataset in DATASETS:
            have = sum((v, dataset) in present for v in variants)
            row[DATASET_NAMES[dataset]] = (
                COVERED if have == len(variants)
                else MISSING if have == 0
                else f"{have}/{len(variants)}")
        rows.append(row)
    return pd.DataFrame(rows).set_index("Feature")


def dataset_scores(scored):
    return (scored.pivot_table(index="Method", columns="Dataset", values="score",
                               aggfunc="mean", observed=True)
            .reindex(index=METHODS, columns=DATASETS))


def summary_ranking(scored, methods, table=None):
    """Rank `methods` among themselves over the axes that group is scored
    on."""
    table = axis_scores(scored) if table is None else table
    table = table.loc[[m for m in methods if m in table.index]]
    table = table[[a for a in table.columns if table[a].notna().any()]]
    weights = np.array([AXIS_WEIGHTS.get(a, 1.0) for a in table.columns])
    scores = (table * weights).sum(axis=1) / (table.notna() * weights).sum(axis=1)
    ranking = pd.DataFrame({
        "Method": [utils.display_name(m) for m in table.index],
        "Score": scores,
        "Axes": table.notna().sum(axis=1),
        "Datasets": [scored.loc[scored["Method"] == m, "Dataset"].nunique()
                     for m in table.index],
        "Best axis": [axis_label(table.columns[int(np.nanargmax(row))], oneline=True)
                      if row.notna().any() else "-"
                      for _, row in table.iterrows()],
        "Worst axis": [axis_label(table.columns[int(np.nanargmin(row))], oneline=True)
                       if row.notna().any() else "-"
                       for _, row in table.iterrows()],
    }, index=table.index)
    ranking.index.name = "Key"
    ranking = ranking.sort_values("Score", ascending=False)
    ranking.insert(0, "Rank", range(1, len(ranking) + 1))
    return ranking

## Evidence and scores

In [11]:
df_evidence, df_incomplete = build_evidence(WORKDIRS)
df_scored = score_evidence(df_evidence)

table_scores = axis_scores(df_scored)
table_values = axis_values(df_scored)
table_counts = count_cells(df_scored)
table_datasets = dataset_scores(df_scored)
table_coverage = feature_coverage(df_evidence)
df_ranking_individual = summary_ranking(df_scored, INDIVIDUAL_METHODS,
                                        table_scores)
df_ranking_joint = summary_ranking(df_scored, JOINT_METHODS, table_scores)

df_segment_counts = collect_segment_counts(WORKDIRS, df_incomplete)
df_annotated = collect_annotated_share(WORKDIRS, df_incomplete)
df_comparisons = collect_comparisons(WORKDIRS, df_incomplete)
df_entropy_summary = collect_entropy(WORKDIRS, df_incomplete)
df_peak_stats = collect_peak_stats(WORKDIRS)
df_mark_combinations = collect_mark_combinations(WORKDIRS)
df_rep_states = collect_replicate_states(WORKDIRS, df_incomplete)
df_rep_families = replicate_state_families(df_rep_states)

for name, frame, index in [("evidence", df_scored, False),
                           ("axis_scores", table_scores, True),
                           ("axis_values", table_values, True),
                           ("axis_cells", table_counts, True),
                           ("dataset_scores", table_datasets, True),
                           ("feature_coverage", table_coverage, True),
                           ("ranking_individual", df_ranking_individual, True),
                           ("ranking_joint", df_ranking_joint, True),
                           ("incomplete_segmentations", df_incomplete, False),
                           ("segment_counts", df_segment_counts, False),
                           ("annotated_share", df_annotated, False),
                           ("comparison_metrics", df_comparisons, False),
                           ("entropy_per_segmentation", df_entropy_summary, False),
                           ("peak_stats", df_peak_stats, False),
                           ("mark_combinations", df_mark_combinations, False),
                           ("replicate_states", df_rep_states, False),
                           ("replicate_state_families", df_rep_families, False)]:
    frame.to_csv(f"{OUT}/{name}.tsv", sep="\t", index=index)

coverage = (df_evidence.assign(Axis=df_evidence["Axis"].astype(str))
            .pivot_table(index="Axis", columns="Dataset", values="Value",
                         aggfunc="size")
            .reindex(index=[a for a in ALL_AXIS_CATEGORIES
                            if a in set(df_evidence["Axis"].astype(str))],
                     columns=DATASETS)
            .fillna(0).astype(int))
coverage.to_csv(f"{OUT}/coverage.tsv", sep="\t")

print(f"\n{len(df_evidence)} evidence rows over "
      f"{df_evidence['Cell'].nunique()} cells, tables in {OUT}")
print(f"\nevidence rows per axis and dataset "
      f"({COMPARISON_METRICS}, composition [{COSINE!r}]):")
print(coverage.to_string())

print(f"\nsegment counts of {len(df_segment_counts)} segmentations, mean per "
      f"model and dataset (\u00d710\u00b3):")
print((df_segment_counts.pivot_table(index="Model", columns="Dataset",
                                     values="N_Segments", aggfunc="mean",
                                     observed=True) / 1000).round(1).to_string())

print(f"\nannotated (non-quiescent) share of {len(df_annotated)} "
      f"segmentations, mean per model and dataset (%):")
print((df_annotated.pivot_table(index="Model", columns="Dataset",
                                values="Annotated", aggfunc="mean",
                                observed=True) * 100).round(1).to_string())

print(f"\n{len(df_comparisons)} comparison rows over "
      f"{df_comparisons['Comparison'].nunique()} comparisons x "
      f"{len(SUMMARY_METRIC_ORDER)} metrics, "
      f"{len(df_entropy_summary)} entropy rows, {len(df_peak_stats)} peak rows")

ENCODE caches in /Users/Oleg.Shpynov/data/2026_segmentations/encode/out

  ENCODE cross-assay counts stability (encode:replicates): no ChIP x Mint-ChIP dataset pair has a segmentation on both sides in this scope, so the axis is left to the other scope
SAGAconf caches in /Users/Oleg.Shpynov/data/2026_segmentations/sagaconf/out
1000-epigenomes caches in /Users/Oleg.Shpynov/data/2026_segmentations/epi1000/out
  1000 epigenomes df_replicates.csv: 22 published individual 15-state rows dropped, they are not the de-novo chromhmm_default

  1000 epigenomes df_pw_15.csv: 1000 published individual 15-state rows dropped, 1000 joint ones kept as joint_chromhmm
  1000 epigenomes: the cross-sample caches carry no pair identity, so the sampled pairs behind each method's mean are not checked to be the same ones
  1000 epigenomes df_replicates_emissions.csv: 22 published individual 15-state rows dropped, they are not the de-novo chromhmm_default
  1000 epigenomes df_entropy_15.csv: 98 published individual 15-state rows dropped, 98 joint ones kept as joint_chromhmm
  1000 epigenomes df_segments_15.csv: 98 published individual 15-state rows dropped, 98 joint ones kept as joint_chromhmm
  1000 epigenomes: 183 of 1372 segmentations realize fewer than 15 states (joint_bmm3_homer 80, joint_kmeans_homer 80, kmeans_homer 15, joint_bmm3_macs2 4, joint_kmeans_macs2 4); they stay in the agreement axes, which have no gate for this dataset - see state_recovery for the size of it

  no peaks at all for SAGAconf/cd14_monocyte, SAGAconf/hela_s3, SAGAconf/k562 - the peak analysis of those samples did not run, so they are left out of the peak figures
Loaded cached binarization mark combinations from out/summary/mark_combinations.pkl
  per-state replicate agreement: 420 replicate pairs - ENCODE 42, SAGAconf 70, 1000 epigenomes 308
Loaded cached per-state replicate agreement from out/summary/rep_per_state.pkl

718 evidence rows over 5 cells, tables in out/summary

evidence rows per axis and dataset (['kappa', 'ami'], composition ['cosine']):
Dataset                            encode  sagaconf  epi1000
Axis
replicates_cosine                      14        14       14
replicates_emissions                   14        14       14
functional_atac_sensitivity            22         0        0
functional_atac_precision              22         0        0
functional_tss_sensitivity             22         0        0
functional_tss_precision               22         0        0
functional_refseq_tss_sensitivity      22         0        0
functional_refseq_tss_precision        22         0        0
functional_tx_sensitivity              22         0        0
functional_tx_precision                22         0        0
state_recovery                         22        14       14
segments_stability                     22        14       14
entropy                                22        14       14
cross_sample_cosine                    15        14       14
cross_assay_segments_stability          8         0        0
cross_assay_agreement_cosine            8         0        0
joint_indiv_cosine                      7         7        7
replicates_kappa                       14        14       14
replicates_ami                         14        14       14
cross_sample_kappa                     15        14       14
cross_sample_ami                       15        14       14
joint_indiv_kappa                       7         7        7
joint_indiv_ami                         7         7        7
cross_assay_agreement_kappa             8         0        0
cross_assay_agreement_ami               8         0        0

segment counts of 1692 segmentations, mean per model and dataset (×10³):
Dataset             encode  sagaconf  epi1000
Model
reference            528.8       NaN      NaN
chromhmm_default     707.4     447.2    527.1
joint_chromhmm       561.7     447.0    430.9
kmeans_homer         597.2     878.7    426.1
bmm3_homer           699.9     917.4    612.1
joint_kmeans_homer   678.8     912.8    419.4
joint_bmm3_homer     808.6     949.6    457.0
kmeans_macs2        1047.1     505.4    766.1
bmm3_macs2          1174.2     545.2    840.0
joint_kmeans_macs2   937.9     494.2    760.6
joint_bmm3_macs2    1054.5     544.7    735.2
kmeans_omni          818.8     654.5    867.0
bmm3_omni            830.5     669.7    876.2
joint_kmeans_omni    778.7     646.8    860.7
joint_bmm3_omni      811.6     666.7    865.2

annotated (non-quiescent) share of 1692 segmentations, mean per model and dataset (%):
Dataset             encode  sagaconf  epi1000
Model
reference             27.6       NaN      NaN
chromhmm_default      38.2      20.6     42.8
joint_chromhmm        31.7      16.0     31.7
kmeans_homer          15.2      18.4      8.8
bmm3_homer            15.9      19.1      9.2
joint_kmeans_homer    17.6      18.4      8.8
joint_bmm3_homer      18.6      18.9      8.9
kmeans_macs2          17.0       3.5     17.4
bmm3_macs2            17.7       3.8     17.7
joint_kmeans_macs2    15.1       3.4     17.4
joint_bmm3_macs2      15.6       3.8     17.4
kmeans_omni           33.1      23.5     30.0
bmm3_omni             33.1      23.8     30.0
joint_kmeans_omni     29.2      23.6     29.9
joint_bmm3_omni       29.3      23.8     30.0

62848 comparison rows over 3 comparisons x 4 metrics, 1692 entropy rows, 2724 peak rows

In [12]:
# OmniPeak BMM3 against ChromHMM: the Kappa and AMI of OmniPeak BMM3 minus that
# of a ChromHMM baseline on the same ENCODE comparison unit, for two
# comparisons.
# - Across samples, per same-assay sample pair: against the default ChromHMM
#   model and the published ENCODE reference, which analysis_encode.ipynb runs
#   through the same sweep (df_cross_sample_ref.pkl). Gated as collect_encode()
#   gates it; only the pairs all three segmentations reached, so both
#   baselines are compared on the same pairs.
# - Across samples on SAGAconf (every cell-line pair, df_cross_sample.pkl) and
#   the 1000 epigenomes (the sampled epigenome pairs, pw_cache_*.pkl): against
#   the default ChromHMM model alone.
# - Between replicates, per replicate pair of ENCODE (rep1 vs rep2,
#   df_joint_rep.pkl), SAGAconf (rep1 vs rep2, df_rep.pkl) and the 1000
#   epigenomes (two epigenomes of one condition, df_replicates.csv): against
#   the default ChromHMM model alone, gated as collect_comparisons() gates
#   them. The ENCODE reference has no replicates.
OMNI_VS_CHROMHMM_METRICS = [KAPPA_DISPLAY, AMI_DISPLAY]
OMNI_VS_CHROMHMM_BASELINES = {"ref": "ENCODE Reference",
                              CHROMHMM_DEFAULT: "ChromHMM default"}
OMNI_VS_CHROMHMM_COLUMNS = ["Pair", "Baseline", "Metric", "Model value",
                            "Baseline value", "Value"]


def _omni_vs_baseline_rows(pairs, baselines, metrics, model=BMM3_OMNI):
    """`model` minus each of `baselines` per unit (Dataset) and metric of
    `pairs`, over the units `model` and every baseline reached."""
    rows = []
    for metric in metrics:
        wide = (pairs.pivot(index="Dataset", columns="Method", values=metric)
                .reindex(columns=[model, *baselines])
                .dropna())
        for baseline in baselines:
            rows.append(pd.DataFrame({
                "Pair": wide.index, "Baseline": OMNI_VS_CHROMHMM_BASELINES[baseline],
                "Metric": metric,
                "Model value": wide[model].values,
                "Baseline value": wide[baseline].values,
                "Value": (wide[model] - wide[baseline]).values}))
    return pd.concat(rows, ignore_index=True)


def omni_vs_chromhmm_rows(workdir, incomplete):
    """OmniPeak BMM3 minus each baseline, per same-assay sample pair and
    metric."""
    out = os.path.join(os.path.expanduser(workdir), "out")
    excluded = _excluded_pairs(incomplete, announce=False)
    models = _drop_excluded(_read(f"{out}/df_cross_sample.pkl"), excluded)
    refs = _read(f"{out}/df_cross_sample_ref.pkl")
    if models is None or refs is None:
        return pd.DataFrame(columns=OMNI_VS_CHROMHMM_COLUMNS)
    # The reference keeps the "ref" key of OMNI_VS_CHROMHMM_BASELINES, the
    # one utils.method_color() greys.
    pairs = pd.concat([models.assign(Method=models["Method"].map(canonical)),
                       refs.assign(Method="ref")], ignore_index=True)
    pairs = pairs[pairs["SameAssay"].fillna(True).astype(bool)]
    return _omni_vs_baseline_rows(pairs, list(OMNI_VS_CHROMHMM_BASELINES),
                                  OMNI_VS_CHROMHMM_METRICS)


def omni_vs_chromhmm_sagaconf_rows(incomplete):
    """OmniPeak BMM3 minus the default ChromHMM, per SAGAconf cell-line
    pair."""
    out = os.path.join(os.path.expanduser(WORKDIRS["sagaconf"]), "out")
    pairs = _drop_excluded(_read(f"{out}/df_cross_sample.pkl"),
                           _excluded_pairs(incomplete, announce=False))
    if pairs is None:
        return pd.DataFrame(columns=OMNI_VS_CHROMHMM_COLUMNS)
    return _omni_vs_baseline_rows(
        pairs.assign(Method=pairs["Method"].map(canonical)),
        [CHROMHMM_DEFAULT], OMNI_VS_CHROMHMM_METRICS)


def omni_vs_chromhmm_epi1000_rows(model=BMM3_OMNI):
    """OmniPeak BMM3 minus the default ChromHMM, per sampled 1000 epigenomes
    pair.

    The pw_cache_*.pkl rows name no pair, but utils.sample_pairs() picks them
    by position with a fixed seed, so row k of two methods is the same pair of
    epigenomes whenever both methods segmented the same epigenomes in the same
    order. The segmentation indices of the caches tell: one per epigenome,
    those of two methods a constant step apart when the order is the same.
    """
    out = os.path.join(os.path.expanduser(WORKDIRS["epi1000"]), "out")
    caches = {}
    for method in (model, CHROMHMM_DEFAULT):
        path = f"{out}/pw_cache_{method}.pkl"
        if not os.path.exists(path):
            print(f"  missing {path}")
            return pd.DataFrame(columns=OMNI_VS_CHROMHMM_COLUMNS)
        caches[method] = pd.read_pickle(path)
    indices = [np.array(sorted(c["lengths"])) for c in caches.values()]
    frames = [c["df"] for c in caches.values()]
    if (len(indices[0]) != len(indices[1]) or len(frames[0]) != len(frames[1])
            or len(set(indices[1] - indices[0])) != 1):
        print("  1000 epigenomes: the cross-sample caches of "
              f"{model} and {CHROMHMM_DEFAULT} cover different epigenomes, "
              "their pairs cannot be lined up - left out")
        return pd.DataFrame(columns=OMNI_VS_CHROMHMM_COLUMNS)
    pairs = pd.concat([df.assign(Method=method,
                                 Dataset=[f"pair {k}" for k in range(len(df))])
                       for method, df in zip(caches, frames)],
                      ignore_index=True)
    return _omni_vs_baseline_rows(pairs, [CHROMHMM_DEFAULT],
                                  OMNI_VS_CHROMHMM_METRICS, model=model)


# The replicate agreement cache of each dataset, one row per method and
# replicate pair, its pair in Dataset.
def _encode_replicate_pairs(out, excluded):
    return _drop_excluded(_read(f"{out}/df_joint_rep.pkl"), excluded)


def _sagaconf_replicate_pairs(out, excluded):
    return _drop_excluded(_read(f"{out}/df_rep.pkl"), excluded)


def _epi1000_replicate_pairs(out, excluded):
    # canonical() reads the published 15-state model as the default ChromHMM;
    # it is dropped, as in _epi1000_comparison_rows().
    rep = _drop_reference_indiv(_read(f"{out}/df_replicates.csv"),
                                "1000 epigenomes df_replicates.csv")
    if rep is None:
        return None
    return rep.assign(Dataset=rep["EID1"].astype(str) + "/"
                              + rep["EID2"].astype(str))


OMNI_VS_REPLICATE_CACHES = {"encode": _encode_replicate_pairs,
                            "sagaconf": _sagaconf_replicate_pairs,
                            "epi1000": _epi1000_replicate_pairs}


def omni_vs_chromhmm_replicate_rows(dataset, incomplete,
                                    metrics=(KAPPA_DISPLAY,)):
    """OmniPeak BMM3 minus the default ChromHMM, per replicate pair of
    `dataset`."""
    out = os.path.join(os.path.expanduser(WORKDIRS[dataset]), "out")
    rep = OMNI_VS_REPLICATE_CACHES[dataset](
        out, _excluded_pairs(incomplete, announce=False))
    if rep is None:
        return pd.DataFrame(columns=OMNI_VS_CHROMHMM_COLUMNS)
    return _omni_vs_baseline_rows(
        rep.assign(Method=rep["Method"].map(canonical)), [CHROMHMM_DEFAULT],
        list(metrics))


def omni_vs_chromhmm_table(rows):
    """Mean, median and the share of pairs OmniPeak BMM3 wins, per baseline
    and metric."""
    return (rows.groupby(["Metric", "Baseline"], sort=False)["Value"]
            .agg(Pairs="size", Mean="mean", Median="median",
                 **{"OmniPeak higher": lambda v: (v > 0).mean()}))


df_omni_vs_chromhmm = omni_vs_chromhmm_rows(WORKDIRS["encode"], df_incomplete)
# The cross-sample comparison of every dataset, keyed as DATASET_NAMES.
df_omni_vs_chromhmm_cs = {
    "encode": df_omni_vs_chromhmm,
    "sagaconf": omni_vs_chromhmm_sagaconf_rows(df_incomplete),
    "epi1000": omni_vs_chromhmm_epi1000_rows()}
# Keyed by the comparison of OMNI_VS_COMPARISONS each one is plotted as; the
# ENCODE replicates keep the bare "replicates".
df_omni_vs_chromhmm_reps = {
    "replicates" if dataset == "encode" else f"replicates_{dataset}":
        omni_vs_chromhmm_replicate_rows(dataset, df_incomplete)
    for dataset in OMNI_VS_REPLICATE_CACHES}
for comparison, rows in [("cross_sample", df_omni_vs_chromhmm),
                         ("cross_sample_sagaconf",
                          df_omni_vs_chromhmm_cs["sagaconf"]),
                         ("cross_sample_epi1000",
                          df_omni_vs_chromhmm_cs["epi1000"]),
                         *df_omni_vs_chromhmm_reps.items()]:
    rows.to_csv(f"{OUT}/{comparison}_omni_bmm3_vs_chromhmm.tsv", sep="\t",
                index=False)
    print(f"{comparison}:")
    print(omni_vs_chromhmm_table(rows).round(3).to_string())


# Transition matrix entropy of the ENCODE reference, the default ChromHMM and
# OmniPeak BMM3, pooled segmentations, off the entropy_summary.tsv
# collect_entropy() reads.
def collect_encode_entropy_omni(workdir, incomplete,
                                models=(REFERENCE, CHROMHMM_DEFAULT, BMM3_OMNI)):
    out = os.path.join(os.path.expanduser(workdir), "out")
    entropy = _encode_frames(out, "entropy_summary.tsv", ["total_entropy"])
    if entropy is None:
        _no_cache("ENCODE", "entropy_summary.tsv")
        return pd.DataFrame(columns=["Dataset", "Cell", "Model", "Value"])
    entropy = _drop_excluded(entropy[entropy["Cell"] == "encode:pooled"],
                             _excluded_pairs(incomplete, announce=False))
    entropy = entropy.assign(Model=entropy["Method"].map(canonical))
    entropy = entropy[entropy["Model"].isin(models)]
    return pd.DataFrame({"Dataset": "encode", "Cell": entropy["Dataset"].values,
                         "Model": entropy["Model"].values,
                         "Value": entropy["total_entropy"].astype(float).values})


df_entropy_omni = collect_encode_entropy_omni(WORKDIRS["encode"], df_incomplete)
print(df_entropy_omni.groupby("Model")["Value"].agg(["size", "mean", "var"])
      .round(4).to_string())

cross_sample:
                         Pairs   Mean  Median  OmniPeak higher
Metric Baseline
Kappa  ENCODE Reference     46  0.012   0.017            0.565
       ChromHMM default     46  0.038   0.036            0.761
AMI    ENCODE Reference     46  0.005   0.004            0.522
       ChromHMM default     46 -0.014  -0.016            0.283
cross_sample_sagaconf:
                         Pairs   Mean  Median  OmniPeak higher
Metric Baseline
Kappa  ChromHMM default     10  0.045   0.016              0.7
AMI    ChromHMM default     10 -0.034  -0.037              0.0
cross_sample_epi1000:
                         Pairs   Mean  Median  OmniPeak higher
Metric Baseline
Kappa  ChromHMM default   1000  0.043   0.043            0.682
AMI    ChromHMM default   1000 -0.028  -0.026            0.164
replicates:
                         Pairs   Mean  Median  OmniPeak higher
Metric Baseline
Kappa  ChromHMM default      3  0.098   0.134            0.667
replicates_sagaconf:
                         Pairs   Mean  Median  OmniPeak higher
Metric Baseline
Kappa  ChromHMM default      5  0.076   0.088              0.8
replicates_epi1000:
                         Pairs   Mean  Median  OmniPeak higher
Metric Baseline
Kappa  ChromHMM default     22  0.076   0.081            0.773
                  size    mean     var
Model
bmm3_omni           12  0.2117  0.0015
chromhmm_default    12  0.2885  0.0207
reference           12  0.2337  0.0062

# 2. Doing plotting

In [13]:
# The colour of a family heatmap comes in bands of FAMILY_COLOUR_STEP of a
# column's range, up to FAMILY_COLOUR_TOP; the rest of the column above it
# shares the top colour, so the leaders read as one group.
FAMILY_COLOUR_STEP = 0.1
FAMILY_COLOUR_TOP = 0.8
# Share of white mixed into every colour, for a pale heatmap the values on top
# of it stay readable on.
FAMILY_COLOUR_PALE = 0.4


def _family_colormap(step=FAMILY_COLOUR_STEP, top=FAMILY_COLOUR_TOP,
                     pale=FAMILY_COLOUR_PALE):
    """viridis in bands of `step` over [0, top] of a 0..1 scale, its top
    colour from there on, mixed with `pale` white."""
    from matplotlib.colors import ListedColormap
    ramp = int(round(top / step))
    colors = plt.get_cmap("viridis")(np.linspace(0, 1, ramp))
    colors[:, :3] = colors[:, :3] * (1 - pale) + pale
    return ListedColormap(np.vstack([colors, np.repeat(
        colors[-1:], int(round(1 / step)) - ramp, axis=0)]))


def _column_contrast(table):
    """`table` min-max scaled per column, so the colour ranks the models
    within a family; a column with one value sits mid-scale."""
    low, high = table.min(), table.max()
    span = (high - low).where(high > low)
    return ((table - low) / span).fillna(0.5).where(table.notna())



# White gaps between the RANKING_GROUPS columns of a value heatmap, the groups
# of the grouped rankings, wider between the biological assay and the
# segmentation group.
GROUP_GAP = 4
WIDE_GAP = 8
WIDE_GAP_GROUPS = {"Biological assay", "Segmentation"}


def _group_gaps(ax, axes_keys):
    """Vertical white gaps where the RANKING_GROUPS group of the columns
    changes; an axis in no group stays with the columns before it."""
    groups, current = [], None
    for a in axes_keys:
        current = next((g for g, axes in RANKING_GROUPS.items()
                        if str(a) in axes), current)
        groups.append(current)
    for i in range(1, len(groups)):
        if groups[i] != groups[i - 1]:
            wide = {groups[i - 1], groups[i]} == WIDE_GAP_GROUPS
            ax.axvline(i, color="white",
                       linewidth=WIDE_GAP if wide else GROUP_GAP)

def _value_text(value):
    """A heatmap cell's value, two decimals on the [0, 1] axes, fewer above."""
    if np.isnan(value):
        return ""
    return f"{value:.2f}" if abs(value) < 10 else f"{value:.0f}"


def _heatmap_groups(table):
    """(group, methods, axes_keys) per model family, as the radars draw them."""
    for group, methods in [("individual", INDIVIDUAL_METHODS), ("joint", JOINT_METHODS)]:
        methods = [m for m in methods if m in table.index]
        axes_keys = [a for a in table.columns
                     if methods and table.loc[methods, a].notna().any()]
        if axes_keys:
            yield group, methods, axes_keys


def _axis_heatmap(colour, annot, cmap, cbar_ticks, cbar_label, title, notes,
                  outpath, mark_low=False):
    """One Method x axis heatmap: `colour` on [0, 1] colours the cells,
    `annot` is printed on them."""
    methods, axes_keys = list(colour.index), list(colour.columns)
    fig, ax = plt.subplots(figsize=(0.56 * (3.0 + 1.1 * len(axes_keys)),
                                    0.7 * (1.0 + 0.38 * len(methods)) + 1.5))
    sns.heatmap(colour, ax=ax, vmin=0, vmax=1, cmap=cmap,
                annot=np.vectorize(_value_text)(annot.values), fmt="",
                yticklabels=[utils.display_name(m) for m in methods],
                xticklabels=[_barplot_axis_label(a, mark_low)
                             for a in axes_keys],
                annot_kws={"fontsize": utils.ANNOTATION_FONTSIZE,
                           "color": "black"},
                linewidths=0.5, linecolor="white",
                cbar_kws={"shrink": 0.6})
    _group_gaps(ax, axes_keys)
    cbar = ax.collections[0].colorbar
    cbar.set_ticks(cbar_ticks)
    cbar.ax.tick_params(labelsize=utils.TICK_FONTSIZE)
    cbar.set_label(cbar_label, fontsize=utils.AXIS_FONTSIZE)
    ax.set_title(title, **utils.TITLE_STYLE)
    ax.set_xlabel("")
    ax.set_ylabel("")
    ax.tick_params(axis="y", labelsize=utils.TICK_FONTSIZE, labelrotation=0)
    ax.tick_params(axis="x", labelsize=utils.TICK_FONTSIZE, rotation=45)
    for label in ax.get_xticklabels():
        label.set_ha("right")
    utils.save_fig(fig, outpath, note=f"- {'; '.join(notes)}")


def plot_heatmap_values(table, outdir):
    """The value radar as a Method x axis heatmap of the raw values, the
    colour min-max scaled per column with the better end always on top."""
    for group, methods, axes_keys in _heatmap_groups(table):
        raw = table.loc[methods, axes_keys].astype(float)
        contrast = _column_contrast(raw)
        # Lower is better on these: flipped, so the top colour is the best.
        for a in axes_keys:
            if AXES[str(a)][1] == "low":
                contrast[a] = 1 - contrast[a]
        # The ladder is in column-scaled units, which no metric tick would
        # read right; it shows the ramp only.
        _axis_heatmap(
            contrast, raw, _family_colormap(), [],
            "Per axis normalized", f"Benchmark values of the {group} models",
            ["cell = the axis value, the same as the value radar",
             "colour runs from the worst to the best value of each column "
             "on its own (\u2193 = lower is better, flipped), so it ranks "
             "the models within an axis and does not compare axes, in "
             f"bands of {FAMILY_COLOUR_STEP:.0%} of a column's range; the "
             f"top {1 - FAMILY_COLOUR_TOP:.0%} shares the top colour"],
            os.path.join(outdir, f"heatmap_values_{group}.pdf"), mark_low=True)


def plot_heatmap_ranks(table, outdir):
    """The rank radar as a Method x axis heatmap of the rank scores."""
    for group, methods, axes_keys in _heatmap_groups(table):
        ranks = table.loc[methods, axes_keys].astype(float)
        # Every rank level its own colour: no top share, the best stands out.
        _axis_heatmap(
            ranks, ranks, _family_colormap(top=1.0),
            [0, 0.5, 1], "Rank score (1 = best)",
            f"Rank scores of the {group} models",
            ["cell = the axis' rank score within the family, the same as the "
             "rank radar",
             f"colour in bands of {FAMILY_COLOUR_STEP:.1f}"],
            os.path.join(outdir, f"heatmap_ranks_{group}.pdf"))


LOWER_BETTER_MARK = " \u2193"


def _barplot_axis_label(axis, mark_low=False):
    """The one-line axis label a barplot puts on the x axis."""
    label = axis_label(axis, oneline=True)
    return label + LOWER_BETTER_MARK if mark_low and AXES[str(axis)][1] == "low" \
        else label


def plot_ranking(ranking, table, group, outpath):
    order = ranking.index.tolist()
    axes_keys = [a for a in table.columns if table.loc[order, a].notna().any()]
    fig, ax = plt.subplots(figsize=(8.4, 0.32 * len(order) + 0.8))
    positions = np.arange(len(order))
    bars = ax.barh(positions, ranking.loc[order, "Score"].values,
                   color=[_segment_count_color(m) for m in order],
                   edgecolor=utils.BAR_STYLE["edgecolor"], linewidth=utils.BAR_STYLE["linewidth"], height=0.5, zorder=2)
    for bar, method in zip(bars, order):
        if is_joint(method):
            bar.set_hatch(JOINT_HATCH)
    for y, method in enumerate(order):
        scores = table.loc[method, axes_keys].dropna().values
        rng = np.random.default_rng(y)
        ax.scatter(scores, y + rng.uniform(-0.1, 0.1, len(scores)),
                   s=POINT_SIZE, **utils.POINT_STYLE)
        ax.text(1.04, y, f"{ranking.loc[method, 'Score']:.2f}",
                va="center", fontsize=utils.LABEL_FONTSIZE, color="#333333")
    ax.set_yticks(positions)
    ax.set_yticklabels([f"{ranking.loc[m, 'Rank']}. {utils.display_name(m)}"
                        for m in order], fontsize=utils.TICK_FONTSIZE)
    ax.tick_params(axis="x", labelsize=utils.TICK_FONTSIZE)
    ax.invert_yaxis()
    ax.set_xlim(0, 1.2)
    ax.set_xticks([0, 0.25, 0.5, 0.75, 1.0])
    ax.axvline(1.0, color="#cccccc", linewidth=0.8)
    ax.axvline(0.5, color="#999999", linewidth=0.8, linestyle="--")
    ax.set_xlabel(f"mean rank score over the axes (1 = best of the {group} "
                  f"models), points are the per-axis scores behind it",
                  fontsize=utils.AXIS_FONTSIZE)
    n_datasets = int(ranking["Datasets"].max()) if not ranking.empty else 0
    ax.set_title(f"Summary ranking of the {group} models "
                 f"({len(axes_keys)} benchmarks, {n_datasets} datasets)",
                 **utils.TITLE_STYLE)
    ax.grid(axis="x", alpha=0.3)
    utils.save_fig(fig, outpath)


REFERENCE_LABEL = "Reference"
SEGMENTS_K_LABEL = "Segments (×10³)"


def _segment_count_label(model):
    """Legend label of a segment-count bar, "Reference" for the published
    markup."""
    return REFERENCE_LABEL if model == REFERENCE else utils.display_name(model)


def _segment_count_color(model):
    return utils.bin_color("reference") if model == REFERENCE \
        else utils.method_color(model)


PANEL_SIZE = (9.0, 4.8)

STATES_LABEL = "States"

SEGMENT_COUNT_VARIANTS = [("_all", METHODS)]

# (column, file stem, title, y label, y scaling) per granularity figure.
GRANULARITY_FIGURES = [
    ("N_Segments", "segment_counts", "Number of segments per segmentation",
     SEGMENTS_K_LABEL, 1 / 1000.0),
    ("N_States", "state_counts", "Actual number of states",
     STATES_LABEL, 1.0),
]

ANNOTATED_LABEL = "Genome outside the quiescent state (%)"

ANNOTATED_FIGURES = [
    ("Annotated", "annotated_share",
     "Share of the genome on a state other than the quiescent one",
     ANNOTATED_LABEL, 100.0),
]


def _segment_count_variant(counts, models):
    """`counts` cut to the segmentations a variant reads: the ENCODE joint
    models exist per replicate only, and the individual counts differ between
    the two scopes, so a figure with both families takes the replicate scope
    and keeps the pooled reference."""
    if not any(is_joint(m) for m in models):
        keep = counts["Scope"] != "replicates"
    else:
        keep = (counts["Scope"] != "pooled") | (counts["Model"] == REFERENCE)
    return counts[keep & counts["Model"].isin(models)]


def _per_model_figures(counts, figures, outdir):
    """One figure per (column of `figures`, model variant): the three datasets
    side by side, a bar per model, over the segmentations `counts` holds.

    Reference is the published markup ENCODE ships per dataset; SAGAconf has
    none, and the published 15-state joint model of the 1000 epigenomes is
    drawn as its joint ChromHMM instead."""
    written = []
    for column, stem, title, ylabel, scale in figures:
        for suffix, wanted in SEGMENT_COUNT_VARIANTS:
            rows = _segment_count_variant(counts, wanted).dropna(subset=[column])
            models = [m for m in wanted if (rows["Model"] == m).any()]
            if not models:
                continue
            datasets = [d for d in DATASETS if (rows["Dataset"] == d).any()]
            order = [DATASET_NAMES[d] for d in datasets]
            hue_order = [_segment_count_label(m) for m in models]
            frame = rows.assign(**{
                "Dataset Name": rows["Dataset"].astype(str).map(DATASET_NAMES),
                "Model Name": rows["Model"].astype(str).map(_segment_count_label),
                ylabel: rows[column] * scale})

            ax = utils.bar_plot(
                frame, "Dataset Name", ylabel, order=order,
                hue="Model Name", hue_order=hue_order,
                palette={_segment_count_label(m): _segment_count_color(m)
                         for m in models},
                figsize=PANEL_SIZE, rotation=0, hatch="joint",
                points={"size": 2.5, "alpha": 0.55, "jitter": 0.2},
                title=title, xlabel="Dataset", ylabel=ylabel, legend=True,
                legend_title="Model")
            note = None
            if (rows["Dataset"] == "encode").any():
                note = ("- ENCODE per-replicate segmentations, the scope its "
                        "joint models exist in; its reference markup is the "
                        "pooled one, it has no per-replicate counterpart"
                        if any(is_joint(m) for m in models)
                        else "- ENCODE pooled segmentations")
            name = f"{stem}{suffix}.pdf"
            utils.save_fig(ax.get_figure(), os.path.join(outdir, name), note=note)
            written.append(name)
    return written


CALLER_ORDER = [utils.CALLER_DISPLAY[c] for c in
                 [utils.CHROMHMM, utils.HOMER, utils.MACS2, utils.OMNI]]

CALLER_PALETTE = {
    utils.CALLER_DISPLAY[utils.CHROMHMM]: utils.BIN_COLORS["default"],
    utils.CALLER_DISPLAY[utils.HOMER]: utils.BIN_COLORS["homer"],
    utils.CALLER_DISPLAY[utils.MACS2]: utils.BIN_COLORS["macs2"],
    utils.CALLER_DISPLAY[utils.OMNI]: utils.BIN_COLORS["omnipeak"],
}


def _caller_bars(rows, value_col, path, title, ylabel, ylim=None, notes=()):
    """One bar per peak caller of `rows`' models, every dataset pooled."""
    frame = rows.assign(Method=rows["Method"].astype(str).map(utils.method_group))
    order = [c for c in CALLER_ORDER if (frame["Method"] == c).any()]
    ax = utils.bar_plot(
        frame, "Method", value_col, order=order, palette=CALLER_PALETTE,
        figsize=(3.75, 4.8), rotation=0, hatch=None, ylim=ylim,
        points={"size": 2.5, "alpha": 0.55, "jitter": 0.2},
        title=title, xlabel="Method", ylabel=ylabel, legend=False)
    notes = [note for note in notes if note]
    utils.save_fig(ax.get_figure(), path, note=f"- {'; '.join(notes)}" if notes else None)
    return [os.path.basename(path)]


def plot_state_counts_methods(counts, outdir):
    """Actual number of states per segmentation, grouped by method only
    (ChromHMM, HOMER, MACS2, OmniPeak)."""
    if counts.empty:
        return []
    # The reference has no caller to be grouped under.
    models = [m for m in METHODS if m != REFERENCE]
    column, stem, title, ylabel, scale = GRANULARITY_FIGURES[1]
    rows = _segment_count_variant(counts, models).dropna(subset=[column])
    if rows.empty:
        return []
    frame = rows.assign(**{"Method": rows["Model"],
                           ylabel: rows[column] * scale})
    return _caller_bars(frame, ylabel,
                        os.path.join(outdir, f"{stem}_methods.pdf"),
                        title, ylabel)


def plot_segment_counts(counts, outdir):
    """Segment and state counts of every segmentation, a bar per model.

    The state count is how many labels a segmentation actually uses, which is
    below the 15 states it was asked for wherever a model collapses some of
    them."""
    if counts.empty:
        print("  no segment counts to plot")
        return []
    return _per_model_figures(counts, GRANULARITY_FIGURES, outdir) +         plot_state_counts_methods(counts, outdir)


def plot_annotated_share(shares, outdir):
    """How much of the genome every segmentation puts on a state other than
    the quiescent one, a bar per model.

    The quiescent state is the one no mark reaches, so this is the share of
    the genome a model says something about at all. It is not a score on its
    own - a model can annotate more of the genome by spreading a weak state
    over it - but it is what the agreement metrics are dominated by, and it
    is where the callers differ most."""
    if shares.empty:
        print("  no state coverage to plot")
        return []
    return _per_model_figures(shares, ANNOTATED_FIGURES, outdir) + \
        plot_annotated_share_chromhmm(shares, outdir) + \
        plot_annotated_share_omni(shares, outdir) + \
        plot_annotated_share_omni_variance(shares, outdir) + \
        plot_annotated_share_omni_datasets(shares, outdir)


def plot_annotated_share_chromhmm(shares, outdir):
    """Targeted comparison of the ChromHMM models and the reference on ENCODE
    and EPI1000."""
    if shares.empty:
        print("  no state coverage to plot")
        return []

    models = [REFERENCE, CHROMHMM_DEFAULT, JOINT_CHROMHMM]
    datasets = ["encode", "epi1000"]
    column, stem, title, ylabel, scale = ANNOTATED_FIGURES[0]

    rows = _segment_count_variant(shares, models).dropna(subset=[column])
    rows = rows[rows["Dataset"].isin(datasets)]
    # User request: don't show ChromHMM and ChromHMM joint for ENCODE, 
    # only show ENCODE reference, 15 state individual and 15 state joint models.
    rows = rows[((rows["Dataset"] == "encode") & (rows["Model"] == REFERENCE)) |
                ((rows["Dataset"] == "epi1000") & (rows["Model"].isin([CHROMHMM_DEFAULT, JOINT_CHROMHMM])))]
    if rows.empty:
        return []

    def _label(model, dataset):
        if dataset == "encode" and model == REFERENCE:
            return "ENCODE reference"
        if model == CHROMHMM_DEFAULT:
            return "Individual ChromHMM"
        return _segment_count_label(model)

    frame = rows.assign(**{
        "Legend Name": [_label(m, d) for m, d in zip(rows["Model"], rows["Dataset"])],
        ylabel: rows[column] * scale})

    hue_order = ["ENCODE reference", "Individual ChromHMM",
                 _segment_count_label(JOINT_CHROMHMM)]
    hue_order = [h for h in hue_order if h in frame["Legend Name"].values]

    # The method colours; the joint model is told apart by its hatch.
    palette = {
        "ENCODE reference": _segment_count_color(REFERENCE),
        "Individual ChromHMM": _segment_count_color(CHROMHMM_DEFAULT),
        _segment_count_label(JOINT_CHROMHMM): _segment_count_color(JOINT_CHROMHMM)
    }

    ax = utils.bar_plot(
        frame, "Legend Name", ylabel, order=hue_order,
        hue="Legend Name", hue_order=hue_order,
        palette=palette,
        figsize=(4.0, 4.8), rotation=45, hatch="joint",
        points={"size": 2.5, "alpha": 0.55, "jitter": 0.2},
        # Three bars leave a narrow axes, too narrow for the full title.
        title="Non-quiescent share", xlabel="Method", ylabel=ylabel,
        legend=False)

    name = f"{stem}_chromhmm.pdf"
    utils.save_fig(ax.get_figure(), os.path.join(outdir, name))
    return [name]


OMNI_SHARE_MODELS = {REFERENCE: "ENCODE reference",
                     CHROMHMM_DEFAULT: "ChromHMM default",
                     BMM3_OMNI: utils.display_name(BMM3_OMNI)}


def _omni_frame(rows, column, value_col, scale=1.0, models=OMNI_SHARE_MODELS):
    """`rows` of `models` - one per ENCODE dataset (Cell) and Model - over the
    datasets all of them cover, `column` times `scale` under `value_col`."""
    rows = rows[rows["Model"].isin(list(models))].dropna(subset=[column])
    complete = rows.groupby("Cell")["Model"].nunique() == len(models)
    rows = rows[rows["Cell"].isin(complete[complete].index)]
    return rows.assign(**{
        "Legend Name": rows["Model"].astype(str).map(models),
        value_col: rows[column] * scale})


def _omni_share_frame(shares, models=OMNI_SHARE_MODELS):
    """The pooled ENCODE segmentations of `models`, the share in percent under
    ANNOTATED_LABEL."""
    column, _, _, ylabel, scale = ANNOTATED_FIGURES[0]
    return _omni_frame(shares[(shares["Dataset"] == "encode")
                              & (shares["Scope"] == "pooled")],
                       column, ylabel, scale, models)


def _squared_deviation(frame, value_col, column, scale=1.0):
    """`frame` with each row's squared deviation from its model's mean, times
    `scale`, under `column`: the mean of a model's rows is its variance."""
    mean = frame.groupby("Model", observed=True)[value_col].transform("mean")
    return frame.assign(**{column: (frame[value_col] - mean) ** 2 * scale})


def _outlier_top(frame, value_col):
    """The top of a `frame` bar plot's y axis that leaves its outliers - the
    points above Q3 + 3 IQR - off the axes, with every bar and its error bar
    kept in view; and the rows it leaves out."""
    values = frame[value_col]
    q1, q3 = values.quantile([0.25, 0.75])
    inside = values[values <= q3 + 3 * (q3 - q1)]
    bars = frame.groupby("Legend Name", observed=True)[value_col]
    top = 1.1 * max(inside.max(), (bars.mean() + bars.sem().fillna(0)).max())
    return top, frame[values > top]


def _omni_bars(frame, value_col, path, title, ylabel, note,
               models=OMNI_SHARE_MODELS, ylim=None, clip=False):
    """A bar per model of `frame`, every dataset a point. `clip` cuts the y
    axis above the outliers (_outlier_top()); the bars are still the means
    over every point, and the note names the points drawn off the axes."""
    order = list(models.values())
    if clip:
        top, clipped = _outlier_top(frame, value_col)
        ylim = (0, top)
        if len(clipped):
            note += "; " + ", ".join(
                f"{cell} {label} ({value:.3g})" for cell, label, value in zip(
                    clipped["Cell"], clipped["Legend Name"],
                    clipped[value_col])) + " above the axes"
    ax = utils.bar_plot(
        frame, "Legend Name", value_col, order=order,
        hue="Legend Name", hue_order=order,
        palette={label: _segment_count_color(model)
                 for model, label in models.items()},
        figsize=(4.0, 4.8), rotation=45, hatch=None, ylim=ylim,
        points={"size": 2.5, "alpha": 0.55, "jitter": 0.2},
        title=title, xlabel="Method", ylabel=ylabel, legend=False)
    utils.save_fig(ax.get_figure(), path, note=note)
    return [os.path.basename(path)]


def _omni_note(frame, variance=False):
    note = (f"- {frame['Cell'].nunique()} ENCODE datasets, pooled "
            f"segmentations")
    if variance:
        return (note + "; bar = variance over the datasets, point = one "
                "dataset's squared deviation from its model's mean")
    return note + ", point = one dataset"


def plot_annotated_share_omni(shares, outdir):
    """Non-quiescent share of the ENCODE reference, the default ChromHMM and
    OmniPeak BMM3, over the ENCODE datasets all three cover."""
    _, stem, _, ylabel, _ = ANNOTATED_FIGURES[0]
    frame = _omni_share_frame(shares)
    if frame.empty:
        print("  no ENCODE non-quiescent share to plot")
        return []
    return _omni_bars(
        frame, ylabel,
        os.path.join(outdir, f"{stem}_omni_bmm3_vs_chromhmm.pdf"),
        "Non-quiescent share", ylabel, note=_omni_note(frame))


def plot_annotated_share_omni_variance(shares, outdir):
    """Variance of the non-quiescent share over the ENCODE datasets, per
    model, as in plot_entropy_global_variance()."""
    _, stem, _, ylabel, _ = ANNOTATED_FIGURES[0]
    frame = _omni_share_frame(shares)
    if frame.empty:
        print("  no ENCODE non-quiescent share to plot")
        return []
    column = "Squared deviation (%²)"
    return _omni_bars(
        _squared_deviation(frame, ylabel, column), column,
        os.path.join(outdir, f"{stem}_variance_omni_bmm3_vs_chromhmm.pdf"),
        "Non-quiescent share variance", "Variance (%²)",
        note=_omni_note(frame, variance=True))


ENTROPY_LABEL = "Entropy (bits)"


def plot_entropy_omni(entropy, outdir):
    """Transition matrix entropy of the ENCODE reference, the default ChromHMM
    and OmniPeak BMM3, over the ENCODE datasets all three cover."""
    frame = _omni_frame(entropy, "Value", ENTROPY_LABEL)
    if frame.empty:
        print("  no ENCODE entropy to plot")
        return []
    return _omni_bars(
        frame, ENTROPY_LABEL,
        os.path.join(outdir, "entropy_omni_bmm3_vs_chromhmm.pdf"),
        "Transition matrix entropy", ENTROPY_LABEL, note=_omni_note(frame),
        clip=True)


def plot_entropy_omni_variance(entropy, outdir):
    """Variance of the transition matrix entropy over the ENCODE datasets,
    per model, in the units of plot_entropy_global_variance()."""
    frame = _omni_frame(entropy, "Value", ENTROPY_LABEL)
    if frame.empty:
        print("  no ENCODE entropy to plot")
        return []
    column = "Squared deviation (×10³ bits²)"
    return _omni_bars(
        _squared_deviation(frame, ENTROPY_LABEL, column, scale=1000.0), column,
        os.path.join(outdir, "entropy_variance_omni_bmm3_vs_chromhmm.pdf"),
        "Transition matrix entropy variance", "Variance (×10³ bits²)",
        note=_omni_note(frame, variance=True), clip=True)


# The same comparisons over every dataset, a group of bars per dataset. Only
# ENCODE has a reference here - SAGAconf has none and the 1000 epigenomes' one
# is not cached per epigenome - so it is a bar on ENCODE alone.
# ENCODE reads its pooled segmentations, as the figures above; SAGAconf has no
# pooled one, so both of its replicates enter as points.
OMNI_DATASET_MODELS = [CHROMHMM_DEFAULT, BMM3_OMNI]
OMNI_DATASET_SHARE_MODELS = [REFERENCE] + OMNI_DATASET_MODELS


def _omni_dataset_rows(rows, value_col, scale=1.0, models=OMNI_DATASET_MODELS):
    """`rows` of `models` - Dataset, Method, `value_col` - times `scale`."""
    rows = rows[rows["Method"].isin(models)].dropna(subset=[value_col])
    return rows.assign(Value=rows[value_col].astype(float) * scale)


def _omni_dataset_variance(rows, scale=1.0):
    """Each row's squared deviation from its dataset and model's mean, times
    `scale`, as Value: the mean of a bar's rows is its variance."""
    mean = rows.groupby(["Dataset", "Method"], observed=True)["Value"] \
        .transform("mean")
    return rows.assign(Value=(rows["Value"] - mean) ** 2 * scale)


def _omni_dataset_note(rows, variance=False):
    counts = rows[rows["Method"] == CHROMHMM_DEFAULT].groupby(
        "Dataset", observed=True)["Cell"].size()
    note = ("segmentations per model - " + ", ".join(
        f"{DATASET_NAMES[d]} {counts[d]}" for d in DATASETS
        if counts.get(d, 0))
        + "; ENCODE pooled, SAGAconf both replicates")
    if (rows["Method"] == REFERENCE).any():
        note += "; the reference on ENCODE only"
    if variance:
        note += ("; bar = variance over the dataset's segmentations, point = "
                 "one segmentation's squared deviation from its mean")
    return note


def _omni_dataset_figure(rows, path, title, ylabel, note,
                         models=OMNI_DATASET_MODELS, top=None):
    """`top` cuts the y axis there; the bars stay the means over every row,
    and the note names the rows drawn off the axes."""
    notes = [note]
    if top is not None:
        above = rows[rows["Value"] > top]
        if len(above):
            notes.append(f"{len(above)} point{'s' if len(above) > 1 else ''} "
                         f"above the axes, up to "
                         f"{above['Value'].max():.3g} "
                         f"({above.loc[above['Value'].idxmax(), 'Cell']})")
    return _summary_figure(rows, models, "Value", path, title,
                           ylabel=ylabel, figwidth=6.0, rotation=45,
                           notes=notes, gaps=False,
                           ylim=None if top is None else (0, top))


def plot_annotated_share_omni_datasets(shares, outdir):
    """Non-quiescent share of the default ChromHMM and OmniPeak BMM3 on every
    dataset."""
    column, stem, _, ylabel, scale = ANNOTATED_FIGURES[0]
    rows = shares[shares["Scope"] != "replicates"].rename(
        columns={"Model": "Method"})
    models = OMNI_DATASET_SHARE_MODELS
    rows = _omni_dataset_rows(rows, column, scale, models=models)
    if rows.empty:
        print("  no non-quiescent share to plot")
        return []
    return [
        _omni_dataset_figure(
            rows, os.path.join(outdir,
                               f"{stem}_omni_bmm3_vs_chromhmm_datasets.pdf"),
            "Non-quiescent share", ylabel, _omni_dataset_note(rows),
            models=models),
        _omni_dataset_figure(
            _omni_dataset_variance(rows),
            os.path.join(outdir, f"{stem}_variance_omni_bmm3_vs_chromhmm"
                                 f"_datasets.pdf"),
            "Non-quiescent share variance", "Variance (%²)",
            _omni_dataset_note(rows, variance=True), models=models)]


def plot_entropy_omni_datasets(entropy, outdir):
    """Transition matrix entropy of the ENCODE reference, the default ChromHMM
    and OmniPeak BMM3 on every dataset."""
    pooled = ~((entropy["Dataset"] == "encode")
               & entropy["Cell"].astype(str).str.contains(r"_rep\d$"))
    entropy = entropy[pooled].assign(Dataset=entropy["Dataset"].astype(str))
    models = OMNI_DATASET_SHARE_MODELS
    rows = _omni_dataset_rows(entropy, "Value", models=models)
    if rows.empty:
        print("  no entropy to plot")
        return []
    return [
        _omni_dataset_figure(
            rows, os.path.join(outdir,
                               "entropy_omni_bmm3_vs_chromhmm_datasets.pdf"),
            "Transition matrix entropy", ENTROPY_LABEL,
            _omni_dataset_note(rows), models=models),
        _omni_dataset_figure(
            _omni_dataset_variance(rows, scale=1000.0),
            os.path.join(outdir,
                         "entropy_variance_omni_bmm3_vs_chromhmm_datasets.pdf"),
            "Transition matrix entropy variance", "Variance (×10³ bits²)",
            _omni_dataset_note(rows, variance=True), models=models,
            # One ENCODE segmentation reaches 128 and would flatten every
            # other bar.
            top=40)]


SUMMARY_POINTS = {"size": 1.5, "alpha": 0.35, "jitter": 0.28}

POINTS_PER_BAR = 150

MODEL_VARIANTS = [("all", METHODS)]

COMPARISON_NOTES = {
    "cross_sample": "different samples segmented by the same model: every "
                    "same-assay dataset pair of ENCODE, every cell-line pair "
                    "of SAGAconf, a reproducible sample of 1000 epigenome "
                    "pairs",
    "replicates": "the two replicates of one biological condition, which is "
                  "the reproducibility ceiling of a model",
    "joint_indiv": "a sample segmented on its own against the same sample "
                   "inside a joint model, so each bar already compares the "
                   "two families and the figure has no joint variant",
}


def _model_variants(rows):
    """(suffix, models) per variant over the models `rows` holds, no
    repeats."""
    variants = []
    for suffix, models in MODEL_VARIANTS:
        present = tuple(m for m in models if (rows["Method"] == m).any())
        if not present or any(present == earlier for _, earlier in variants):
            continue
        variants.append((suffix, present))
    return variants


def _thin_points(frame, keys=("Dataset Name", "Model Name")):
    """At most POINTS_PER_BAR rows per bar with a fixed seed; None when nothing
    needs thinning."""
    groups = [group for _, group in frame.groupby(list(keys), observed=True)]
    if not any(len(group) > POINTS_PER_BAR for group in groups):
        return None
    return pd.concat([group if len(group) <= POINTS_PER_BAR
                      else group.sample(POINTS_PER_BAR, random_state=0)
                      for group in groups])


def _thinned_note(rows, keys):
    """The note of a figure whose densest bars are drawn thinned, or None."""
    sizes = rows.groupby(list(keys), observed=True).size()
    if sizes.empty or sizes.max() <= POINTS_PER_BAR:
        return None
    return (f"points thinned to {POINTS_PER_BAR} of the {int(sizes.max())} on "
            f"the densest bar; every bar is the mean over all of them")


def _model_bars(ax, rows, value_col, models, x_col, x_order, **kwargs):
    """One panel of a summary figure: a bar per model over the `x_col`
    levels."""
    frame = rows.assign(**{
        "Dataset Name": rows["Dataset"].astype(str).map(DATASET_NAMES),
        "Model Name": rows["Method"].astype(str).map(utils.display_name)})
    return utils.bar_plot(
        frame, x_col, value_col, ax=ax, order=list(x_order),
        hue="Model Name", hue_order=[utils.display_name(m) for m in models],
        palette={utils.display_name(m): _segment_count_color(m) for m in models},
        points=SUMMARY_POINTS,
        point_data=_thin_points(frame, (x_col, "Model Name")),
        legend_title="Model", **kwargs)


def _summary_figure(rows, models, value_col, path, title, ylabel,
                    x_col="Dataset Name", x_order=None, panel_col=None,
                    panels=None, panel_labels=None, notes=(), ylim=None,
                    log=False, figwidth=PANEL_SIZE[0], rotation=0, gaps=True):
    """One summary figure: the `panels` levels of `panel_col` side by side, or
    a single panel."""
    if x_order is None:
        x_order = [DATASET_NAMES[d] for d in DATASETS
                   if (rows["Dataset"] == d).any()]
    keys = list(panels) if panels else [None]
    fig, axes = plt.subplots(1, len(keys),
                             figsize=(figwidth * len(keys), PANEL_SIZE[1]),
                             sharey=True, squeeze=False)
    for i, (ax, key) in enumerate(zip(axes[0], keys)):
        panel = rows if key is None else rows[rows[panel_col] == key]
        _model_bars(ax, panel, value_col, models, x_col, x_order,
                    title=None if key is None
                    else str((panel_labels or {}).get(key, key)),
                    xlabel="", ylabel=ylabel if i == 0 else "", ylim=ylim,
                    log=log, rotation=rotation, legend=(i == len(keys) - 1),
                    gaps=gaps)
    fig.suptitle(title, **utils.TITLE_STYLE)
    notes = [note for note in notes if note]
    utils.save_fig(fig, path, note=f"- {'; '.join(notes)}" if notes else None)
    return os.path.basename(path)


def plot_comparison_figures(comparisons, outdir):
    """One figure per comparison, metric and model variant."""
    written = []
    if comparisons.empty:
        print("  no comparison metrics to plot")
        return written
    for comparison in SUMMARY_COMPARISONS:
        for metric in SUMMARY_METRIC_ORDER:
            rows = comparisons[(comparisons["Comparison"] == comparison)
                               & (comparisons["Metric"] == metric)]
            if rows.empty:
                continue
            for suffix, models in _model_variants(rows):
                name = (f"agreement_{comparison}_{utils.slug(metric)}"
                        f"_{suffix}.pdf")
                variant = rows[rows["Method"].isin(models)]
                written.append(_summary_figure(
                    variant, models, "Value", os.path.join(outdir, name),
                    f"{axis_label(comparison, oneline=True)}: {metric}",
                    ylabel=f"{metric} index", ylim=(0, 1.05),
                    notes=[_thinned_note(variant, ("Dataset", "Method"))]))
    return written


def plot_entropy_figures(entropy, outdir):
    """Transition matrix entropy, one figure per model variant."""
    written = []
    if entropy.empty:
        print("  no entropy to plot")
        return written
    for suffix, models in _model_variants(entropy):
        name = f"entropy_{suffix}.pdf"
        variant = entropy[entropy["Method"].isin(models)]
        written.append(_summary_figure(
            variant, models, "Value", os.path.join(outdir, name),
            "Transition matrix entropy", ylabel="Entropy (bits)",
            notes=[_thinned_note(variant, ("Dataset", "Method"))]))
    return written


GLOBAL_METHODS = [CHROMHMM_DEFAULT, KMEANS_HOMER, KMEANS_MACS2, KMEANS_OMNI]


def _coverage_note(rows, models):
    """Which datasets every bar of a pooled figure draws on, and how many
    values each one contributes."""
    parts = []
    for m in models:
        counts = rows[rows["Method"] == m].groupby("Dataset", observed=True).size()
        counts = counts[counts > 0]
        parts.append(f"{utils.display_name(m)}: " + ", ".join(
            f"{DATASET_NAMES[d]} {n}" for d, n in counts.items()))
    return "values per dataset - " + "; ".join(parts)


def _models_note(models):
    """Which model of each caller a per-caller figure draws, all datasets
    pooled."""
    return ("all datasets pooled; models "
            + ", ".join(utils.display_name(m) for m in models))


def plot_entropy_global_variance(entropy, outdir, models=GLOBAL_METHODS):
    """Variance of the transition matrix entropy over every segmentation of
    every dataset. A point is one segmentation's squared deviation from its
    model's pooled mean, so a bar - their mean - is the pooled variance."""
    rows = entropy[entropy["Method"].isin(models)]
    if rows.empty:
        print("  no entropy to plot")
        return []
    mean = rows.groupby("Method", observed=True)["Value"].transform("mean")
    column = "Squared deviation (×10³ bits²)"
    rows = rows.assign(**{column: (rows["Value"] - mean) ** 2 * 1000.0})
    # A few outlying segmentations would flatten every bar; they stay in the
    # variance and are only drawn off the top of the axes.
    top = 1.1 * rows[column].quantile(0.98)
    clipped = rows[rows[column] > top]
    return _caller_bars(
        rows, column, os.path.join(outdir, "entropy_global_variance.pdf"),
        "Transition matrix entropy variance",
        ylabel="Variance (×10³ bits²)", ylim=(0, top),
        notes=[_models_note(models), "bar = variance of the entropy pooled over all datasets, "
               "point = one segmentation's squared deviation from the pooled "
               "mean",
               f"{len(clipped)} points above the axes, up to "
               f"{clipped[column].max():.0f} ({clipped.loc[clipped[column].idxmax(), 'Cell']})"
               if len(clipped) else None,
               _coverage_note(rows, models)])


def plot_joint_indiv_kappa(comparisons, outdir, models=GLOBAL_METHODS):
    """Kappa of every individual segmentation against the same sample in its
    joint model, all datasets pooled."""
    rows = comparisons[(comparisons["Comparison"] == "joint_indiv")
                       & (comparisons["Metric"] == KAPPA_DISPLAY)
                       & comparisons["Method"].isin(models)]
    if rows.empty:
        print("  no individual vs joint Kappa to plot")
        return []
    return _caller_bars(
        rows, "Value",
        os.path.join(outdir, "agreement_joint_indiv_kappa_global.pdf"),
        f"Individual vs joint {KAPPA_DISPLAY}",
        ylabel=f"{KAPPA_DISPLAY} index", ylim=(0, 1.05),
        notes=[_models_note(models), "point = one sample, its individual segmentation against its "
               "joint-model segmentation", _coverage_note(rows, models)])

JOINT_COUNTERPARTS = {joint: indiv for indiv, joint in JOINT_OF.items()}


def joint_gain_rows(comparisons, comparison="replicates", metric=AMI_DISPLAY):
    """Joint minus individual `metric` of every comparison unit - a replicate
    pair - keyed by the individual model of its pipeline."""
    rows = comparisons[(comparisons["Comparison"] == comparison)
                       & (comparisons["Metric"] == metric)]
    wide = rows.assign(Method=rows["Method"].astype(str)).pivot(
        index=["Dataset", "Cell"], columns="Method", values="Value")
    frames = [pd.DataFrame({"Dataset": wide.index.get_level_values("Dataset"),
                            "Cell": wide.index.get_level_values("Cell"),
                            "Method": indiv,
                            "Value": (wide[joint] - wide[indiv]).values})
              for joint, indiv in JOINT_COUNTERPARTS.items()
              if joint in wide and indiv in wide]
    if not frames:
        return pd.DataFrame(columns=["Dataset", "Cell", "Method", "Value"])
    return _summary_categoricals(
        pd.concat(frames, ignore_index=True).dropna(subset=["Value"]))


def plot_replicate_joint_gain(comparisons, outdir):
    """Paired difference joint - individual of every replicate pair, one
    figure per metric, a bar per pipeline over the datasets; the companions
    of the agreement_replicates_*_all.pdf figures."""
    written = []
    for metric in SUMMARY_METRIC_ORDER:
        rows = joint_gain_rows(comparisons, metric=metric)
        if rows.empty:
            continue
        models = [m for m in INDIVIDUAL_METHODS
                  if (rows["Method"] == m).any()]
        x_order = [DATASET_NAMES[d] for d in DATASETS
                   if (rows["Dataset"] == d).any()]
        fig, ax = plt.subplots(figsize=PANEL_SIZE)
        _model_bars(ax, rows, "Value", models, "Dataset Name", x_order,
                    xlabel="", ylabel=f"{metric} joint − individual",
                    rotation=0, legend=True)
        ax.axhline(0, color="black", linewidth=0.8)
        fig.suptitle(f"Replicates: joint − individual {metric}",
                     **utils.TITLE_STYLE)
        name = (f"agreement_replicates_{utils.slug(metric)}"
                f"_joint_minus_individual.pdf")
        utils.save_fig(fig, os.path.join(outdir, name),
                       note=f"- point = one replicate pair, the {metric} "
                            f"of the joint model minus that of its "
                            f"pipeline's individual model on the same "
                            f"pair; above 0 the joint model is the more "
                            f"reproducible")
        written.append(name)
    if not written:
        print("  no paired replicate agreement to plot")
    return written


def plot_peak_figures(peaks, outdir):
    """Peak count and mean peak length per mark, one panel per dataset."""
    written = []
    if peaks.empty:
        print("  no peak statistics to plot")
        return written
    models = [m for m in PEAK_MODELS if (peaks["Method"] == m).any()]
    datasets = [d for d in DATASETS if (peaks["Dataset"] == d).any()]
    marks = [m for m in PEAK_MARKS if (peaks["Mark"] == m).any()]
    by_mark = dict(x_col="Mark", x_order=marks, panel_col="Dataset",
                   panels=datasets, panel_labels=DATASET_NAMES, rotation=45,
                   figwidth=6.0)

    counts = peaks.assign(**{"Peaks (×10³)": peaks["N_Peaks"] / 1000.0})
    written.append(_summary_figure(
        counts, models, "Peaks (×10³)",
        os.path.join(outdir, "peaks_number_by_mark.pdf"),
        "Number of peaks per mark and model", ylabel="Peaks (×10³)",
        notes=[_thinned_note(counts, ("Dataset", "Method", "Mark"))],
        **by_mark))

    lengths = peaks[peaks["N_Peaks"] > 0]
    empty = len(peaks) - len(lengths)
    written.append(_summary_figure(
        lengths, models, "Mean_Length",
        os.path.join(outdir, "peaks_mean_length_by_mark.pdf"),
        "Mean peak length per mark and model",
        ylabel="Mean peak length (bp, log scale)", log=True,
        notes=[f"log scale; {empty} of the {len(peaks)} (sample, mark) calls "
               f"are empty, have no length and are left out here" if empty
               else "log scale",
               _thinned_note(lengths, ("Dataset", "Method", "Mark"))],
        **by_mark))
    return written


COMBINATIONS_LABEL = "Share of possible combinations"


def _combination_frame(rows):
    return rows.assign(**{
        "Caller": rows["Caller"].astype(str),
        "Dataset Name": rows["Dataset"].astype(str).map(DATASET_NAMES),
        COMBINATIONS_LABEL: rows["Share"]})


def _marks_note(rows):
    marks = rows.groupby("Dataset", observed=True)["Marks"].agg(["min", "max"])
    return "marks per sample - " + ", ".join(
        f"{DATASET_NAMES[d]} {lo}" + (f"-{hi}" if hi != lo else "")
        for d, (lo, hi) in marks.iterrows())


def plot_mark_combination_figures(combinations, outdir):
    """The share of all possible mark combinations a caller's binarization
    reaches, a bar per dataset and one point per sample."""
    if combinations.empty:
        print("  no binarization mark combinations to plot")
        return []
    callers = [c for c in CALLER_ORDER
               if (combinations["Caller"].astype(str) == c).any()]
    style = dict(hue="Caller", hue_order=callers, palette=CALLER_PALETTE,
                 hatch=None, ylim=(0, 1.05), rotation=0,
                 points=SUMMARY_POINTS, legend_title="Caller")

    used = _combination_frame(combination_usage(combinations))
    datasets = [d for d in DATASETS if (used["Dataset"] == d).any()]
    path = os.path.join(outdir, "mark_combinations_used.pdf")
    utils.bar_plot(used, "Dataset Name", COMBINATIONS_LABEL,
                   order=[DATASET_NAMES[d] for d in datasets],
                   point_data=_thin_points(used, ("Dataset Name", "Caller")),
                   figsize=PANEL_SIZE, legend=True,
                   title="Mark combinations present in the binarization",
                   xlabel="Dataset", ylabel=COMBINATIONS_LABEL, **style)
    utils.save_fig(plt.gcf(), path, note="- " + "; ".join(filter(None, [
        "share of all 2^M - 1 non-empty combinations of the M marks found in "
        "at least one bin", _marks_note(combinations),
        _thinned_note(used, ("Dataset", "Caller"))])))
    return [os.path.basename(path)]


def plot_replicate_family_heatmaps(families, outdir):
    """Model x state family heatmaps of the replicate agreement over every
    state, one figure per metric."""
    if families.empty:
        print("  no per-state families to plot")
        return []
    missing = sorted({f"{utils.display_name(m)} in {DATASET_NAMES[d]}"
                      for d in DATASETS for m in METHODS if m != REFERENCE
                      if (families["Dataset"] == d).any()
                      and not ((families["Dataset"] == d)
                               & (families["Method"] == m)).any()})
    written = []
    for metric in [SUMMARY_METRIC_LABELS[m] for m in REP_STATE_METRICS]:
        table = family_table(families, metric)
        if table.empty:
            continue
        fig, ax = plt.subplots(figsize=(3.0 + 1.1 * table.shape[1],
                                        0.7 * (1.0 + 0.38 * table.shape[0])))
        sns.heatmap(_column_contrast(table), ax=ax, vmin=0, vmax=1,
                    cmap=_family_colormap(), annot=table.values, fmt=".2f",
                    # Every model named: seaborn thins the labels of a
                    # short heatmap otherwise.
                    yticklabels=[utils.display_name(m) for m in table.index],
                    # Dark on every band: they are all pale.
                    annot_kws={"fontsize": utils.ANNOTATION_FONTSIZE,
                               "color": "black"},
                    linewidths=0.5, linecolor="white",
                    cbar_kws={"shrink": 0.6})
        # The ladder is in column-scaled units, 0..100% of a column's range,
        # which no metric tick would read right; it shows the ramp only.
        cbar = ax.collections[0].colorbar
        cbar.set_ticks([])
        cbar.set_label("Per state normalized", fontsize=utils.AXIS_FONTSIZE)
        ax.set_title(f"Replicate {metric} per state family",
                     **utils.TITLE_STYLE)
        ax.set_xlabel("")
        ax.set_ylabel("")
        # The individual and the joint family apart.
        n_individual = sum(not is_joint(m) for m in table.index)
        if 0 < n_individual < len(table):
            ax.axhline(n_individual, color="white", linewidth=3)
        ax.tick_params(axis="y", labelsize=utils.TICK_FONTSIZE,
                       labelrotation=0)
        ax.tick_params(axis="x", labelsize=utils.TICK_FONTSIZE, rotation=45)
        notes = ["cell = mean over the states of a family within a "
                 "replicate pair, then over the pairs of a dataset, then "
                 "over the datasets",
                 "colour runs from the minimum to the maximum of each "
                 "column on its own, so it ranks the models within a "
                 "family and does not compare families, in bands of "
                 f"{FAMILY_COLOUR_STEP:.0%} of a column's range; the top "
                 f"{1 - FAMILY_COLOUR_TOP:.0%} shares the top colour",
                 f"no pairs for {', '.join(missing)}" if missing else None]
        name = (f"agreement_replicates_per_state_families_"
                f"{utils.slug(metric)}.pdf")
        utils.save_fig(fig, os.path.join(outdir, name),
                       note=f"- {'; '.join(n for n in notes if n)}")
        written.append(name)
    return written

In [14]:
# Top annotation strips for the summary heatmaps.  The upper strip separates
# direct biological benchmarks from indirect/technical ones; the lower strip
# encodes the ranking group.  All strip colours are drawn from one palette so
# a colour identifies only one category across both strips.
HEATMAP_STRIP_COLORS = {
    "Biological": "#1F77B4",
    "Indirect": "#FF7F0E",
    "Replicates": "#2CA02C",
    "Biological assay": "#D62728",
    "Segmentation": "#9467BD",
    "Cross-sample": "#8C564B",
    "Assay": "#E377C2",
    "Individual / Join": "#7F7F7F",
}
HEATMAP_GROUP_COLORS = {group: HEATMAP_STRIP_COLORS[group]
                        for group in RANKING_GROUPS}
HEATMAP_BENCHMARK_COLORS = {kind: HEATMAP_STRIP_COLORS[kind]
                            for kind in ["Biological", "Indirect"]}
HEATMAP_TOP_STRIP_HEIGHT = 0.3
HEATMAP_TOP_STRIP_GAP = 0.05
HEATMAP_STRIP_HEATMAP_GAP = HEATMAP_TOP_STRIP_HEIGHT / 2


def _axis_group(axis):
    """Ranking group of one summary axis, or None when ungrouped."""
    return next((group for group, axes in RANKING_GROUPS.items()
                 if str(axis) in axes), None)


def _axis_benchmark_class(axis):
    """Replicate and biological-assay axes are biological benchmarks; the
    rest are indirect benchmarks of stability or consistency."""
    return "Biological" if _axis_group(axis) in {"Replicates", "Biological assay"} else "Indirect"


def _draw_heatmap_top_strips(ax, axes_keys):
    """Coloured strips above a heatmap: benchmark type on top, group below."""
    y_group = -HEATMAP_STRIP_HEATMAP_GAP - HEATMAP_TOP_STRIP_HEIGHT
    y_kind = y_group - HEATMAP_TOP_STRIP_GAP - HEATMAP_TOP_STRIP_HEIGHT
    for x, axis in enumerate(axes_keys):
        kind = _axis_benchmark_class(axis)
        ax.add_patch(plt.Rectangle(
            (x, y_kind), 1, HEATMAP_TOP_STRIP_HEIGHT,
            facecolor=HEATMAP_BENCHMARK_COLORS[kind],
            edgecolor="none", clip_on=False, transform=ax.transData))
        group = _axis_group(axis)
        if group is not None:
            ax.add_patch(plt.Rectangle(
                (x, y_group), 1, HEATMAP_TOP_STRIP_HEIGHT,
                facecolor=HEATMAP_GROUP_COLORS.get(group, "#BBBBBB"),
                edgecolor="none", clip_on=False, transform=ax.transData))
    ax.set_ylim(len(ax.get_yticklabels()), y_kind - HEATMAP_TOP_STRIP_HEIGHT)


def _heatmap_strip_legend(axes_keys):
    """Full legend of every strip category, even if absent from this heatmap."""
    handles = [Patch(facecolor=HEATMAP_BENCHMARK_COLORS[k], edgecolor="none",
                     label=k) for k in ["Biological", "Indirect"]]
    handles += [Patch(facecolor=HEATMAP_GROUP_COLORS[g], edgecolor="none",
                      label=g) for g in RANKING_GROUPS]
    return handles


def _axis_heatmap(colour, annot, cmap, cbar_ticks, cbar_label, title, notes,
                  outpath, mark_low=False):
    """One Method x axis heatmap: `colour` on [0, 1] colours the cells,
    `annot` is printed on them. Strips above the cells encode whether a
    benchmark is biological or indirect, then its axis group."""
    methods, axes_keys = list(colour.index), list(colour.columns)
    fig, ax = plt.subplots(figsize=(0.56 * (3.0 + 1.1 * len(axes_keys)),
                                    0.7 * (1.0 + 0.38 * len(methods)) + 2.2))
    sns.heatmap(colour, ax=ax, vmin=0, vmax=1, cmap=cmap,
                annot=np.vectorize(_value_text)(annot.values), fmt="",
                yticklabels=[utils.display_name(m) for m in methods],
                xticklabels=[_barplot_axis_label(a, mark_low)
                             for a in axes_keys],
                annot_kws={"fontsize": utils.ANNOTATION_FONTSIZE,
                           "color": "black"},
                linewidths=0.5, linecolor="white",
                cbar_kws={"shrink": 0.6})
    _group_gaps(ax, axes_keys)
    _draw_heatmap_top_strips(ax, axes_keys)
    cbar = ax.collections[0].colorbar
    cbar.set_ticks(cbar_ticks)
    cbar.ax.tick_params(labelsize=utils.TICK_FONTSIZE)
    cbar.set_label(cbar_label, fontsize=utils.AXIS_FONTSIZE)
    ax.set_title(title, **utils.TITLE_STYLE)
    ax.set_xlabel("")
    ax.set_ylabel("")
    ax.tick_params(axis="y", labelsize=utils.TICK_FONTSIZE, labelrotation=0)
    ax.tick_params(axis="x", labelsize=utils.TICK_FONTSIZE, rotation=45)
    for label in ax.get_xticklabels():
        label.set_ha("right")
    ax.legend(handles=_heatmap_strip_legend(axes_keys), title="Types",
              fontsize=utils.LEGEND_FONTSIZE,
              title_fontsize=utils.LEGEND_TITLE_FONTSIZE,
              bbox_to_anchor=(1.16, 1), loc="upper left", borderaxespad=0)
    utils.save_fig(
        fig, outpath,
        note=f"- {'; '.join(notes + ['Types: biological vs indirect benchmark, then ranking group'])}")

In [15]:
plot_heatmap_ranks(table_scores, OUT)
plot_heatmap_values(table_values, OUT)
for group, ranking in [
        ("individual", df_ranking_individual),
        ("joint", df_ranking_joint)]:
    plot_ranking(ranking, table_scores, group,
                 f"{OUT}/ranking_all_{group}.pdf")
plot_segment_counts(df_segment_counts, OUT)
plot_annotated_share(df_annotated, OUT)
plot_entropy_figures(df_entropy_summary, OUT)
plot_entropy_global_variance(df_entropy_summary, OUT)
plot_entropy_omni(df_entropy_omni, OUT)
plot_entropy_omni_variance(df_entropy_omni, OUT)
plot_entropy_omni_datasets(df_entropy_summary, OUT)
plot_comparison_figures(df_comparisons, OUT)
plot_replicate_joint_gain(df_comparisons, OUT)
plot_replicate_family_heatmaps(df_rep_families, OUT)
plot_joint_indiv_kappa(df_comparisons, OUT)
plot_mark_combination_figures(df_mark_combinations, OUT)

  saved out/summary/heatmap_ranks_individual.pdf - cell = the axis' rank score within the family, the same as the rank radar; colour in bands of 0.1; Types: biological vs indirect benchmark, then ranking group
  saved out/summary/heatmap_ranks_joint.pdf - cell = the axis' rank score within the family, the same as the rank radar; colour in bands of 0.1; Types: biological vs indirect benchmark, then ranking group

  saved out/summary/heatmap_values_individual.pdf - cell = the axis value, the same as the value radar; colour runs from the worst to the best value of each column on its own (↓ = lower is better, flipped), so it ranks the models within an axis and does not compare axes, in bands of 10% of a column's range; the top 20% shares the top colour; Types: biological vs indirect benchmark, then ranking group
  saved out/summary/heatmap_values_joint.pdf - cell = the axis value, the same as the value radar; colour runs from the worst to the best value of each column on its own (↓ = lower is better, flipped), so it ranks the models within an axis and does not compare axes, in bands of 10% of a column's range; the top 20% shares the top colour; Types: biological vs indirect benchmark, then ranking group

  saved out/summary/ranking_all_individual.pdf
  saved out/summary/ranking_all_joint.pdf

  saved out/summary/segment_counts_all.pdf - ENCODE per-replicate segmentations, the scope its joint models exist in; its reference markup is the pooled one, it has no per-replicate counterpart

  saved out/summary/state_counts_all.pdf - ENCODE per-replicate segmentations, the scope its joint models exist in; its reference markup is the pooled one, it has no per-replicate counterpart
  saved out/summary/state_counts_methods.pdf

  saved out/summary/annotated_share_all.pdf - ENCODE per-replicate segmentations, the scope its joint models exist in; its reference markup is the pooled one, it has no per-replicate counterpart
  saved out/summary/annotated_share_chromhmm.pdf

  saved out/summary/annotated_share_omni_bmm3_vs_chromhmm.pdf - 12 ENCODE datasets, pooled segmentations, point = one dataset
  saved out/summary/annotated_share_variance_omni_bmm3_vs_chromhmm.pdf - 12 ENCODE datasets, pooled segmentations; bar = variance over the datasets, point = one dataset's squared deviation from its model's mean
  saved out/summary/annotated_share_omni_bmm3_vs_chromhmm_datasets.pdf - segmentations per model - ENCODE 12, SAGAconf 10, 1000 epigenomes 98; ENCODE pooled, SAGAconf both replicates; the reference on ENCODE only

  saved out/summary/annotated_share_variance_omni_bmm3_vs_chromhmm_datasets.pdf - segmentations per model - ENCODE 12, SAGAconf 10, 1000 epigenomes 98; ENCODE pooled, SAGAconf both replicates; the reference on ENCODE only; bar = variance over the dataset's segmentations, point = one segmentation's squared deviation from its mean
  saved out/summary/entropy_all.pdf

  saved out/summary/entropy_global_variance.pdf - all datasets pooled; models Default ChromHMM, Homer KMeans, MACS2 KMeans, OmniPeak KMeans; bar = variance of the entropy pooled over all datasets, point = one segmentation's squared deviation from the pooled mean; 10 points above the axes, up to 177 (monocytes_mint:chromhmm_default); values per dataset - Default ChromHMM: ENCODE 18, SAGAconf 10, 1000 epigenomes 98; Homer KMeans: ENCODE 18, SAGAconf 10, 1000 epigenomes 98; MACS2 KMeans: ENCODE 18, SAGAconf 10, 1000 epigenomes 98; OmniPeak KMeans: ENCODE 18, SAGAconf 10, 1000 epigenomes 98
  saved out/summary/entropy_omni_bmm3_vs_chromhmm.pdf - 12 ENCODE datasets, pooled segmentations, point = one dataset; monocytes_mint ChromHMM default (0.647) above the axes
  saved out/summary/entropy_variance_omni_bmm3_vs_chromhmm.pdf - 12 ENCODE datasets, pooled segmentations; bar = variance over the datasets, point = one dataset's squared deviation from its model's mean; monocytes_mint ChromHMM default (128) above the axes

  saved out/summary/entropy_omni_bmm3_vs_chromhmm_datasets.pdf - segmentations per model - ENCODE 12, SAGAconf 10, 1000 epigenomes 98; ENCODE pooled, SAGAconf both replicates; the reference on ENCODE only
  saved out/summary/entropy_variance_omni_bmm3_vs_chromhmm_datasets.pdf - segmentations per model - ENCODE 12, SAGAconf 10, 1000 epigenomes 98; ENCODE pooled, SAGAconf both replicates; the reference on ENCODE only; bar = variance over the dataset's segmentations, point = one segmentation's squared deviation from its mean; 1 point above the axes, up to 128 (monocytes_mint:chromhmm_default)

  saved out/summary/agreement_cross_sample_composition_all.pdf - points thinned to 150 of the 1000 on the densest bar; every bar is the mean over all of them

  saved out/summary/agreement_cross_sample_kappa_all.pdf - points thinned to 150 of the 1000 on the densest bar; every bar is the mean over all of them

  saved out/summary/agreement_cross_sample_jaccard_all.pdf - points thinned to 150 of the 1000 on the densest bar; every bar is the mean over all of them

  saved out/summary/agreement_cross_sample_ami_all.pdf - points thinned to 150 of the 1000 on the densest bar; every bar is the mean over all of them

  saved out/summary/agreement_replicates_composition_all.pdf
  saved out/summary/agreement_replicates_kappa_all.pdf

  saved out/summary/agreement_replicates_jaccard_all.pdf
  saved out/summary/agreement_replicates_ami_all.pdf

  saved out/summary/agreement_joint_indiv_composition_all.pdf
  saved out/summary/agreement_joint_indiv_kappa_all.pdf

  saved out/summary/agreement_joint_indiv_jaccard_all.pdf
  saved out/summary/agreement_joint_indiv_ami_all.pdf

  saved out/summary/agreement_replicates_composition_joint_minus_individual.pdf - point = one replicate pair, the Composition of the joint model minus that of its pipeline's individual model on the same pair; above 0 the joint model is the more reproducible
  saved out/summary/agreement_replicates_kappa_joint_minus_individual.pdf - point = one replicate pair, the Kappa of the joint model minus that of its pipeline's individual model on the same pair; above 0 the joint model is the more reproducible

  saved out/summary/agreement_replicates_jaccard_joint_minus_individual.pdf - point = one replicate pair, the Jaccard of the joint model minus that of its pipeline's individual model on the same pair; above 0 the joint model is the more reproducible
  saved out/summary/agreement_replicates_ami_joint_minus_individual.pdf - point = one replicate pair, the AMI of the joint model minus that of its pipeline's individual model on the same pair; above 0 the joint model is the more reproducible

  saved out/summary/agreement_replicates_per_state_families_jaccard.pdf - cell = mean over the states of a family within a replicate pair, then over the pairs of a dataset, then over the datasets; colour runs from the minimum to the maximum of each column on its own, so it ranks the models within a family and does not compare families, in bands of 10% of a column's range; the top 20% shares the top colour
  saved out/summary/agreement_replicates_per_state_families_kappa.pdf - cell = mean over the states of a family within a replicate pair, then over the pairs of a dataset, then over the datasets; colour runs from the minimum to the maximum of each column on its own, so it ranks the models within a family and does not compare families, in bands of 10% of a column's range; the top 20% shares the top colour

  saved out/summary/agreement_joint_indiv_kappa_global.pdf - all datasets pooled; models Default ChromHMM, Homer KMeans, MACS2 KMeans, OmniPeak KMeans; point = one sample, its individual segmentation against its joint-model segmentation; values per dataset - Default ChromHMM: ENCODE 6, SAGAconf 5, 1000 epigenomes 98; Homer KMeans: ENCODE 6, SAGAconf 5, 1000 epigenomes 98; MACS2 KMeans: ENCODE 6, SAGAconf 5, 1000 epigenomes 98; OmniPeak KMeans: ENCODE 6, SAGAconf 5, 1000 epigenomes 98
  saved out/summary/mark_combinations_used.pdf - share of all 2^M - 1 non-empty combinations of the M marks found in at least one bin; marks per sample - ENCODE 6, SAGAconf 11-13, 1000 epigenomes 6

['mark_combinations_used.pdf']

In [16]:
# OmniPeak BMM3 - ChromHMM, per comparison of OMNI_VS_COMPARISONS: one figure
# per metric with a box per ChromHMM baseline, every unit on top and the
# number of units above and below 0; and one scatter per metric and baseline,
# the two agreements of a unit against each other. Above 0, and above the
# diagonal, OmniPeak BMM3 keeps more of its segmentation from one side of the
# comparison to the other.
OMNI_VS_CHROMHMM_PALETTE = {
    label: utils.method_color(baseline)
    for baseline, label in OMNI_VS_CHROMHMM_BASELINES.items()}

# (title prefix, what one unit is) per comparison; the key prefixes the files.
OMNI_VS_COMPARISONS = {
    "cross_sample": ("Cross-sample", "same-assay ENCODE sample pairs"),
    "replicates": ("Replicate", "ENCODE replicate pairs, rep1 vs rep2"),
    "replicates_sagaconf": ("SAGAconf replicate",
                            "SAGAconf replicate pairs, rep1 vs rep2"),
    "replicates_epi1000": ("1000 epigenomes replicate",
                           "1000 epigenomes replicate pairs, two epigenomes "
                           "of one condition"),
}


def _omni_vs_baselines(rows):
    """The baseline labels `rows` holds, in OMNI_VS_CHROMHMM_BASELINES order."""
    return [label for label in OMNI_VS_CHROMHMM_BASELINES.values()
            if (rows["Baseline"] == label).any()]


def _omni_vs_groups(rows):
    """`rows` with the Group a box is drawn for, in drawing order: the
    baseline, or the dataset and the baseline when `rows` hold several
    datasets (a Data column, as DATASET_NAMES)."""
    if "Data" not in rows or rows["Data"].nunique() < 2:
        rows = rows.assign(Group=rows["Baseline"])
        return rows, _omni_vs_baselines(rows)
    rows = rows.assign(Group=rows["Data"] + "\n" + rows["Baseline"])
    order = [f"{DATASET_NAMES[d]}\n{b}" for d in DATASETS
             for b in OMNI_VS_CHROMHMM_BASELINES.values()]
    return rows, [g for g in order if (rows["Group"] == g).any()]


def plot_omni_vs_chromhmm(rows, outdir, comparison="cross_sample", units=None):
    """A box per baseline - per dataset and baseline when `rows` hold several
    datasets - one figure per metric. `units` replaces the comparison's
    description of a unit in the note."""
    prefix, default_units = OMNI_VS_COMPARISONS[comparison]
    units = units or default_units
    if rows.empty:
        print(f"  no OmniPeak BMM3 vs ChromHMM {units} to plot")
        return []
    rows, order = _omni_vs_groups(rows)
    baselines = _omni_vs_baselines(rows)
    several = len(order) > len(baselines)
    written = []
    for metric in OMNI_VS_CHROMHMM_METRICS:
        panel = rows[rows["Metric"] == metric]
        if panel.empty:
            continue
        fig, ax = plt.subplots(figsize=(1.5 + 1.5 * len(order), 4.5))
        # Coloured by the group itself: a hue other than x, undodged, has
        # seaborn give some boxes another baseline's colour.
        colors = {g: OMNI_VS_CHROMHMM_PALETTE[b] for g, b in
                  zip(panel["Group"], panel["Baseline"])}
        sns.boxplot(panel, x="Group", y="Value", hue="Group",
                    order=order, hue_order=order, palette=colors, width=0.5,
                    showfliers=False, linewidth=utils.BAR_STYLE["linewidth"],
                    legend=False, ax=ax)
        # The 1000 epigenome pairs are drawn thinned, as every summary figure
        # draws its densest bars; the boxes and counts are over all of them.
        points = _thin_points(panel, ("Group",))
        utils.strip_points(ax, data=panel if points is None else points,
                           x="Group", y="Value", order=order, dodge=False)
        # The units on either side of 0, above and below each box.
        ax.margins(y=0.15)
        # x in data, y in axes coordinates: a slight gap from the frame.
        at = ax.get_xaxis_transform()
        for x, group in enumerate(order):
            values = panel.loc[panel["Group"] == group, "Value"]
            ax.text(x, 0.97, f">0: {(values > 0).sum()}", transform=at,
                    ha="center", va="top",
                    fontsize=utils.ANNOTATION_FONTSIZE)
            ax.text(x, 0.03, f"<0: {(values < 0).sum()}", transform=at,
                    ha="center", va="bottom",
                    fontsize=utils.ANNOTATION_FONTSIZE)
        ax.axhline(0, color="black", linewidth=0.8)
        ax.grid(axis="y", alpha=0.3)
        ax.set_title(f"{prefix} {metric}:\nOmniPeak BMM3 vs ChromHMM",
                     **utils.TITLE_STYLE)
        ax.set_xlabel("Dataset and baseline" if several else "Baseline")
        ax.set_ylabel(f"{metric}: OmniPeak BMM3 − baseline")
        name = f"{comparison}_omni_bmm3_vs_chromhmm_{utils.slug(metric)}.pdf"
        counts = panel.groupby("Group")["Pair"].nunique()
        what = (", ".join(f"{g.replace(chr(10), ' vs ')} {counts[g]}"
                          for g in order) if several
                else f"{panel['Pair'].nunique()}")
        thinned = _thinned_note(panel, ("Group",))
        utils.save_fig(fig, os.path.join(outdir, name), bar_width=False,
                       note=f"- {units}: {what}; each the OmniPeak BMM3 "
                            f"{metric} minus that of the baseline on the "
                            f"same pair" + (f"; {thinned}" if thinned else ""))
        written.append(name)
    return written


def plot_omni_vs_chromhmm_scatter(rows, outdir, comparison="cross_sample"):
    """OmniPeak BMM3 against a ChromHMM baseline on the same unit, one figure
    per metric and baseline; above the diagonal OmniPeak BMM3 agrees more.
    The baselines of a metric share their axes, so their figures read side by
    side."""
    prefix, units = OMNI_VS_COMPARISONS[comparison]
    if rows.empty:
        print(f"  no OmniPeak BMM3 vs ChromHMM {units} to plot")
        return []
    model = utils.display_name(BMM3_OMNI)
    written = []
    for metric in OMNI_VS_CHROMHMM_METRICS:
        by_metric = rows[rows["Metric"] == metric]
        if by_metric.empty:
            continue
        values = by_metric[["Baseline value", "Model value"]].to_numpy()
        pad = 0.05 * (values.max() - values.min())
        lims = (values.min() - pad, values.max() + pad)
        for label in _omni_vs_baselines(by_metric):
            panel = by_metric[by_metric["Baseline"] == label]
            fig, ax = plt.subplots(figsize=(4.5, 4.5))
            ax.scatter(panel["Baseline value"], panel["Model value"],
                       s=POINT_SIZE, **{**utils.POINT_STYLE,
                                        "color": OMNI_VS_CHROMHMM_PALETTE[label]})
            ax.plot(lims, lims, color="black", linewidth=0.8, linestyle="--")
            # The units on either side of the diagonal, in the corner of
            # their half.
            above = (panel["Model value"] > panel["Baseline value"]).sum()
            below = (panel["Model value"] < panel["Baseline value"]).sum()
            ax.text(0.04, 0.96, f"above: {above}", transform=ax.transAxes,
                    ha="left", va="top", fontsize=utils.ANNOTATION_FONTSIZE)
            ax.text(0.96, 0.04, f"below: {below}", transform=ax.transAxes,
                    ha="right", va="bottom",
                    fontsize=utils.ANNOTATION_FONTSIZE)
            ax.set_xlim(lims)
            ax.set_ylim(lims)
            ax.set_aspect("equal")
            ax.grid(alpha=0.3)
            ax.set_title(f"{prefix} {metric}:\n{model} vs {label}",
                         **utils.TITLE_STYLE)
            ax.set_xlabel(f"{metric}, {label}")
            ax.set_ylabel(f"{metric}, {model}")
            name = (f"{comparison}_omni_bmm3_vs_chromhmm_{utils.slug(metric)}"
                    f"_scatter_{utils.slug(label)}.pdf")
            utils.save_fig(fig, os.path.join(outdir, name), bar_width=False,
                           note=f"- {len(panel)} {units}; dashed = equal "
                                f"agreement, {above} above it, {below} below")
            written.append(name)
    return written



def plot_omni_vs_chromhmm_replicates_joint(reps, outdir):
    """The replicate OmniPeak BMM3 - ChromHMM default difference of every
    dataset in one figure per metric, a box per dataset, every replicate pair
    on top and the number of pairs above and below 0."""
    datasets = {comparison: DATASET_NAMES["encode" if comparison == "replicates"
                                          else comparison.split("_", 1)[1]]
                for comparison in reps}
    rows = pd.concat([r.assign(Data=datasets[c]) for c, r in reps.items()
                      if not r.empty], ignore_index=True)
    if rows.empty:
        print("  no OmniPeak BMM3 vs ChromHMM replicate pairs to plot")
        return []
    order = [d for d in datasets.values() if (rows["Data"] == d).any()]
    color = OMNI_VS_CHROMHMM_PALETTE[OMNI_VS_CHROMHMM_BASELINES[CHROMHMM_DEFAULT]]
    written = []
    for metric in OMNI_VS_CHROMHMM_METRICS:
        panel = rows[rows["Metric"] == metric]
        if panel.empty:
            continue
        fig, ax = plt.subplots(figsize=(1.5 + 1.5 * len(order), 4.5))
        sns.boxplot(panel, x="Data", y="Value", order=order, color=color,
                    width=0.5, showfliers=False,
                    linewidth=utils.BAR_STYLE["linewidth"], ax=ax)
        utils.strip_points(ax, data=panel, x="Data", y="Value", order=order,
                           dodge=False)
        # The pairs on either side of 0, above and below each box.
        ax.margins(y=0.15)
        # x in data, y in axes coordinates: a slight gap from the frame.
        at = ax.get_xaxis_transform()
        for x, data in enumerate(order):
            values = panel.loc[panel["Data"] == data, "Value"]
            ax.text(x, 0.97, f">0: {(values > 0).sum()}", transform=at,
                    ha="center", va="top",
                    fontsize=utils.ANNOTATION_FONTSIZE)
            ax.text(x, 0.03, f"<0: {(values < 0).sum()}", transform=at,
                    ha="center", va="bottom",
                    fontsize=utils.ANNOTATION_FONTSIZE)
        ax.axhline(0, color="black", linewidth=0.8)
        ax.grid(axis="y", alpha=0.3)
        ax.set_title(f"Replicate {metric}:\nOmniPeak BMM3 vs ChromHMM",
                     **utils.TITLE_STYLE)
        ax.set_xlabel("Dataset")
        ax.set_ylabel(f"{metric}: OmniPeak BMM3 − baseline")
        name = f"replicates_all_omni_bmm3_vs_chromhmm_{utils.slug(metric)}.pdf"
        counts = panel.groupby("Data")["Pair"].nunique()
        utils.save_fig(fig, os.path.join(outdir, name), bar_width=False,
                       note="- replicate pairs per dataset: " + ", ".join(
                           f"{d} {counts[d]}" for d in order))
        written.append(name)
    return written


# Across samples the boxes cover every dataset; the scatters stay ENCODE only,
# the one dataset with a reference.
plot_omni_vs_chromhmm(
    pd.concat([rows.assign(Data=DATASET_NAMES[dataset])
               for dataset, rows in df_omni_vs_chromhmm_cs.items()
               if not rows.empty], ignore_index=True),
    OUT, "cross_sample",
    units="sample pairs (ENCODE same-assay, SAGAconf every cell-line pair, "
          "1000 epigenomes a reproducible sample)")
plot_omni_vs_chromhmm_scatter(df_omni_vs_chromhmm, OUT, "cross_sample")
for comparison, rows in df_omni_vs_chromhmm_reps.items():
    plot_omni_vs_chromhmm(rows, OUT, comparison)
    plot_omni_vs_chromhmm_scatter(rows, OUT, comparison)
plot_omni_vs_chromhmm_replicates_joint(df_omni_vs_chromhmm_reps, OUT)

  saved out/summary/cross_sample_omni_bmm3_vs_chromhmm_kappa.pdf - sample pairs (ENCODE same-assay, SAGAconf every cell-line pair, 1000 epigenomes a reproducible sample): ENCODE vs ENCODE Reference 46, ENCODE vs ChromHMM default 46, SAGAconf vs ChromHMM default 10, 1000 epigenomes vs ChromHMM default 1000; each the OmniPeak BMM3 Kappa minus that of the baseline on the same pair; points thinned to 150 of the 1000 on the densest bar; every bar is the mean over all of them
  saved out/summary/cross_sample_omni_bmm3_vs_chromhmm_ami.pdf - sample pairs (ENCODE same-assay, SAGAconf every cell-line pair, 1000 epigenomes a reproducible sample): ENCODE vs ENCODE Reference 46, ENCODE vs ChromHMM default 46, SAGAconf vs ChromHMM default 10, 1000 epigenomes vs ChromHMM default 1000; each the OmniPeak BMM3 AMI minus that of the baseline on the same pair; points thinned to 150 of the 1000 on the densest bar; every bar is the mean over all of them
  saved out/summary/cross_sample_omni_bmm3_vs_chromhmm_kappa_scatter_encode_reference.pdf - 46 same-assay ENCODE sample pairs; dashed = equal agreement, 26 above it, 20 below

  saved out/summary/cross_sample_omni_bmm3_vs_chromhmm_kappa_scatter_chromhmm_default.pdf - 46 same-assay ENCODE sample pairs; dashed = equal agreement, 35 above it, 11 below
  saved out/summary/cross_sample_omni_bmm3_vs_chromhmm_ami_scatter_encode_reference.pdf - 46 same-assay ENCODE sample pairs; dashed = equal agreement, 24 above it, 22 below
  saved out/summary/cross_sample_omni_bmm3_vs_chromhmm_ami_scatter_chromhmm_default.pdf - 46 same-assay ENCODE sample pairs; dashed = equal agreement, 13 above it, 33 below

  saved out/summary/replicates_omni_bmm3_vs_chromhmm_kappa.pdf - ENCODE replicate pairs, rep1 vs rep2: 3; each the OmniPeak BMM3 Kappa minus that of the baseline on the same pair
  saved out/summary/replicates_omni_bmm3_vs_chromhmm_kappa_scatter_chromhmm_default.pdf - 3 ENCODE replicate pairs, rep1 vs rep2; dashed = equal agreement, 2 above it, 1 below
  saved out/summary/replicates_sagaconf_omni_bmm3_vs_chromhmm_kappa.pdf - SAGAconf replicate pairs, rep1 vs rep2: 5; each the OmniPeak BMM3 Kappa minus that of the baseline on the same pair

  saved out/summary/replicates_sagaconf_omni_bmm3_vs_chromhmm_kappa_scatter_chromhmm_default.pdf - 5 SAGAconf replicate pairs, rep1 vs rep2; dashed = equal agreement, 4 above it, 1 below
  saved out/summary/replicates_epi1000_omni_bmm3_vs_chromhmm_kappa.pdf - 1000 epigenomes replicate pairs, two epigenomes of one condition: 22; each the OmniPeak BMM3 Kappa minus that of the baseline on the same pair
  saved out/summary/replicates_epi1000_omni_bmm3_vs_chromhmm_kappa_scatter_chromhmm_default.pdf - 22 1000 epigenomes replicate pairs, two epigenomes of one condition; dashed = equal agreement, 17 above it, 5 below

  saved out/summary/replicates_all_omni_bmm3_vs_chromhmm_kappa.pdf - replicate pairs per dataset: ENCODE 3, SAGAconf 5, 1000 epigenomes 22

['replicates_all_omni_bmm3_vs_chromhmm_kappa.pdf']

# 3. Showing the results

In [17]:
header("Feature coverage")
display(table_coverage)

,Metric,ENCODE,SAGAconf,1000 epigenomes
Feature,,,,
Replicate agreement,Kappa / AMI,yes,yes,yes
Replicate composition,Cosine,yes,yes,yes
Replicate emission similarity,cosine of the state emissions,yes,yes,yes
Active chromatin vs ATAC-seq (Sensitivity),Sensitivity,yes,no,no
Active chromatin vs ATAC-seq (Precision),Precision,yes,no,no
Tss states vs expressed TSS (Sensitivity),Sensitivity,yes,no,no
Tss states vs expressed TSS (Precision),Precision,yes,no,no
Tss states vs RefSeq TSS (Sensitivity),Sensitivity,yes,no,no
Tss states vs RefSeq TSS (Precision),Precision,yes,no,no
Tx state vs expressed genes (Sensitivity),Sensitivity,yes,no,no
Tx state vs expressed genes (Precision),Precision,yes,no,no
Recovery of requested state count,fraction reaching k=15,yes,yes,yes
Segment-count stability,CV of segment number,yes,yes,yes
Transition Matrix Entropy stability,CV of entropy,yes,yes,yes
Cross-sample agreement,Kappa / AMI,yes,yes,yes
Cross-sample composition,Cosine,yes,yes,yes
Cross-assay counts stability,CV of segment number,yes,no,no
Cross-assay agreement,Kappa / AMI,yes,no,no
Cross-assay composition agreement,Cosine,yes,no,no
Individual / joint agreement,Kappa / AMI,yes,yes,yes
Individual / joint composition agreement,Cosine,yes,yes,yes

In [18]:
for group, ranking in [("individual", df_ranking_individual),
                       ("joint", df_ranking_joint)]:
    header(f"{group.capitalize()} models summary ranks")
    display(ranking.round(3))

,Rank,Method,Score,Axes,Datasets,Best axis,Worst axis
Key,,,,,,,
bmm3_omni,1,OmniPeak BMM3,0.707,19,3,Tss states vs expressed TSS (Sensitivity),Tss states vs expressed TSS (Precision)
kmeans_omni,2,OmniPeak KMeans,0.616,19,3,Tx state vs expressed genes (Sensitivity),Tx state vs expressed genes (Precision)
chromhmm_default,3,Default ChromHMM,0.564,19,3,Tx state vs expressed genes (Precision),Cross-sample composition
reference,4,ENCODE Reference,0.555,15,1,Tss states vs expressed TSS (Precision),Tss states vs expressed TSS (Sensitivity)
kmeans_macs2,5,MACS2 KMeans,0.513,19,3,Active chromatin vs ATAC-seq (Precision),Active chromatin vs ATAC-seq (Sensitivity)
bmm3_homer,6,Homer BMM3,0.498,19,3,Recovery of requested state count,Active chromatin vs ATAC-seq (Sensitivity)
bmm3_macs2,7,MACS2 BMM3,0.481,19,3,Recovery of requested state count,Tx state vs expressed genes (Sensitivity)
kmeans_homer,8,Homer KMeans,0.451,19,3,Tss states vs RefSeq TSS (Sensitivity),Recovery of requested state count

,Rank,Method,Score,Axes,Datasets,Best axis,Worst axis
Key,,,,,,,
joint_chromhmm,1,Joint ChromHMM,0.745,18,3,Replicate agreement,Individual / joint agreement
joint_kmeans_omni,2,Joint OmniPeak KMeans,0.648,18,3,Tx state vs expressed genes (Sensitivity),Tx state vs expressed genes (Precision)
joint_bmm3_omni,3,Joint OmniPeak BMM3,0.646,18,3,Active chromatin vs ATAC-seq (Sensitivity),Active chromatin vs ATAC-seq (Precision)
joint_kmeans_homer,4,Joint Homer KMeans,0.529,18,3,Tss states vs expressed TSS (Sensitivity),Recovery of requested state count
joint_kmeans_macs2,5,Joint MACS2 KMeans,0.454,18,3,Active chromatin vs ATAC-seq (Precision),Tss states vs expressed TSS (Sensitivity)
joint_bmm3_homer,6,Joint Homer BMM3,0.311,18,3,Tx state vs expressed genes (Precision),Active chromatin vs ATAC-seq (Precision)
joint_bmm3_macs2,7,Joint MACS2 BMM3,0.283,18,3,Recovery of requested state count,Active chromatin vs ATAC-seq (Sensitivity)

In [19]:
header(f"Replicate {KAPPA_DISPLAY} per state family")
display(family_table(df_rep_families, KAPPA_DISPLAY)
        .rename(index=utils.display_name).round(2))

header(f"Replicate {KAPPA_DISPLAY} per state family and dataset "
       f"(mean over the models)")
display(df_rep_families[df_rep_families["Metric"] == KAPPA_DISPLAY]
        .pivot_table(index="Family", columns="Dataset", values="Value",
                     aggfunc="mean", observed=True)
        .reindex(index=[f for f in STATE_FAMILIES
                        if f in set(df_rep_families["Family"])])
        .rename(columns=DATASET_NAMES).round(2))

Family,Promoter,Enhancer,Transcribed,Bivalent,Polycomb,Heterochromatin,Quiescent
Method,,,,,,,
Default ChromHMM,0.49,0.39,0.56,0.42,0.43,0.37,0.64
Homer KMeans,0.39,0.29,0.43,0.25,0.36,0.35,0.57
Homer BMM3,0.38,0.33,0.42,0.35,0.35,0.33,0.57
MACS2 KMeans,0.39,0.31,0.34,0.24,0.38,0.33,0.61
MACS2 BMM3,0.39,0.29,0.36,0.23,0.32,0.28,0.61
OmniPeak KMeans,0.45,0.38,0.54,0.24,0.44,0.47,0.65
OmniPeak BMM3,0.46,0.38,0.54,0.27,0.44,0.46,0.66
Joint ChromHMM,0.60,0.46,0.63,0.54,0.53,0.50,0.71
Joint Homer KMeans,0.41,0.34,0.44,0.28,0.37,0.36,0.57
Joint Homer BMM3,0.45,0.35,0.44,0.39,0.37,0.34,0.57
Joint MACS2 KMeans,0.48,0.34,0.40,0.37,0.41,0.33,0.61
Joint MACS2 BMM3,0.48,0.35,0.43,0.38,0.36,0.28,0.61
Joint OmniPeak KMeans,0.59,0.42,0.59,0.36,0.46,0.48,0.65
Joint OmniPeak BMM3,0.52,0.46,0.57,0.48,0.47,0.48,0.66

Dataset          ENCODE  SAGAconf  1000 epigenomes
Family
Promoter           0.45      0.58             0.35
Enhancer           0.38      0.48             0.23
Transcribed        0.54      0.60             0.29
Bivalent           0.42      0.49             0.23
Polycomb           0.64      0.36             0.22
Heterochromatin    0.49      0.36             0.29
Quiescent          0.67      0.69             0.51

In [20]:
header("Share of the possible mark combinations present in the binarization")
display(combination_usage(df_mark_combinations)
        .pivot_table(index="Caller", columns="Dataset", values="Share",
                     aggfunc="mean", observed=True)
        .rename(columns=DATASET_NAMES).round(3))

Dataset   ENCODE  SAGAconf  1000 epigenomes
Caller
HOMER      0.893     0.717            0.442
MACS2      0.857     0.319            0.857
ChromHMM   0.980     0.693            0.989
OmniPeak   0.999     0.654            0.999

In [21]:
for dataset, rows in df_omni_vs_chromhmm_cs.items():
    header(f"Cross-sample agreement: OmniPeak BMM3 − ChromHMM "
           f"({DATASET_NAMES[dataset]})")
    display(omni_vs_chromhmm_table(rows).round(3))

for comparison, rows in df_omni_vs_chromhmm_reps.items():
    header(f"{OMNI_VS_COMPARISONS[comparison][0]} agreement: "
           f"OmniPeak BMM3 − ChromHMM ({OMNI_VS_COMPARISONS[comparison][1]})")
    display(omni_vs_chromhmm_table(rows).round(3))

                         Pairs   Mean  Median  OmniPeak higher
Metric Baseline
Kappa  ENCODE Reference     46  0.012   0.017            0.565
       ChromHMM default     46  0.038   0.036            0.761
AMI    ENCODE Reference     46  0.005   0.004            0.522
       ChromHMM default     46 -0.014  -0.016            0.283

                         Pairs   Mean  Median  OmniPeak higher
Metric Baseline
Kappa  ChromHMM default     10  0.045   0.016              0.7
AMI    ChromHMM default     10 -0.034  -0.037              0.0

                         Pairs   Mean  Median  OmniPeak higher
Metric Baseline
Kappa  ChromHMM default   1000  0.043   0.043            0.682
AMI    ChromHMM default   1000 -0.028  -0.026            0.164

                         Pairs   Mean  Median  OmniPeak higher
Metric Baseline
Kappa  ChromHMM default      3  0.098   0.134            0.667

                         Pairs   Mean  Median  OmniPeak higher
Metric Baseline
Kappa  ChromHMM default      5  0.076   0.088              0.8

                         Pairs   Mean  Median  OmniPeak higher
Metric Baseline
Kappa  ChromHMM default     22  0.076   0.081            0.773